<?php
/*
 * Traductions
 */
class Trad extends Txt
{
	/*
	 * Chargement les elements de traduction
	 */
	public static function loadTrads()
	{
		////	Dates formatées par PHP
		setlocale(LC_TIME, "de_DE.utf8", "de_DE.UTF-8", "de_DE", "de", "german");

		////	TRADUCTIONS
		self::$trad=array(
			////	Langue de l'appli, des dates et de l'éditeur
			"CURLANG"=>"de",
			"DATELANG"=>"de_DE",
			"EDITORLANG"=>"de",
			"FANCYBOXLANG"=>"de",

			////	Divers
			"mainMenu"=>"Hauptmenü",
			"menuOptions"=>"Menü der Optionen",
			"emptyFields"=>"Bitte füllen Sie die Formularfelder aus",
			"requiredFields"=>"Bitte füllen Sie das Feld aus",
			"inaccessibleElem"=>"Das angeforderte Element ist nicht zugänglich",
			"warning"=>"Achtung",
			"elemEditedByAnotherUser"=>"Dieses Formular wird derzeit bearbeitet von",
			"yes"=>"ja",
			"no"=>"nein",
			"none"=>"keine",
			"or"=>"oder",
			"and"=>"und",
			"goToPage"=>"Gehe zu Seite",
			"alphabetFilter"=>"Alphabetischer Filter",
			"displayAll"=>"Alle anzeigen",
			"show"=>"Anzeigen",
			"hide"=>"Ausblenden",
			"byDefault"=>"Standardmäßig",
			"changeOrder"=>"Verschieben, um die Anzeigereihenfolge zu ändern",
			"mapLocalize"=>"Auf Karte anzeigen",
			"mapLocalizationFailure"=>"Folgende Adresse konnte nicht gefunden werden",
			"mapLocalizationFailure2"=>"Bitte überprüfen Sie, ob die Adresse auf www.google.fr/maps oder www.openstreetmap.org existiert",
			"sendMail"=>"E-Mail senden",
			"mailInvalid"=>"Die E-Mail ist ungültig",
			"element"=>"Element",
			"elements"=>"Elemente",
			"folder"=>"Ordner",
			"folders"=>"Ordner",
			"close"=>"Schließen",
			"modifRecorded"=>"Die Änderungen wurden gespeichert",
			"comment"=>"Kommentar",
			"commentAdd"=>"Kommentar hinzufügen",
			"optional"=>"(optional)",
			"objNew"=>"Kürzlich erstelltes Element",
			"objNewTooltip"=>"Erstellt innerhalb von 24 Stunden oder seit der letzten Anmeldung",
			"personalAccess"=>"Persönlicher Zugang",
			"copyUrl"=>"Freigabeadresse kopieren",
			"copyUrlTooltip"=>"Ermöglicht den Zugriff auf das Element über eine E-Mail, einen Blog usw.",
			"copyUrlNotif"=>"Die Adresse wurde erfolgreich kopiert",

			////	Confirm et Suppression
			"confirm"=>"Bestätigen",
			"confirmOk"=>"Ok",
			"confirmCancel"=>"Abbrechen",
			"confirmDownload"=>"Datei herunterladen ?",
			"confirmCloseForm"=>"Formular schließen ohne zu speichern?",
			"delete"=>"Löschen",
			"confirmDelete"=>"Löschen bestätigen?",
			"confirmDeleteAlert"=>"Achtung: Diese Aktion ist endgültig!",
			"confirmDeleteNotify"=>"Die Löschung war erfolgreich",
			"confirmDeleteSelect"=>"Endgültiges Löschen der ausgewählten Elemente bestätigen?",
			"confirmDeleteSelectNb"=>"ausgewählte Elemente",
			"confirmDeleteFolder"=>"Einige Unterordner sind für Sie zum Lesen nicht zugänglich: Trotzdem bestätigen?",
			"confirmDeleteWait"=>"Bitte warten Sie einen Moment: Das Löschen des Ordners kann einige Sekunden dauern",
			"notifDeleteFolderUncomplete"=>"Einige Elemente wurden nicht gelöscht, da Sie nicht über die erforderlichen Zugriffsrechte verfügen",

			////	Images
			"picture"=>"Foto",
			"pictureProfil"=>"Profilfoto",
			"wallpaper"=>"Hintergrundbild",
			"keepImg"=>"Bild behalten",
			"changeImg"=>"Bild ändern",
			"pixels"=>"Pixel",

			////	Connexion
			"specifyLoginPassword"=>"Bitte geben Sie einen Benutzernamen und ein Passwort an",
			"specifyLogin"=>"Bitte geben Sie eine E-Mail/einen Benutzernamen (ohne Leerzeichen) an",
			"mailLloginNotif"=>"Es wird empfohlen, eine E-Mail als Anmelde-ID zu verwenden",
			"mailLlogin"=>"E-Mail / Anmelde-ID",
			"connect"=>"Verbindung",
			"connectAuto"=>"Verbunden bleiben",
			"connectAutoTooltip"=>"Meine Anmeldedaten für automatische Verbindung speichern",
			"gIdentityUserUnknown"=>"ist nicht auf dem Space registriert",
			"connectSpaceSwitch"=>"Verbinde mich mit einem anderen Space",
			"guestAccess"=>"Gast-Login",
			"guestAccessTooltip"=>"Melden Sie sich in diesem Bereich als Gast an",
			"publicSpacePasswordError"=>"Falsches Passwort",
			"disconnectSpace"=>"Trennen Sie mich vom Projektraum",
			"disconnectSpaceConfirm"=>"Mich vom Space trennen?",

			////	Password : connexion d'user / edition d'user / reset du password
			"password"=>"Passwort",
			"passwordModify"=>"Passwort ändern",
			"passwordToModify"=>"Temporäres Passwort (wird auf der Anmeldeseite geändert)",
			"passwordToModify2"=>"Passwort (muss bei Bedarf in Ihrem Benutzerprofil geändert werden)",
			"passwordVerif"=>"Passwort bestätigen",
			"passwordTooltip"=>"Bitte füllen Sie die Felder nur aus, wenn Sie Ihr Passwort ändern möchten",
			"passwordInvalid"=>"Ihr Passwort muss Zahlen, Buchstaben und mindestens 6 Zeichen enthalten",
			"passwordVerifError"=>"Ihre Passwortbestätigung ist ungültig",
			"specifyPassword"=>"Bitte geben Sie ein Passwort an",
			"resetPassword"=>"Passwort vergessen?",
			"resetPassword2"=>"Geben Sie Ihre E-Mail-Adresse ein, um Ihr Anmeldekennwort zurückzusetzen",
			"resetPasswordNotif"=>"Ihnen wurde gerade eine E-Mail zum Zurücksetzen Ihres Passworts zugesandt. Sollten Sie diese nicht erhalten haben, überprüfen Sie bitte, ob Ihre E-Mail-Adresse korrekt eingegeben wurde.",
			"resetPasswordMailTitle"=>"Passwort zurücksetzen",
			"resetPasswordMailPassword"=>"Um Ihr Passwort zurückzusetzen und sich erneut anzumelden",
			"resetPasswordMailPassword2"=>"bitte hier klicken",
			"resetPasswordMailLoginRemind"=>"Anmelde-ID erinnern",
			"resetPasswordIdExpired"=>"Der Link zur Neugenerierung des Passworts ist abgelaufen. Bitte versuchen Sie den Vorgang erneut",

			////	Type d'affichage
			"displayMode"=>"Anzeige",
			"displayMode_line"=>"Zeilen",
			"displayMode_block"=>"Blöcke",

			////	Sélectionner / Déselectionner tous les éléments
			"select"=>"Auswählen",
			"selectUnselect"=>"Auswählen / Abwählen",
			"selectAll"=>"Alles auswählen",
			"selectNone"=>"Alle abwählen",
			"selectSwitch"=>"Auswahl umkehren",
			"deleteElems"=>"Auswahl löschen",
			"changeFolder"=>"In einen anderen Ordner verschieben",
			"showOnMap"=>"Kontakte auf einer Karte anzeigen",
			"showOnMapTooltip"=>"Kontakte mit Adresse, Postleitzahl und Ort auf einer Karte anzeigen",
			"notifSelectUser"=>"Bitte wählen Sie mindestens einen Benutzer aus",
			"notifSelectUsers"=>"Bitte wählen Sie mindestens 2 Benutzer aus",
			"selectSpace"=>"Bitte wählen Sie mindestens ein Leerzeichen aus",
			"visibleAllSpaces"=>"Auf allen Spaces verfügbar",
			"visibleOnSpace"=>"Verfügbar im Space",

			////	Temps ("de 11h à 12h", "le 25-01-2007 à 10h30", etc.)
			"from"=>"von",
			"at"=>"à",
			"begin"=>"Anfang",
			"end"=>"Ende",
			"beginEnd"=>"Anfang / Ende",
			"days"=>"Tage",
			"day_1"=>"Montag",
			"day_2"=>"Dienstag",
			"day_3"=>"Mittwoch",
			"day_4"=>"Donnerstag",
			"day_5"=>"Freitag",
			"day_6"=>"Samstag",
			"day_7"=>"Sonntag",
			"month_1"=>"Januar",
			"month_2"=>"Februar",
			"month_3"=>"März",
			"month_4"=>"April",
			"month_5"=>"Mai",
			"month_6"=>"Juni",
			"month_7"=>"Juli",
			"month_8"=>"August",
			"month_9"=>"September",
			"month_10"=>"Oktober",
			"month_11"=>"November",
			"month_12"=>"Dezember",
			"today"=>"heute",
			"displayToday"=>"Heute anzeigen",
			"beginEndError"=>"Enddatum darf nicht vor Startdatum liegen",
			"dateFormatError"=>"Das Datum muss im Format TT/MM/JJJJ vorliegen",
			"timeFormatError"=>"Die Zeit muss im Format HH:mm angegeben werden",

			////	Menus d'édition des objets et editeur tinyMce
			"title"=>"Titel",
			"name"=>"Name",
			"description"=>"Beschreibung",
			"specifyName"=>"Bitte geben Sie einen Namen an",
			"editorDraft"=>"Meinen Text wiederherstellen",
			"editorDraftConfirm"=>"Den letzten im Editor eingegebenen Text abrufen",
			"editorFileInsert"=>"Bild oder Video hinzufügen",
			"editorFileInsertNotif"=>"Bitte wählen Sie ein Bild im JPG-, PNG-, GIF-Format oder ein Video im MP4- oder WebM-Format",
			
			////	Validation des formulaires
			"add"=>"Hinzufügen",
			"modify"=>"Ändern",
			"record"=>"Speichern",
			"modifyAndAccesRight"=>"Element und seine Zugriffsrechte ändern",
			"validate"=>"Validieren",
			"send"=>"Senden",
			"sendTo"=>"Senden an",

			////	Tri d'affichage. Tous les éléments (dossier, tâche, lien, etc...) ont par défaut une date, un auteur & une description
			"sortBy"=>"Sortiert nach",
			"sortBy2"=>"Sortieren nach",
			"SORT_dateCrea"=>"Erstellungsdatum",
			"SORT_dateModif"=>"Änderungsdatum",
			"SORT_title"=>"Titel",
			"SORT_description"=>"Beschreibung",
			"SORT__idUser"=>"Autor",
			"SORT_extension"=>"Dateityp",
			"SORT_octetSize"=>"Größe",
			"SORT_downloadsNb"=>"Anzahl der Downloads",
			"SORT_civility"=>"Höflichkeit",
			"SORT_name"=>"Name",
			"SORT_firstName"=>"Vorname",
			"SORT_adress"=>"Adresse",
			"SORT_postalCode"=>"Postleitzahl",
			"SORT_city"=>"Stadt",
			"SORT_country"=>"Land",
			"SORT_function"=>"Funktion",
			"SORT_companyOrganization"=>"Firma / Organisation",
			"SORT_lastConnection"=>"letzte Verbindung",
			"SORT_ascend"=>"Aufsteigend",
			"SORT_descend"=>"Absteigend",

			////	Visibilité d'un Objet
			"guest"=>"eingeladen",
			"createdBy"=>"Erstellt von",
			"modifBy"=>"Geändert von",
			"objHistory"=>"Elementverlauf",
			"all"=>"alle",
			"deletedUser"=>"Benutzerkonto gelöscht",
			"folderContent"=>"Inhalt",
			"accessRead"=>"Lesen",
			"accessReadTooltip"=>"Lesezugriff",
			"accessWriteLimit"=>"Eingeschränktes Schreiben",
			"accessWriteLimitTooltip"=>"Eingeschränkter Schreibzugriff: jeder Benutzer kann nur die -OBJCONTENT-s ändern oder löschen, die er in diesem --OBJLABEL-- erstellt hat.",
			"accessWrite"=>"Schreiben",
			"accessWriteTooltip"=>"Schreibzugriff",
			"accessWriteTooltipContainer"=>"Schreibzugriff: Möglichkeit zum Ändern oder Löschen aller -OBJCONTENT-s von --OBJLABEL--",
			"accessAutorPrivilege"=>"Nur der Autor und Administratoren können dieses --OBJLABEL-- ändern oder löschen",
			"accessRightsInherited"=>"Vom übergeordneten Element --OBJLABEL-- geerbte Zugriffsrechte",
			"categoryNotifSpaceAccess"=>"ist nur über den Bereich zugänglich",
			"categoryNotifChangeOrder"=>"Die Anzeigereihenfolge wurde geändert",

			////	Libellé des objets (cf. "MdlObject::objectType")
			"OBJECTcontainer"=>"Container",
			"OBJECTelement"=>"Element",
			"OBJECTfolder"=>"Ordner",
			"OBJECTdashboardNews"=>"Neuigkeiten",
			"OBJECTdashboardPoll"=>"Umfrage",
			"OBJECTfile"=>"Datei",
			"OBJECTfileFolder"=>"Ordner",
			"OBJECTcalendar"=>"Tagesordnung",
			"OBJECTcalendarEvent"=>"Ereignis",
			"OBJECTforumSubject"=>"Betreff",
			"OBJECTforumMessage"=>"Nachricht",
			"OBJECTcontact"=>"Kontakt",
			"OBJECTcontactFolder"=>"Ordner",
			"OBJECTlink"=>"Favorit",
			"OBJECTlinkFolder"=>"Ordner",
			"OBJECTtask"=>"Aufgabe",
			"OBJECTtaskFolder"=>"Ordner",
			"OBJECTuser"=>"Benutzer",

			////	Envoi d'un email
			"MAIL_sendOk"=>"Die E-Mail wurde erfolgreich versendet",
			"MAIL_sendNotOk"=>"Die E-Mail konnte nicht versendet werden",
			"MAIL_recipients"=>"Empfänger",
			"MAIL_hello"=>"Hallo",
			"MAIL_hideRecipients"=>"Empfänger ausblenden",
			"MAIL_hideRecipientsTooltip"=>"Alle Empfänger ausblenden",
			"MAIL_addReplyTo"=>"Meine E-Mail als Antwort hinzufügen",
			"MAIL_addReplyToTooltip"=>"Fügen Sie meine E-Mail im Feld ''Antworten an'' hinzu <br><span style='font-size:1.5em'>&#9888;</span> Beachten Sie, dass Ihre E-Mail mit dieser Option im Spam-Ordner einiger Messaging-Dienste landen kann.",
			"MAIL_noFooter"=>"Nachricht nicht signieren",
			"MAIL_noFooterTooltip"=>"Am Ende der Nachricht keine Unterschrift leisten: Name des Absenders und Link zum Bereich",
			"MAIL_receptionNotif"=>"Empfangsbestätigung",
			"MAIL_receptionNotifTooltip"=>"Beim Öffnen der E-Mail eine Empfangsbestätigung anfordern <br>Beachten Sie, dass einige E-Mail-Clients diese Funktion nicht unterstützen",
			"MAIL_specificMails"=>"E-Mail-Adressen hinzufügen",
			"MAIL_specificMailsTooltip"=>"E-Mail-Adressen hinzufügen, die nicht im Feld aufgeführt sind",
			"MAIL_maxFileSizeConfirm"=>"Die Anzahl der angehängten Dateien überschreitet das Empfangslimit einiger Postfächer (--MAXFILESSIZE--)<br><br>Trotzdem senden?",
			"MAIL_maxFileSizeNotif"=>"Die folgende Datei wurde der E-Mail nicht hinzugefügt, da sie zu groß ist",
			"MAIL_sendMail"=>"E-Mail senden",
			"MAIL_sendBy"=>"Gesendet von",
			"MAIL_sendNotif"=>"Die Benachrichtigungs-E-Mail wurde erfolgreich versendet",
			"MAIL_fromTheSpace"=>"aus dem Projektraum",
			"MAIL_elemCreatedBy"=>"--OBJLABEL-- erstellt von",
			"MAIL_elemModifiedBy"=>"--OBJLABEL-- geändert von",
			"MAIL_elemAccessLink"=>"Klicken Sie hier, um in Ihrem Bereich darauf zuzugreifen",

			////	Dossier & fichier
			"gigaOctet"=>"GB",
			"megaOctet"=>"MB",
			"kiloOctet"=>"KB",
			"rootFolder"=>"Hauptordner",
			"rootFolderTooltip"=>"Um die Zugriffsrechte des Hauptordners zu ändern, gehen Sie in das Menü ''Speicherplatz konfigurieren''",
			"addFolder"=>"Ordner hinzufügen",
			"download"=>"Datei herunterladen",
			"downloadFolder"=>"Download-Ordner",
			"diskSpaceUsed"=>"Benutzter Speicherplatz",
			"diskSpaceUsedModFile"=>"Vom Dateimodul verwendeter Speicherplatz",
			"downloadAlert"=>"Ihr Archiv ist zu groß, um es tagsüber herunterzuladen (--ARCHIVE_SIZE--). Bitte starten Sie den Download nach",
			"downloadBackToApp"=>"Zurück zur Anwendung",

			////	Infos sur une personne
			"civility"=>"Anstand",
			"name"=>"Name",
			"firstName"=>"Vorname",
			"adress"=>"Adresse",
			"postalCode"=>"Postleitzahl",
			"city"=>"Stadt",
			"country"=>"Land",
			"telephone"=>"Telefon",
			"telmobile"=>"Mobiltelefon",
			"mail"=>"E-Mail",
			"function"=>"Funktion",
			"companyOrganization"=>"Organisation / Firma",
			"lastConnection"=>"Letzte verbindung",
			"notConnected"=>"Noch nicht verbunden",
			"connectedToday"=>"Heute verbunden",
			"connectedThe"=>"Verbunden mit",
			"displayProfil"=>"Profil anzeigen",
			
			////	Captcha
			"captcha"=>"Kopieren Sie die 5 Zeichen",
			"captchaTooltip"=>"Bitte kopieren Sie die 5 Zeichen zu Ihrer Identifikation",
			"captchaError"=>"Die visuelle Identifizierung ist falsch: 5 Zeichen des Captchas",

			////	Rechercher
			"searchSpecifyText"=>"Bitte geben Sie mindestens 3 Zeichen ein (alphanumerisch und ohne Sonderzeichen)",
			"search"=>"Suchen",
			"searchOnSpace"=>"Suche im Projektraum",
			"searchDateCrea"=>"Erstellungsdatum",
			"searchDateCreaDay"=>"weniger als ein Tag",
			"searchDateCreaWeek"=>"weniger als eine Woche",
			"searchDateCreaMonth"=>"weniger als ein Monat",
			"searchDateCreaYear"=>"weniger als ein Jahr",
			"advancedSearch"=>"Erweiterte Suche",
			"advancedSearchAnyWord"=>"beliebiges Wort",
			"advancedSearchAllWords"=>"alle Wörter",
			"advancedSearchExactPhrase"=>"die genaue Phrase",
			"keywords"=>"Schlüsselwörter",
			"listModules"=>"Module",
			"listFields"=>"Felder",
			"listFieldsElems"=>"Betroffene Elemente",
			"noResults"=>"Keine Ergebnisse",

			////	Inscription d'utilisateur
			"userInscription"=>"Für diesen Bereich registrieren",
			"userInscriptionTooltip"=>"Senden Sie eine Registrierungsanfrage, um ein Benutzerkonto zu erhalten.<br>Nach der Bestätigung durch einen Administrator wird Ihnen eine Bestätigung per E-Mail zugesandt.",
			"userInscriptionSpace"=>"Im Space registrieren",
			"userInscriptionRecorded"=>"Ihre Registrierung wurde registriert: Sie wird so bald wie möglich vom Space-Administrator bestätigt",
			"userInscriptionEmailSubject"=>"Neue Registrierung im Space",
			"userInscriptionEmailMessage"=>"Eine neue Registrierung wurde von <i>--NEW_USER_LABEL--</i> für den Bereich <i>--SPACE_NAME--</i> angefordert: <br><br><i>--NEW_USER_MESSAGE--<i> <br><br>Denken Sie daran, diese Registrierung bei der nächsten Anmeldung zu bestätigen oder abzubrechen.",
			"userInscriptionEdit"=>"Registrierungsformular auf der Login-Seite",
			"userInscriptionEditTooltip"=>"Besucher können eine Registrierung im Space beantragen, um ein Benutzerkonto zu haben: Die Anfrage wird dann vom Space-Administrator bestätigt",
			"userInscriptionNotif"=>"Benachrichtige mich per E-Mail, wenn ich mich registriere",
			"userInscriptionNotifTooltip"=>"Nach jeder Registrierung eine E-Mail-Benachrichtigung an die Space-Administratoren senden",
			"userInscriptionValidate"=>"Registrierungsanfragen validieren",
			"userInscriptionValidateTooltip"=>"Anfragen zur Platzregistrierung validieren",
			"userInscriptionSelectValidate"=>"Ausgewählte Registrierungen validieren",
			"userInscriptionSelectInvalidate"=>"Ausgewählte Registrierungen ungültig machen",
			"userInscriptionInvalidateMail"=>"Leider wurde Ihre Registrierung am nicht bestätigt",

			////	Importer ou Exporter : Contact OU Utilisateurs
			"importExport_user"=>"Benutzer importieren / exportieren",
			"import_user"=>"Benutzer in den aktuellen Bereich importieren",
			"export_user"=>"Benutzer aus dem aktuellen Bereich exportieren",
			"importExport_contact"=>"Kontakte importieren / exportieren",
			"import_contact"=>"Kontakte in den aktuellen Ordner importieren",
			"export_contact"=>"Kontakte aus dem aktuellen Ordner exportieren",
			"exportFormat"=>"im Format",
			"specifyFile"=>"Bitte geben Sie eine Datei an",
			"fileExtension"=>"Der Dateityp ist ungültig. Er muss vom Typ sein",
			"importContactRootFolder"=>"In den Hauptordner importierte Kontakte werden standardmäßig ''allen Benutzern im Bereich'' zugewiesen",
			"importInfo"=>"Wählen Sie die Agora-Felder aus, die Sie ansprechen möchten, indem Sie die Dropdown-Listen in jeder Spalte verwenden",
			"importNotif1"=>"Bitte wählen Sie die Spalte 'Name' aus den Dropdown-Listen aus",
			"importNotif2"=>"Bitte wählen Sie mindestens ein Element zum Importieren aus",
			"importNotif3"=>"Das Agora-Feld wurde bereits in einer anderen Spalte ausgewählt (jedes Agora-Feld kann nur einmal ausgewählt werden)",

			////	Messages d'erreur / Notifications
			"NOTIF_identification"=>"Ungültiger Benutzername oder ungültiges Passwort",
			"NOTIF_presentIp"=>"Dieses Benutzerkonto wird derzeit von einem anderen Terminal mit einer anderen IP-Adresse verwendet",
			"NOTIF_noAccessNoSpaceAffected"=>"Ihr Benutzerkonto wurde erfolgreich identifiziert, Sie sind jedoch derzeit keinem Space zugeordnet. Bitte kontaktieren Sie den Administrator, um Ihre Zugriffsrechte zu überprüfen.",
			"NOTIF_noAccess"=>"Ihre Verbindung ist getrennt",
			"NOTIF_fileOrFolderAccess"=>"Datei/Ordner nicht zugänglich",
			"NOTIF_diskSpace"=>"Es ist nicht genügend Speicherplatz zum Speichern Ihrer Dateien vorhanden. Sie können keine Datei hinzufügen",
			"NOTIF_fileVersion"=>"Dateityp unterscheidet sich vom Original",
			"NOTIF_fileVersionForbidden"=>"Dateityp nicht erlaubt",
			"NOTIF_folderMove"=>"Sie können den Ordner nicht in sich selbst verschieben!",
			"NOTIF_duplicateName"=>"Ein Eintrag mit gleichem Namen existiert bereits: <br> Bitte geben Sie einen anderen an",
			"NOTIF_duplicateNameFolder"=>"Ein Ordner mit gleichem Namen existiert bereits: <br> Bitte geben Sie einen anderen an",
			"NOTIF_fileName"=>"Eine Datei mit gleichem Namen existiert bereits.<br>Der Name ist jedoch erhalten geblieben.",
			"NOTIF_chmodDATAS"=>"Der Ordner /DATAS/ ist nicht beschreibbar (führen Sie ggf. ''chmod 770'' aus)",
			"NOTIF_usersNb"=>"Sie können kein neues Benutzerkonto erstellen: Anzahl begrenzt auf ",

			////	Header
			"HEADER_displaySpace"=>"Arbeitsbereiche",
			"HEADER_displayAdmin"=>"Administratoranzeige",
			"HEADER_displayAdminInfo"=>"Ermöglicht die Anzeige von Elementen des Bereichs, die mir nicht direkt zugewiesen sind: Ordner, Kalender usw.",
			"HEADER_displayAdminEnabled"=>"Anzeigenverwaltung aktiviert",
			"HEADER_displayAdminDisabled"=>"Administratoranzeige deaktiviert",
			"HEADER_documentation"=>"Benutzerhandbuch",
			"HEADER_shortcuts"=>"Verknüpfungen",

			////	Messenger / Visio
			"MESSENGER_MODULE_NAME"=>"Nachrichten",
			"MESSENGER_MODULE_DESCRIPTION"=>"Chatten oder Videokonferenz mit anderen Personen online starten",
			"MESSENGER_messengerMultiUsers"=>"Chatten Sie mit mehreren Personen im Nachrichtensystem (linker Bereich zur Auswahl der Empfänger)",
			"MESSENGER_chatWithMulti"=>"Chatten mit",
			"MESSENGER_chatWith"=>"Chatten oder Videokonferenz starten mit",
			"MESSENGER_messageFrom"=>"Nachricht von",
			"MESSENGER_messageSentTo"=>"Gesendet an",
			"MESSENGER_messageToSelected"=>"Nachricht an ausgewählte Personen",
			"MESSENGER_messageTo"=>"Nachricht an",
			"MESSENGER_addMessageNotif"=>"Bitte geben Sie eine Nachricht an",
			"MESSENGER_visioProposeTo"=>"Videokonferenz vorschlagen an",
			"MESSENGER_visioProposeToSelection"=>"Videokonferenz vorschlagen an ausgewählte Personen Personen",
			"MESSENGER_visioProposeToUsers"=>"Klicken Sie hier, um die Videokonferenz zu starten",
			"MESSENGER_nobody"=>"Derzeit sind keine anderen Benutzer angemeldet",

			////	Lancer une Visio
			"VISIO_urlAdd"=>"Videokonferenz hinzufügen",
			"VISIO_urlAddConfirm"=>"Einen Link zum Starten einer neuen Videokonferenz hinzufügen?",
			"VISIO_urlCopy"=>"Videokonferenz-Link kopieren",
			"VISIO_urlDelete"=>"Videokonferenz-Link löschen",
			"VISIO_launch"=>"Videokonferenz starten",
			"VISIO_launchJitsi"=>"Starten Sie die Videokonferenz <br>mit der Jitsi-Anwendung",
			"VISIO_launchFromEvent"=>"Event-Videokonferenz starten",
			"VISIO_launchTooltip"=>"Denken Sie daran, den Zugriff auf Ihre Webcam und Ihr Mikrofon zuzulassen",
			"VISIO_launchTooltip2"=>"Probleme mit der Kamera oder dem Mikrofon bei Ihrer Videokonferenz? Folgen Sie der Anleitung <img src='app/img/pdf.png'>",
			"VISIO_launchServerTooltip"=>"Wählen Sie den sekundären Server, wenn der primäre Server nicht richtig funktioniert:<br>Wichtig: Ihre Gesprächspartner müssen denselben Server wie Sie auswählen.",
			"VISIO_launchServerMain"=>"Haupt-Visio-Server",
			"VISIO_launchServerAlt"=>"Sekundärer Videoserver",

			////	VueObjMenuEdit.php
			"EDIT_notifNoSelection"=>"Sie müssen mindestens eine Person oder einen Raum auswählen",
			"EDIT_notifNoPersoAccess"=>"Sie sind dem Artikel nicht zugeordnet. Trotzdem validieren?",
			"EDIT_parentFolderAccessError"=>"Überprüfen Sie die Zugriffsrechte des übergeordneten Ordners <br><i>--FOLDER_NAME--</i><br><br> Es muss auch ein Zugriffsrecht für <br><i>--SPACE_LABEL--</i> &nbsp;>&nbsp; <i>--TARGET_LABEL--</i><br><br> vorhanden sein, sonst ist dieser Ordner nicht zugänglich!",
			"EDIT_accessRight"=>"Zugriffsrechte",
			"EDIT_accessRightContent"=>"Zugriffsrechte auf Inhalte",
			"EDIT_spaceNoModule"=>"Das aktuelle Modul wurde diesem Bereich noch nicht hinzugefügt",
			"EDIT_allUsers"=>"Alle Benutzer",
			"EDIT_allUsersTooltip"=>"Zugriffsrechte für alle Benutzer des Bereichs <i>--SPACENAME--</i>",
			"EDIT_allUsersAndGuests"=>"Alle Benutzer und Gäste",
			"EDIT_allUsersAndGuestsTooltip"=>"Zugriffsrechte für alle Benutzer und Gäste des Raums <i>--SPACENAME--</i>.<hr>Gäste haben nur Lesezugriff auf den Raum (Personen ohne Benutzerkonto)",
			"EDIT_adminSpace"=>"Administrator: Vollzugriff auf alle Elemente des Spaces",
			"EDIT_showAllUsers"=>"Alle Benutzer anzeigen",
			"EDIT_showAllUsersAndSpaces"=>"Alle Benutzer und Bereiche anzeigen",
			"EDIT_notifMail"=>"Per E-Mail benachrichtigen",
			"EDIT_notifMail2"=>"E-Mail-Benachrichtigung senden",
			"EDIT_notifMailTooltip"=>"Senden Sie eine E-Mail-Benachrichtigung an die Personen, denen das Element (--OBJLABEL--) zugewiesen ist",
			"EDIT_notifMailTooltipCal"=>"<hr>Wenn Sie den Termin persönlichen Kalendern zuordnen, dann wird die Benachrichtigung nur an die Besitzer dieser Kalender gesendet (Schreibzugriff).",
			"EDIT_notifMailAddFiles"=>"Datei(en) an die Benachrichtigung anhängen",
			"EDIT_notifMailSelect"=>"Benachrichtigungsempfänger auswählen",
			"EDIT_accessRightSubFolders"=>"Unterordnern dieselben Zugriffsrechte geben",
			"EDIT_accessRightSubFoldersTooltip"=>"Zugriffsrechte auf Unterordner erweitern (nur auf solche mit Schreibzugriff)",
			"EDIT_shortcut"=>"Verknüpfung",
			"EDIT_shortcutInfo"=>"Verknüpfung in Menüleiste anzeigen",
			"EDIT_attachedFile"=>"Angehängte Dateien",
			"EDIT_attachedFileAdd"=>"Dateien anhängen",
			"EDIT_attachedFileInsert"=>"In Text einfügen",
			"EDIT_attachedFileInsertTooltip"=>"Bild in Editortext einfügen (.jpeg/.png/.mp4-Format)",
			"EDIT_guestName"=>"Ihr Name / Benutzername",
			"EDIT_guestNameNotif"=>"Bitte geben Sie einen Namen oder Spitznamen an",
			"EDIT_guestMail"=>"Ihre E-Mail",
			"EDIT_guestMailTooltip"=>"Bitte geben Sie Ihre E-Mail-Adresse zur Validierung Ihres Vorschlags an",
			"EDIT_guestElementRegistered"=>"Vielen Dank für Ihren Vorschlag. <br> Er wird kurz vor der Validierung überprüft",

			////	Formulaire d'installation
			"INSTALL_dbConnect"=>"Mit der Datenbank verbinden",
			"INSTALL_dbHost"=>"MariaDB oder MySql Server (Hostname)",
			"INSTALL_dbName"=>"Datenbankname",
			"INSTALL_dbLogin"=>"Benutzername",
			"INSTALL_adminAgora"=>"Hauptadministrator",
			"INSTALL_errorDbNameFormat"=>"Warnung: Der Datenbankname sollte möglichst nur alphanumerische Zeichen, Bindestriche oder Unterstriche enthalten",
			"INSTALL_errorDbConnection"=>"Verbindung zur Datenbank fehlgeschlagen:<br>Bitte überprüfen Sie die Verbindungsdetails",
			"INSTALL_errorDbExist"=>"Anwendung bereits installiert: <a href='index.php'>Klicken Sie hier, um darauf zuzugreifen</a><br><br>Denken Sie daran, die Datenbank zu löschen, um die Installation neu zu starten",
			"INSTALL_errorDbNoSqlFile"=>"Die Installationsdatei db.sql ist nicht erreichbar oder wurde gelöscht, da die Installation bereits durchgeführt wurde",
			"INSTALL_PhpOldVersion"=>"Agora-Project --CURRENT_VERSION-- erfordert eine neuere Version von PHP",
			"INSTALL_confirmInstall"=>"Installation bestätigen?",
			"INSTALL_installOk"=>"Ihr Space wurde erfolgreich installiert",
			// Premiers enregistrements en DB
			"INSTALL_agoraDescription"=>"Freigabe- und gemeinsamer Arbeitsbereich",
			"INSTALL_dataDashboardNews"=>  "<h3>Willkommen in Ihrem neuen Freigabebereich!</h3>
											<h4 onclick=\"redir('?ctrl=file')\"><img src='app/img/file/iconSmall.png'>Teilen Sie Ihre Dateien mit Ihrem Team im Dateimanager</h4>
											<h4 onclick=\"redir('?ctrl=calendar')\"><img src='app/img/calendar/iconSmall.png'> Erstellen Sie Ereignisse in Ihrem freigegebenen Kalender oder persönlichen Kalender</h4>
											<h4 onclick=\"redir('?ctrl=dashboard')\"><img src='app/img/dashboard/iconSmall.png'> Verwenden Sie den Newsfeed, um Informationen über Ihre Aktivitäten zu verbreiten</h4>
											<h4 onclick=\"redir('?ctrl=forum')\"><img src='app/img/messenger.png'>Kommunizieren Sie über Forum, Messaging oder Videokonferenzen</h4>
											<h4 onclick=\"redir('?ctrl=task')\"><img src='app/img/task/iconSmall.png'>Verwalten Sie Ihre Aufgaben und Projekte, um Ihre Aktivitäten zu organisieren</h4>
											<h4 onclick=\"redir('?ctrl=mail')\"><img src='app/img/mail/iconSmall.png'> Senden Sie Newsletter, um Informations-E-Mails über Ihre Aktivitäten zu verteilen.</h4>
											<h4 onclick=\"lightboxOpen('docs/DOCUMENTATION_FR.pdf?displayFile=true')\"><img src='app/img/documentation.png'> Konsultieren Sie das Benutzerhandbuch, um Ihren Bereich zu entdecken</h4>
											<h4 onclick=\"lightboxOpen('?ctrl=user&action=SendInvitation')\"><img src='app/img/mail.png'> Senden Sie E-Mail-Einladungen zum Beitritt zum Space</h4>",
			"INSTALL_dataDashboardPoll"=>"Was halten Sie vom Newsfeed?",
			"INSTALL_dataDashboardPollA"=>"Sehr interessant!",
			"INSTALL_dataDashboardPollB"=>"Interessant",
			"INSTALL_dataDashboardPollC"=>"Nicht interessant",
			"INSTALL_dataCalendarEvt"=>"Willkommen in Ihrem Bereich!",
			"INSTALL_dataForumSubject1"=>"Willkommen im Forum!",
			"INSTALL_dataForumSubject2"=>"Stellen Sie in diesem Forum gerne Ihre Fragen und diskutieren Sie die Themen, die Sie besprechen möchten.",
			"INSTALL_dataTaskStatus1"=>"Zu erledigen",
			"INSTALL_dataTaskStatus2"=>"In Bearbeitung",
			"INSTALL_dataTaskStatus3"=>"Zu validieren",
			"INSTALL_dataTaskStatus4"=>"Abgeschlossen",

			////	MOD : AGORA
			////
			"AGORA_generalSettings"=>"Allgemeine Einstellungen",
			"AGORA_Changelog"=>"Versionsprotokoll",
			"AGORA_phpMailDisabled"=>"PHP Mail Funktion deaktiviert",
			"AGORA_phpLdapDisabled"=>"PHP LDAP Funktion deaktiviert",
			"AGORA_phpGD2Disabled"=> "PHP GD2-Funktion deaktiviert",
			"AGORA_backupFull"=>"Vollständige Sicherung",
			"AGORA_backupFullTooltip"=>"Vollständige Sicherung des Speicherplatzes wiederherstellen: alle Dateien und die Datenbank",
			"AGORA_backupDb"=>"Datenbank sichern",
			"AGORA_backupDbTooltip"=>"Nur das Datenbank-Backup des Speicherplatzes abrufen",
			"AGORA_backupConfirm"=>"Dieser Vorgang kann mehrere Minuten dauern: Download bestätigen?",
			"AGORA_diskSpaceInvalid"=>"Der Speicherplatz für Dateien muss eine Ganzzahl sein",
			"AGORA_visioHostInvalid"=>"Die Adresse des Videokonferenzservers ist ungültig: Sie muss mit 'https' beginnen",
			"AGORA_gApiKeyInvalid"=>"Wenn Sie Google Map als Kartentool wählen, müssen Sie dort einen 'API-Schlüssel' angeben",
			"AGORA_gIdentityKeyInvalid"=>"Wenn Sie die optionale Anmeldung über Google wählen, müssen Sie dort einen 'API Key' für Google SignIn angeben",
			"AGORA_confirmModif"=>"Änderungen bestätigen?",
			"AGORA_name"=>"Name des Hauptraums",
			"AGORA_nameTooltip"=>"Name, der auf der Anmeldeseite, in E-Mails usw. angezeigt wird.",
			"AGORA_description"=>"Beschreibung auf der Login-Seite",
			"AGORA_footerHtml"=>"Text unten links auf jeder Seite",
			"AGORA_logo"=>"Logo unten rechts auf jeder Seite",
			"AGORA_logoUrl"=>"URL",
			"AGORA_logoConnect"=>"Logo auf der Anmeldeseite",
			"AGORA_logoConnectTooltip"=>"Logo, das oben im Anmeldeformular angezeigt wird",
			"AGORA_lang"=>"Standardsprache",
			"AGORA_timezone"=>"Zeitzone",
			"AGORA_diskSpaceLimit"=>"Speicherplatz für Dateien",
			"AGORA_logsTimeOut"=>"Ereignisverlauf speichern",
			"AGORA_logsTimeOutTooltip"=>"Die Aufbewahrungsfrist des Ereignisverlaufs betrifft das Hinzufügen oder Ändern von Elementen. Löschprotokolle werden mindestens 1 Jahr lang aufbewahrt.",
			"AGORA_visioHost"=>"Jitsi-Videokonferenzserver",
			"AGORA_visioHostTooltip"=>"Url des Haupt-Videokonferenzservers. Beispiel: https://framatalk.org oder https://meet.jit.si",
			"AGORA_visioHostAlt"=>"Alternativer Videokonferenzserver",
			"AGORA_visioHostAltTooltip"=>"Url des alternativen Videokonferenzservers: falls der Haupt-Jitsi-Server nicht verfügbar ist",
			"AGORA_skin"=>"Oberflächenfarbe",
			"AGORA_black"=>"Dunkle Anzeige",
			"AGORA_white"=>"Lichtanzeige",
			"AGORA_userMailDisplay"=>"E-Mail-Adressen der Benutzer für alle sichtbar",
			"AGORA_userMailDisplayTooltip"=>"E-Mail im Profil des Nutzers, in E-Mail-Benachrichtigungen usw. anzeigen/ausblenden.<br>Hinweis: Der Hauptadministrator kann weiterhin die E-Mails jedes Benutzers anzeigen",
			"AGORA_moduleLabelDisplay"=>"Name der Module in der Menüleiste",
			"AGORA_folderDisplayMode"=>"Standard-Ordneranzeige",
			"AGORA_wallpaperLogoError"=>"Hintergrundbild und Logo müssen im .jpg- oder .png-Format vorliegen",
			"AGORA_deleteWallpaper"=>"Hintergrundbild löschen",
			"AGORA_usersCommentLabel"=>"''Kommentieren''-Schaltfläche bei Elementen",
			"AGORA_usersComment"=>"Kommentar",
			"AGORA_usersComments"=>"Kommentare",
			"AGORA_usersLikeLabel"=>"''Gefällt mir''-Button bei Artikeln",
			"AGORA_usersLike"=>"Gefällt mir!",
			"AGORA_mapTool"=>"Kartierungswerkzeug",
			"AGORA_mapToolTooltip"=>"Mapping-Tool zum Anzeigen von Benutzern und Kontakten auf einer Karte",
			"AGORA_gApiKey"=>"Google API-Schlüssel für Maps",
			"AGORA_gApiKeyTooltip"=>"Obligatorische Einstellung für Google Maps:<br> https://developers.google.com/maps/documentation/javascript/get-api-key",
			"AGORA_gIdentity"=>"Anmeldung über ein Google Gmail-Konto",
			"AGORA_gIdentityTooltip"=>"Benutzer mit einem Identifikator mit einer <i>@gmail.com</i>-Adresse können sich auch über ihr Google-Konto anmelden",
			"AGORA_gIdentityClientId"=>"API-Schlüssel für die Anmeldung über Google",
			"AGORA_gIdentityClientIdTooltip"=>"Obligatorische Einstellung für die Verbindung über ein Google-Konto:<br> https://developers.google.com/identity/protocols/oauth2",
			"AGORA_messengerDisplay"=>"Nachrichten",
			"AGORA_personsSort"=>"Benutzer und Kontakte sortieren nach",
			//SMTP
			"AGORA_smtpLabel"=>"SMTP & sendMail Verbindung",
			"AGORA_sendmailFrom"=>"E-Mail 'Von'",
			"AGORA_sendmailFromPlaceholder"=>"Beispiel: 'noreply@mydomain.com'",
			"AGORA_smtpHost"=>"SMTP-Serveradresse (Hostname)",
			"AGORA_smtpPort"=>"Port auf dem Server",
			"AGORA_smtpPortTooltip"=>"'25' als Standard. '587' oder '465' für SSL/TLS-Verbindung",
			"AGORA_smtpSecure"=>"Verschlüsselter Verbindungstyp (optional)",
			"AGORA_smtpSecureTooltip"=>"'ssl' oder 'tls'",
			"AGORA_smtpUsername"=>"Benutzername",
			"AGORA_smtpPass"=>"Passwort",
			//LDAP
			"AGORA_ldapLabel"=>"Verbindung zu einem LDAP-Server",
			"AGORA_ldapLabelTooltip"=>"Verbindung zu einem LDAP-Server zum Erstellen von Benutzern in Ihrem Bereich: siehe die Option ''Benutzerimport/-export'' des Moduls ''Benutzer''",
			"AGORA_ldapUri"=>"LDAP-URI",
			"AGORA_ldapUriTooltip"=>"Vollständige LDAP-URI in der Form LDAP://hostname:port oder LDAPS://hostname:port für SSL-Verschlüsselung.",
			"AGORA_ldapPort"=>"Server-Port",
			"AGORA_ldapPortTooltip"=>"Der für die Verbindung verwendete Port: standardmäßig ''389''",
			"AGORA_ldapLogin"=>"LDAP-Administrator-DN (Distinguished Name)",
			"AGORA_ldapLoginTooltip"=>"zum Beispiel ''cn=admin,dc=my-company,dc=com''",
			"AGORA_ldapPass"=>"LDAP-Administratorkennwort",
			"AGORA_ldapDn"=>"Benutzergruppen-DN (Distinguished Name)",
			"AGORA_ldapDnTooltip"=>"Benutzergruppen-DN: Standort der Benutzer im Verzeichnis. Beispiel ''ou=my-group,dc=my-company,dc=com''",
			"importLdapFilterTooltip"=>"LDAP-Suchfilter (siehe https://www.php.net/manual/function.ldap-search.php). Beispiel ''(cn=*)'' oder ''(&(samaccountname=MONLOGIN)(cn=*))''",
			"AGORA_ldapConnectError"=>"Fehler beim Verbinden mit dem LDAP-Server!",

			////	MOD : LOG
			////
			"LOG_MODULE_DESCRIPTION"=>"Ereignisverlauf",
			"LOG_path"=>"Pfad",
			"LOG_filter"=>"Filter",
			"LOG_date"=>"Datum/Uhrzeit",
			"LOG_spaceName"=>"Bereich",
			"LOG_moduleName"=>"Modul",
			"LOG_objectType"=>"Objekttyp",
			"LOG_action"=>"Aktion",
			"LOG_userName"=>"Benutzer",
			"LOG_ip"=>"IP",
			"LOG_comment"=>"Kommentar",
			"LOG_noLogs"=>"Keine Protokolle",
			"LOG_filterSince"=>"gefiltert von",
			"LOG_search"=>"Suchen",
			"LOG_connexion"=>"verbindung",
			"LOG_add"=>"hinzufügen",
			"LOG_delete"=>"löschung",
			"LOG_modif"=>"änderung",

			////	MOD : SPACE
			////
			"SPACE_moduleTooltip"=>"Der Hauptbereich kann in mehrere Arbeitsbereiche (auch ''Unterbereiche'' genannt) unterteilt werden",
			"SPACE_manageAllSpaces"=>"Alle Arbeitsbereiche verwalten",
			"SPACE_config"=>"Arbeitsbereich verwalten",
			"SPACE_space"=>"Leerzeichen",
			"SPACE_spaces"=>"Leerzeichen",
			"SPACE_accessRightUndefined"=>"Muss noch definiert werden!",
			"SPACE_modules"=>"Module",
			"SPACE_addSpace"=>"Neuer Bereich",
			//Edit
			"SPACE_userAdminAccess"=>"Space-Benutzer und -Administratoren",
			"SPACE_selectModule"=>"Sie müssen mindestens ein Modul auswählen",
			"SPACE_spaceModules"=>"Raummodule",
			"SPACE_publicSpace"=>"Öffentlicher Bereich: Gastzugang",
			"SPACE_publicSpaceTooltip"=>"Ein öffentlicher Bereich ist für Personen ohne Benutzerkonto (Gäste) zugänglich. Diese können dann von der Startseite aus auf den Bereich zugreifen. Sie können ein Passwort festlegen, um den Zugriff auf diesen öffentlichen Bereich zu schützen. Die Module 'E-Mail' und 'Benutzer' sind für Gäste nicht verfügbar.",
			"SPACE_publicSpaceNotif"=>"Wenn Ihr öffentlicher Bereich personenbezogene Daten (Telefon, Adresse usw.) enthält, denken Sie daran, ein Passwort festzulegen, um die DSGVO einzuhalten: Datenschutz-Grundverordnung",
			"SPACE_usersInvitation"=>"Benutzer können Einladungen per E-Mail versenden",
			"SPACE_usersInvitationTooltip"=>"Alle Benutzer können E-Mail-Einladungen zum Beitritt zum Space senden",
			"SPACE_allUsers"=>"Alle Benutzer",
			"SPACE_user"=>"Benutzer",
			"SPACE_userTooltip"=>"Normaler Zugriff auf den Projektraum",
			"SPACE_admin"=>"Administrator",
			"SPACE_adminTooltip"=>"Der Administrator kann alle im Space vorhandenen Elemente bearbeiten/löschen.<br>Er kann den Space außerdem konfigurieren, neue Benutzer oder Benutzergruppen erstellen, Einladungen per E-Mail versenden usw.",

			////	MOD : USER
			////
			"USER_MODULE_NAME"=>"Benutzer",
			"USER_MODULE_DESCRIPTION"=>"Space-Benutzer",
			"USER_OPTION_allUsersAddGroup"=>"Alle Benutzer können Gruppen erstellen",
			"USER_spaceOrAllUsersTooltip"=>"Benutzer des aktuellen Bereichs / Benutzer aller Bereiche (Administratoransicht)",
			"USER_spaceUsers"=>"Space-Benutzer verwalten",
			"USER_allUsers"=>"Alle Benutzer verwalten",
			"USER_deleteDefinitely"=>"Dauerhaft löschen",
			"USER_deleteFromCurSpace"=>"Aus dem aktuellen Speicherplatz löschen/freigeben",
			"USER_deleteFromCurSpaceConfirm"=>"Benutzer aus aktuellem Bereich löschen/aufheben?",
			"USER_user"=>"Benutzer",
			"USER_users"=>"Benutzer",
			"USER_addExistUser"=>"Vorhandenen Benutzer hinzufügen",
			"USER_addExistUserTitle"=>"Einen bestehenden Benutzer zum aktuellen Bereich hinzufügen (dem aktuellen Bereich zuweisen)",
			"USER_addUser"=>"Neuer Benutzer",
			"USER_addUserSite"=>"Benutzer anlegen: standardmäßig keinem Leerzeichen zugewiesen!",
			"USER_addUserSpace"=>"Benutzer für den aktuellen Bereich erstellen",
			"USER_sendCoords"=>"Anmeldeinformationen senden",
			"USER_sendCoordsTooltip"=>"Senden Sie mehreren Benutzern eine E-Mail mit ihrer Anmelde-ID und einem Link zum Initialisieren ihres Passworts",
			"USER_sendCoordsTooltip2"=>"Senden Sie jedem neuen Benutzer eine E-Mail mit seinen Anmeldedaten.",
			"USER_sendCoordsConfirm"=>"Senden bestätigen?",
			"USER_sendCoordsMail"=>"Ihre Zugangsdaten für Ihren Bereich",
			"USER_noUser"=>"Zurzeit ist diesem Bereich kein Benutzer zugewiesen",
			"USER_spaceList"=>"Benutzerbereiche",
			"USER_spaceNoAffection"=>"kein Leerzeichen",
			"USER_adminGeneral"=>"Hauptadministrator",
			"USER_adminGeneralTooltip"=>"Warnung: Der Hauptadministrator kann alle Elemente des Bereichs (Ordner, Dateien, Kalender usw.) sowie alle Benutzer und Bereiche bearbeiten/löschen!<br>Es ist daher ratsam, dieses Privileg maximal 2 oder 3 Personen zuzuweisen.<br><br>Für eingeschränktere Privilegien wählen Sie das Recht „Administrator“ (unten).",
			"USER_adminSpace"=>"Bereichsadministrator",
			"USER_userSpace"=>"Benutzerbereich",
			"USER_profilEdit"=>"Benutzerprofil bearbeiten",
			"USER_myProfilEdit"=>"Mein Profil bearbeiten",
			// Invitations
			"USER_sendInvitation"=>"Einladungen versenden",
			"USER_sendInvitationTooltip"=>"Einladungs-E-Mails zum Beitritt zum aktuellen Space versenden:<br> Sobald eine Einladung bestätigt ist, wird automatisch ein Benutzerkonto für die betreffende Person angelegt.",
			"USER_mailInvitationObject"=>"Einladung von",
			"USER_mailInvitationFromSpace"=>"lädt Sie in den Space ein",
			"USER_mailInvitationConfirm"=>"Klicken Sie hier, um die Einladung zu bestätigen",
			"USER_mailInvitationWait"=>"Einladung(en) warten auf Bestätigung",
			"USER_exired_idInvitation"=>"Ihr Einladungslink ist abgelaufen...",
			"USER_invitPassword"=>"Bestätigen Sie Ihre Einladung",
			"USER_invitPassword2"=>"Wählen Sie Ihr Passwort und bestätigen Sie dann Ihre Einladung",
			"USER_invitationValidated"=>"Ihre Einladung wurde validiert!",
			"USER_gPeopleImport"=>"Meine Google-/Gmail-Kontakte importieren",
			"USER_quotaExceeded"=>"Benutzerkontingent erreicht. Bitte kontaktieren Sie den Space-Administrator.",
			"USER_importQuotaExceeded"=>"Sie sind auf --USERS_QUOTA_REMAINING-- neue Benutzerkonten beschränkt, von insgesamt --LIMITE_NB_USERS-- Benutzern",
			// groupes
			"USER_spaceGroups"=>"Benutzergruppen",
			"USER_spaceGroupsEdit"=>"Space-Benutzergruppen bearbeiten",
			"USER_groupEditInfo"=>"Liste der Gruppen, die ich bearbeiten kann: Gruppenautor oder Space-Administrator",
			"USER_addGroup"=>"Neue Gruppe",
			"USER_userGroups"=>"Benutzergruppen",
			// Utilisateur_affecter
			"USER_searchPrecision"=>"Bitte geben Sie einen Namen, Vornamen oder eine E-Mail-Adresse an",
			"USER_userAffectConfirm"=>"Zuweisungen bestätigen?",
			"USER_userSearch"=>"Nach Benutzern suchen, die dem Bereich hinzugefügt werden sollen",
			"USER_allUsersOnSpace"=>"Alle Benutzer werden dem aktuellen Space zugewiesen",
			"USER_usersSpaceAffection"=>"Benutzer dem Space zuweisen:",
			"USER_usersSearchNoResult"=>"Keine Benutzer für diese Suche",
			"USER_usersSearchBack"=>"Zurück",
			// Utilisateur_edit & CO
			"USER_langs"=>"Sprache",
			"USER_persoCalendarDisabled"=>"Persönlicher Kalender deaktiviert",
			"USER_persoCalendarDisabledTooltip"=>"Aktivieren Sie diese Option, um den persönlichen Kalender des Benutzers zu deaktivieren.<br><br> Hinweis: Jedem Benutzer wird standardmäßig ein persönlicher Kalender zugewiesen. Dieser bleibt immer zugänglich, unabhängig vom angezeigten Bereich.",
			"USER_connectionSpace"=>"Bei Verbindung angezeigter Speicherplatz",
			"USER_loginExists"=>"Der Benutzername/die E-Mail-Adresse existiert bereits. Bitte geben Sie einen anderen an",
			"USER_mailPresentInAccount"=>"ein Benutzerkonto mit dieser E-Mail-Adresse existiert bereits",
			"USER_loginAndMailDifferent"=>"Beide E-Mail-Adressen müssen identisch sein",
			"USER_mailNotifObject"=>"Willkommen bei ",
			"USER_mailNotifContent"=>"Ihr Benutzerkonto wurde gerade erstellt am",
			"USER_mailNotifContent2"=>"Melden Sie sich hier mit folgenden Angaben an",
			"USER_mailNotifContent3"=>"Denken Sie daran, diese E-Mail in Ihrem Archiv zu behalten",
			// Edition du Livecounter/Messenger
			"USER_livecounterVisibility"=>"Sichtbarkeit bei Nachrichten",
			"USER_livecounterAllUsers"=>"Meine Anwesenheit anzeigen, wenn ich angemeldet bin",
			"USER_livecounterDisabled"=>"Meine Anwesenheit immer verbergen",
			"USER_livecounterSomeUsers"=>"Einigen Benutzern meine Anwesenheit anzeigen",

			////	MOD : DASHBOARD
			////
			"DASHBOARD_MODULE_NAME"=>"Neuigkeiten",
			"DASHBOARD_MODULE_DESCRIPTION"=>"Neuigkeiten, Umfragen und neue Elemente",
			"DASHBOARD_OPTION_adminAddNews"=>"Nur Administratoren können Nachrichten erstellen",
			"DASHBOARD_OPTION_disablePolls"=>"Umfragen deaktivieren",
			"DASHBOARD_OPTION_adminAddPoll"=>"Nur Administratoren können Umfragen erstellen",
			"DASHBOARD_menuNews"=>"Neuigkeiten",
			"DASHBOARD_menuPolls"=>"Umfragen",
			"DASHBOARD_menuElems"=>"Was ist neu",
			"DASHBOARD_addNews"=>"Neue Nachrichten",
			"DASHBOARD_offlineNews"=>"Archivierte News anzeigen",
			"DASHBOARD_offlineNewsNb"=>"archivierte Nachrichten",
			"DASHBOARD_noNews"=>"Zurzeit keine Neuigkeiten",
			"DASHBOARD_addPoll"=>"Neue Umfrage",
			"DASHBOARD_pollsVoted"=>"Nur Umfragen mit Stimmen anzeigen",
			"DASHBOARD_pollsVotedNb"=>"Umfragen, für die ich bereits gestimmt habe",
			"DASHBOARD_pollsNotVoted"=>"Umfragen nicht bewertet",
			"DASHBOARD_vote"=>"Stimmen Sie ab und sehen Sie sich die Ergebnisse an!",
			"DASHBOARD_voteTooltip"=>"Die Abstimmung ist anonym: niemand erfährt Ihre Wahl",
			"DASHBOARD_answerVotesNb"=>"--NB_VOTES-- Mal abgestimmt",
			"DASHBOARD_pollVotesNb"=>"Die Umfrage wurde --NB_VOTES-- Mal bewertet",
			"DASHBOARD_pollVotedBy"=>"Abgestimmt von",
			"DASHBOARD_noPoll"=>"Zurzeit keine Umfragen",
			"DASHBOARD_plugins"=>"Neue Elemente erstellt",
			"DASHBOARD_pluginsTooltip"=>"Erstellte Elemente",
			"DASHBOARD_pluginsTooltip2"=>"zwischen den",
			"DASHBOARD_plugins_day"=>"heute",
			"DASHBOARD_plugins_week"=>"diese Woche",
			"DASHBOARD_plugins_month"=>"diesen Monat",
			"DASHBOARD_plugins_previousConnection"=>"seit der letzten Verbindung",
			"DASHBOARD_pluginsTooltipRedir"=>"Element in seinem Ordner anzeigen",
			"DASHBOARD_pluginEmpty"=>"Keine neuen Einträge in diesem Zeitraum",
			// Actualite/News
			"DASHBOARD_topNews"=>"Top-Neuigkeiten",
			"DASHBOARD_topNewsTooltip"=>"Neuigkeiten werden immer oben in der Liste angezeigt",
			"DASHBOARD_offline"=>"Archivierte Nachrichten",
			"DASHBOARD_dateOnline"=>"Geplante Veröffentlichung",
			"DASHBOARD_dateOnlineTooltip"=>"Planen Sie einen automatischen Veröffentlichungstermin. In der Zwischenzeit werden die Nachrichten archiviert",
			"DASHBOARD_dateOnlineNotif"=>"Bis zur automatischen Veröffentlichung werden die Nachrichten vorübergehend archiviert",
			"DASHBOARD_dateOffline"=>"Geplante Archivierung",
			"DASHBOARD_dateOfflineTooltip"=>"Termin zur automatischen Nachrichtenarchivierung festlegen",
			// Sondage/Polls
			"DASHBOARD_titleQuestion"=>"Titel / Frage",
			"DASHBOARD_multipleResponses"=>"Mehrere Antworten pro Abstimmung möglich",
			"DASHBOARD_newsDisplay"=>"Mit News anzeigen (linkes Menü)",
			"DASHBOARD_publicVote"=>"Die Wahl jedes Wählers ist öffentlich",
			"DASHBOARD_publicVoteInfos"=>"Die Wahl jedes Wählers wird im Umfrageergebnis angezeigt. Beachten Sie, dass eine öffentliche Abstimmung eine Teilnahmehürde an der Umfrage darstellen kann.",
			"DASHBOARD_dateEnd"=>"Ende der Abstimmung",
			"DASHBOARD_responseList"=>"Mögliche Antworten",
			"DASHBOARD_responseNb"=>"Antwort Nr.",
			"DASHBOARD_addResponse"=>"Antwort hinzufügen",
			"DASHBOARD_controlResponseNb"=>"Bitte geben Sie mindestens 2 mögliche Antworten an",
			"DASHBOARD_votedPollNotif"=>"Warnung: Sobald mit der Abstimmung über die Umfrage begonnen wurde, ist es nicht mehr möglich, den Titel und die Antworten der Umfrage zu ändern",
			"DASHBOARD_voteNoResponse"=>"Bitte wählen Sie eine Antwort aus",
			"DASHBOARD_exportPoll"=>"Umfrageergebnis als PDF herunterladen",
			"DASHBOARD_exportPollDate"=>"Umfrageergebnis vom",

			////	MOD : FILE
			////
			"FILE_MODULE_NAME"=>"Dateien",
			"FILE_MODULE_DESCRIPTION"=>"Dateimanager",
			"FILE_OPTION_adminRootAddContent"=>"Nur der Administrator kann Ordner und Dateien im Stammverzeichnis erstellen",
			"FILE_addFile"=>"Datei hinzufügen",
			"FILE_addFileAlert"=>"Auf den Serverordner kann nicht geschrieben werden! Bitte kontaktieren Sie den Administrator",
			"FILE_downloadSelection"=>"Auswahl herunterladen",
			"FILE_fileDownload"=>"Herunterladen",
			"FILE_fileSize"=>"Dateigröße",
			"FILE_imageSize"=>"Bildgröße",
			"FILE_nbFileVersions"=>"Dateiversionen",
			"FILE_downloadsNb"=>"(--NB_DOWNLOAD-- Mal heruntergeladen)",
			"FILE_downloadedBy"=>"Datei heruntergeladen von",
			"FILE_addFileVersion"=>"Neue Version der Datei hinzufügen",
			"FILE_noFile"=>"Zur Zeit keine Dateien",
			// Edit
			"FILE_fileSizeLimit"=>"Dateien dürfen nicht größer sein",
			"FILE_uploadSimple"=>"Einfacher Upload",
			"FILE_uploadMultiple"=>"Mehrfach-Upload",
			"FILE_imgReduce"=>"Bilder optimieren",
			"FILE_updatedName"=>"Der Dateiname ist anders: der Name der neuen Version wird daher beibehalten",
			"FILE_fileSizeError"=>"Datei zu groß",
			"FILE_addMultipleFilesTooltip"=>"Drücken Sie die Taste 'Strg', um mehrere Dateien auszuwählen",
			"FILE_selectFile"=>"Bitte wählen Sie mindestens eine Datei aus",
			"FILE_fileContent"=>"Inhalt",
			// Versions
			"FILE_versionsOf"=>"Versionen von",
			"FILE_confirmDeleteVersion"=>"Löschen dieser Version bestätigen?",

			////	MOD : CALENDAR
			////
			"CALENDAR_MODULE_NAME"=>"Kalender",
			"CALENDAR_MODULE_DESCRIPTION"=>"Gemeinsame und persönliche Kalender",
			"CALENDAR_OPTION_adminAddRessourceCalendar"=>"Nur der Administrator kann freigegebene Kalender erstellen",
			"CALENDAR_OPTION_adminAddCategory"=>"Nur der Administrator kann Ereigniskategorien erstellen",
			"CALENDAR_OPTION_createSpaceCalendar"=>"Einen gemeinsamen Kalender für den Space erstellen",
			"CALENDAR_CAT_menuTooltip"=>"Nur Ereignisse mit Kategorie anzeigen",
			"CALENDAR_CAT_showAll"=>"Alle Kategorien",
			"CALENDAR_CAT_showAllTooltip"=>"Alle Kategorien anzeigen",
			"CALENDAR_CAT_undefined"=>"Kategorie nicht definiert",
			"CALENDAR_CAT_editTitle"=>"Veranstaltungskategorien bearbeiten",
			"CALENDAR_CAT_editInfo"=>"Jede Kategorie kann von ihrem Autor oder vom allgemeinen Administrator bearbeitet werden",
			"CALENDAR_CAT_editAdd"=>"Kategorie hinzufügen",
			"CALENDAR_moduleAlwaysEnabledInfo"=>"Benutzer, die ihren persönlichen Kalender in ihrem Benutzerprofil nicht deaktiviert haben, sehen das Kalendermodul weiterhin in der Menüleiste",
			"CALENDAR_readableCalendars"=>"Verfügbare Kalender",
			"CALENDAR_hideAllCals"=>"Alle Kalender ausblenden",
			"CALENDAR_printCalendars"=>"Kalender drucken",
			"CALENDAR_printCalendarsInfos"=>"Seite im Querformat drucken",
			"CALENDAR_addSharedCalendar"=>"Neuer freigegebener Kalender",
			"CALENDAR_addSharedCalendarTooltip"=>"Einen gemeinsamen Kalender erstellen: für die Buchung eines Zimmers, Fahrzeugs, Videoprojektors usw.",
			"CALENDAR_exportIcal"=>"Veranstaltungen im iCal-Format exportieren",
			"CALENDAR_icalUrl"=>"Kopieren Sie die Adresse des Kalenders:<br>Um ihn über eine externe App abzurufen",
			"CALENDAR_icalUrlCopy"=>"Ermöglicht den Zugriff auf den Kalender aus einer externen App (schreibgeschützt):<br>aus Thunderbird, Outlook, Google Kalender usw.",
			"CALENDAR_importIcal"=>"Veranstaltungen im iCal-Format importieren",
			"CALENDAR_ignoreOldEvt"=>"Keine Ereignisse importieren, die älter als ein Jahr sind",
			"CALENDAR_importIcalPresent"=>"Bereits anwesend?",
			"CALENDAR_importIcalPresentInfo"=>"Ereignis bereits im Kalender vorhanden?",
			"CALENDAR_display_1Day"=>"1 Tag",
			"CALENDAR_display_3Days"=>"3 Tage",
			"CALENDAR_display_7Days"=>"7 Tage",
			"CALENDAR_display_week"=>"Woche",
			"CALENDAR_display_workWeek"=>"Arbeitswoche",
			"CALENDAR_display_month"=>"Monat",
			"CALENDAR_yearWeekNum"=>"Wochennummer anzeigen",
			"CALENDAR_periodNext"=>"Nächste Periode",
			"CALENDAR_periodPrev"=>"Vorheriger Zeitraum",
			"CALENDAR_evtAffects"=>"Im Kalender von",
			"CALENDAR_evtAffectToConfirm"=>"Warte auf Bestätigung im Kalender von",
			"CALENDAR_evtProposition"=>"Veranstaltungsvorschlag muss bestätigt werden",
			"CALENDAR_evtProposedBy"=>"Vorgeschlagen von",
			"CALENDAR_evtProposeConfirm"=>"Vorschlag bestätigen",
			"CALENDAR_evtProposeConfirmed"=>"Der Veranstaltungsvorschlag wurde dem Kalender hinzugefügt. <br>Eine Benachrichtigungs-E-Mail wurde an den Autor gesendet",
			"CALENDAR_evtProposeConfirmedMail"=>"Ihr Veranstaltungsvorschlag wurde bestätigt von",
			"CALENDAR_evtProposeDecline"=>"Vorschlag ablehnen",
			"CALENDAR_evtProposeDeclined"=>"Der Vorschlag wurde abgelehnt. <br>Eine Benachrichtigungs-E-Mail wurde an den Autor gesendet",
			"CALENDAR_evtProposeDeclinedMail"=>"Ihr Veranstaltungsvorschlag wurde abgelehnt",
			"CALENDAR_evtDelete"=>"Ereignis löschen",
			"CALENDAR_evtDeleteCal"=>"Entfernen Sie das Ereignis aus diesem Kalender",
			"CALENDAR_evtDeleteDate"=>"Löschen Sie das Ereignis an diesem Datum",
			"CALENDAR_evtPrivate"=>"Private Veranstaltung",
			"CALENDAR_evtAutor"=>"Von mir erstellte Veranstaltungen",
			"CALENDAR_evtAutorInfo"=>"Nur von mir erstellte Termine anzeigen",
			"CALENDAR_evtChangeTime"=>"Verschieben nach",
			"CALENDAR_evtChangeTimeConfirmed"=>"Der Termin wurde erfolgreich verschoben",
			"CALENDAR_noEvt"=>"Keine Veranstaltung",
			"CALENDAR_noCalendarDisplayed"=>"Kein Kalender angezeigt",
			// Evenement
			"CALENDAR_importanceNormal"=>"Normale Wichtigkeit",
			"CALENDAR_importanceHight"=>"Hohe Wichtigkeit",
			"CALENDAR_visibilityPublic"=>"Normale Anzeige",
			"CALENDAR_visibilityPublicHide"=>"Zeitbereichsanzeige",
			"CALENDAR_visibilityPrivate"=>"Private Anzeige",
			"CALENDAR_visibilityTooltip"=>"Für Personen mit Nur-Lese-Zugriff auf Kalender und Termin: <br>- Zeitfensteranzeige: Nur belegten Termin anzeigen und Details ausblenden<br>- Private Anzeige: Termin nicht anzeigen",
			// Edit
			"CALENDAR_sharedCalendarDescription"=>"Gemeinsamer Kalender des Spaces",
			"CALENDAR_noPeriodicity"=>"Nur einmal",
			"CALENDAR_period_weekDay"=>"Jede Woche",
			"CALENDAR_period_month"=>"Jeden Monat",
			"CALENDAR_period_monthDetail"=>"Jeden --DATE-- des Monats",
			"CALENDAR_period_year"=>"Jedes Jahr",
			"CALENDAR_period_yearDetail"=>"Jeden --DATE-- des Jahres",
			"CALENDAR_periodDateExceptions"=>"Ausnahme wiederholen",
			"CALENDAR_periodDateEnd"=>"Ende der Wiederholung",
			"CALENDAR_calendarAffectations"=>"Zuweisung zu Kalendern",
			"CALENDAR_addEvt"=>"Neue Veranstaltung",
			"CALENDAR_addEvtTooltip"=>"Ein Ereignis zum Kalender hinzufügen",
			"CALENDAR_addEvtTooltip2"=>"Ereignis zum Kalender hinzufügen",
			"CALENDAR_proposeEvtTooltip"=>"Bieten Sie eine Veranstaltung für diesen Kalender an (in Reading) : dann vom Kalenderbesitzer bestätigt",
			"CALENDAR_proposeOptionTooltip"=>"Möglichkeit, die Veranstaltung vorzuschlagen : dann vom Eigentümer des Kalenders bestätigt",
			"CALENDAR_verifCalNb"=>"Bitte wählen Sie mindestens einen Kalender aus",
			"CALENDAR_busyTimeSlot"=>"Slot im Kalender bereits belegt:",
			"CALENDAR_timeSlot"=>"Zeitfenster für Anzeige 'Woche'",
			"CALENDAR_propositionNotif"=>"Benachrichtige mich per E-Mail über jeden Veranstaltungsvorschlag",
			"CALENDAR_propositionNotifTooltip"=>"Jeder Veranstaltungsvorschlag wird vom Kalenderadministrator bestätigt oder für ungültig erklärt.",
			"CALENDAR_propositionGuest"=>"Gäste können Veranstaltungen vorschlagen",
			"CALENDAR_propositionGuestTooltip"=>"Denken Sie daran, in den Zugriffsrechten unten 'alle Benutzer und Gäste' auszuwählen.",
			"CALENDAR_propositionEmailSubject"=>"Neue Veranstaltung vorgeschlagen von",
			"CALENDAR_propositionEmailMessage"=>"Neues Ereignis vorgeschlagen von --AUTOR_LABEL-- : &nbsp; <i><b>--EVT_TITLE_DATE--</b></i> <br><i>--EVT_DESCRIPTION--</i> <br>Greifen Sie auf Ihren Bereich zu, um diesen Vorschlag zu bestätigen oder abzubrechen",

			////	MOD : FORUM
			////
			"FORUM_MODULE_NAME"=>"Forum",
			"FORUM_MODULE_DESCRIPTION"=>"Diskussionsforum",
			"FORUM_OPTION_adminAddSubject"=>"Nur Administratoren können Themen erstellen",
			"FORUM_OPTION_adminAddTheme"=>"Nur Administratoren können Designs erstellen",
			"FORUM_CAT_menuTooltip"=>"Nur Themen mit Thema anzeigen",
			"FORUM_CAT_showAll"=>"Alle Themen",
			"FORUM_CAT_showAllTooltip"=>"Alle Themen anzeigen",
			"FORUM_CAT_undefined"=>"Undefiniertes Thema",
			"FORUM_CAT_editTitle"=>"Forumsthemen bearbeiten",
			"FORUM_CAT_editInfo"=>"Jedes Thema kann von seinem Autor oder vom allgemeinen Administrator geändert werden",
			"FORUM_CAT_editAdd"=>"Ein Thema hinzufügen",
			"SORT_dateLastMessage"=>"letzte Nachricht",
			"FORUM_forumRoot"=>"Forum-Startseite",
			"FORUM_subject"=>"Betreff",
			"FORUM_subjects"=>"Themen",
			"FORUM_message"=>"Nachricht",
			"FORUM_messages"=>"Nachrichten",
			"FORUM_lastMessageFrom"=>"letzter von",
			"FORUM_noSubject"=>"Zurzeit keine Themen",
			"FORUM_subjectBy"=>"Betreff von",
			"FORUM_addSubject"=>"Neues Thema",
			"FORUM_displaySubject"=>"Thema anzeigen",
			"FORUM_addMessage"=>"Nachricht hinzufügen",
			"FORUM_quoteMessage"=>"Antworten",
			"FORUM_quoteMessageInfo"=>"Antworten Sie, indem Sie diese Nachricht zitieren",
			"FORUM_notifyLastPost"=>"Benachrichtige mich über jeden Beitrag",
			"FORUM_notifyLastPostTooltip"=>"Senden Sie mir eine E-Mail-Benachrichtigung für jeden neuen Beitrag",
			"FORUM_notifOnlyReadAccess"=>"Warnung: Wenn nur Lesezugriff besteht, kann niemand zum Thema beitragen...",
			"FORUM_notifWriteAccess"=>"Der ''Schreib''-Zugriff ist für die Moderatoren des Themas vorgesehen:<br>Es ist daher ratsam, das ''Eingeschränkte Schreibrecht'' zu verwenden",

			////	MOD : TASK
			////
			"TASK_MODULE_NAME"=>"Aufgaben",
			"TASK_MODULE_DESCRIPTION"=>"Aufgaben / Notizen",
			"TASK_OPTION_adminRootAddContent"=>"Nur der Administrator kann Ordner und Aufgaben im Stammverzeichnis erstellen",
			"TASK_OPTION_adminAddStatus"=>"Nur Administratoren können Aufgabenstatus erstellen",
			"TASK_CAT_menuTooltip"=>"Nur Aufgaben mit Status anzeigen",
			"TASK_CAT_showAll"=>"Alle Status",
			"TASK_CAT_showAllTooltip"=>"Alle Status anzeigen",
			"TASK_CAT_undefined"=>"Status undefiniert",
			"TASK_CAT_editTitle"=>"Aufgabenstatus bearbeiten",
			"TASK_CAT_editInfo"=>"Jeder Kanban-Status kann von seinem Autor oder vom allgemeinen Administrator geändert werden",
			"TASK_CAT_editAdd"=>"Kanban-Status hinzufügen",
			"SORT_priority"=>"Priorität",
			"SORT_advancement"=>"Fortschritt",
			"SORT_dateBegin"=>"Startdatum",
			"SORT_dateEnd"=>"Enddatum",
			"TASK_addTask"=>"Neue Aufgabe",
			"TASK_noTask"=>"Zurzeit keine Aufgaben",
			"TASK_advancement"=>"Fortschritt",
			"TASK_advancementAverage"=>"Durchschnittlicher Fortschritt",
			"TASK_priority"=>"Priorität",
			"TASK_priorityUndefined"=>"Priorität nicht definiert",
			"TASK_priority1"=>"Niedrig",
			"TASK_priority2"=>"Normal",
			"TASK_priority3"=>"Hoch",
			"TASK_assignedTo"=>"Zugewiesen an",
			"TASK_advancementLate"=>"Fortschritt zu spät",
			"TASK_folderDateBeginEnd"=>"Frühester Beginn / Spätestes Ende",

			////	MOD : CONTACT
			////
			"CONTACT_MODULE_NAME"=>"Kontakte",
			"CONTACT_MODULE_DESCRIPTION"=>"Kontaktverzeichnis",
			"CONTACT_OPTION_adminRootAddContent"=>"Nur der Administrator kann Ordner und Kontakte im Stammverzeichnis erstellen",
			"CONTACT_addContact"=>"Neuer Kontakt",
			"CONTACT_noContact"=>"Zurzeit kein Kontakt",
			"CONTACT_createUser"=>"Einen Benutzer in diesem Bereich erstellen",
			"CONTACT_createUserConfirm"=>"Neues Benutzerkonto für den aktuellen Bereich erstellen, von diesem Kontakt aus?",
			"CONTACT_createUserConfirmed"=>"Benutzer wurde erstellt",

			////	MOD : LINK
			////
			"LINK_MODULE_NAME"=>"Links",
			"LINK_MODULE_DESCRIPTION"=>"Internet-Links und Lieblings-Websites",
			"LINK_OPTION_adminRootAddContent"=>"Nur der Administrator kann Ordner und Links im Stammverzeichnis erstellen",
			"LINK_addLink"=>"Neuer Link",
			"LINK_noLink"=>"Zurzeit keine Links",
			"LINK_adress"=>"Webadresse",

			////	MOD : MAIL
			////
			"MAIL_MODULE_NAME"=>"E-Mail",
			"MAIL_MODULE_DESCRIPTION"=>"E-Mails an Benutzer und/oder Kontakte versenden (Newsletter)",
			"MAIL_specifyMail"=>"Bitte geben Sie mindestens einen Empfänger an",
			"MAIL_title"=>"Betreff der E-Mail",
			"MAIL_description"=>"E-Mail-Nachricht",
			"MAIL_historyTitle"=>"Verlauf der gesendeten E-Mails",
			"MAIL_delete"=>"E-Mail löschen",
			"MAIL_resend"=>"E-Mail erneut senden",
			"MAIL_resendInfo"=>"Rufen Sie den Inhalt dieser E-Mail ab, um sie erneut zu versenden",
			"MAIL_historyEmpty"=>"Noch keine E-Mail",
		);
	}

	/*
	 * Feiertage des Jahres
	 */
	public static function publicHolidays($year)
	{
		$dateList[$year."-01-01"]="Neujahr";
		$dateList[$year."-12-25"]="Weihnachten";
		$dateList[$year."-12-26"]="Zweiter Weihnachtsfeiertag";
		if(function_exists("easter_date")){
			$easterTime=easter_date($year);
			$dateList[date('Y-m-d',$easterTime)]		="Ostern";
			$dateList[date('Y-m-d',$easterTime+86400)]	="Ostermontag";			
		}
		$tmpDates=Txt::timeChangeDates($year);
		$dateList[$tmpDates["summer"]]="Sommerzeit";
		$dateList[$tmpDates["winter"]]="Winterzeit";
		return $dateList;
	}
}