<?php
/*
 * Traductions
 */
class Trad extends Txt
{
	/*
	 * Chargement les elements de traduction
	 */
	public static function loadTrads()
	{
		////	Dates formatées par PHP
		setlocale(LC_TIME, "es_ES.utf8", "es_ES.UTF-8", "es_ES", "es", "spanish");

		////	TRADUCTIONS
		self::$trad=array(
			////	Langue de l'appli, des dates et de l'éditeur
			"CURLANG"=>"es",
			"DATELANG"=>"es_ES",
			"EDITORLANG"=>"es",
			"FANCYBOXLANG"=>"es",

			////	Divers
			"mainMenu"=>"Menú principal",
			"menuOptions"=>"Menú de opciones",
			"emptyFields"=>"Por favor, rellene los campos del formulario",
			"requiredFields"=>"Campo obligatorio",
			"inaccessibleElem"=>"Elemento inaccesible",
			"warning"=>"Atención",
			"elemEditedByAnotherUser"=>"Atención : este elemento está actualmente editado por",
			"yes"=>"sí",
			"no"=>"no",
			"none"=>"no",
			"or"=>"o",
			"and"=>"y",
			"goToPage"=>"Ir a la página",
			"alphabetFilter"=>"Filtro alfabético",
			"displayAll"=>"Mostrar todo",
			"show"=>"Mostrar",
			"hide"=>"Ocultar",
			"byDefault"=>"Por defecto",
			"changeOrder"=>"Mover a establecer el orden de presentación de los módulos",
			"mapLocalize"=>"Localizar en el mapa",
			"mapLocalizationFailure"=>"Falla de localización de la siguiente dirección",
			"mapLocalizationFailure2"=>"Verifique que exista la dirección en www.google.com/maps o www.openstreetmap.org",
			"sendMail"=>"enviar un email",
			"sendMailTo"=>"Enviar un email a",
			"mailInvalid"=>"El email no es válida",
			"element"=>"elemento",
			"elements"=>"elementos",
			"folder"=>"carpeta",
			"folders"=>"carpetas",
			"close"=>"Cerrar",
			"modifRecorded"=>"Los cambios fueron registrados",
			"comment"=>"Comentario",
			"commentAdd"=>"Añadir un comentario",
			"optional"=>"(opcional)",
			"objNew"=>"Elemento creado recientemente",
			"objNewTooltip"=>"Creado hoy o desde el último inicio de sesión",
			"personalAccess"=>"Acceso personal",
			"copyUrl"=>"Copiar el enlace para compartir",
			"copyUrlTooltip"=>"Copiar el enlace para compartir (URL) para enviarlo por email, mensajería, etc.",
			"copyUrlNotif"=>"El enlace se ha copiado correctamente",
			"footerGeneratedTime"=>"Página generada en",
		
			////	Confirm et Suppression
			"confirm"=>"Confirmar",
			"confirmOk"=>"Ok",
			"confirmCancel"=>"Cancelar",
			"confirmDownload"=>"¿ Descargar el archivo ?",
			"confirmCloseForm"=>"¿ Cerrar el formulario sin guardar ?",
			"delete"=>"Eliminar",
			"confirmDelete"=>"¿ Confirmar eliminación ?",
			"confirmDeleteAlert"=>"La eliminación es permanente",
			"confirmDeleteNotify"=>"La eliminación fue exitosa",
			"confirmDeleteSelect"=>"¿ Desea eliminar estos elementos permanentemente ?",
			"confirmDeleteSelectNb"=>"elementos seleccionados",
			"confirmDeleteFolder"=>"Algunas subcarpetas no son accesibles para usted: ¿puede confirmarlo de todos modos ?",
			"confirmDeleteWait"=>"Espere un momento: la eliminación de la carpeta puede tardar unos segundos",
			"notifDeleteFolderUncomplete"=>"Algunos elementos no se han eliminado porque no tienes los derechos de acceso necesarios",
			
			////	Images
			"picture"=>"Foto",
			"pictureProfil"=>"Foto de perfil",
			"wallpaper"=>"Wallpaper",
			"keepImg"=>"Mantener la imagen",
			"changeImg"=>"Cambiar la imagen",
			"pixels"=>"píxeles",

			////	Connexion
			"specifyLoginPassword"=>"Gracias a especificar un nombre de usuario y contraseña",
			"specifyLogin"=>"Gracias especificar un email/identificador (sin espacio)",
			"mailLloginNotif"=>"Se recomienda utilizar un email como identificador de sesión",
			"mailLlogin"=>"Email / Identificador de conexión",
			"connect"=>"Conexión",
			"connectAuto"=>"Mantente conectado",
			"connectAutoTooltip"=>"Recordar mis datos de inicio de sesión para la conexión automática",
			"gOAuthUserUnknown"=>"no está registrado en el espacio",
			"connectSpaceSwitch"=>"Conectarse a otro espacio",
			"guestAccess"=>"Iniciar sesión como invitado",
			"guestAccessTooltip"=>"Iniciar sesión en este espacio como invitado",
			"publicSpacePasswordError"=>"Contraseña incorrecta",
			"disconnectSpace"=>"Cerrar sesión",
			"disconnectSpaceConfirm"=>"¿ Desconexión del espacio ?",

			////	Password : connexion / modification / reset
			"password"=>"Contraseña",
			"passwordDisplay"=>"Mostrar / ocultar la contraseña",
			"passwordOptional"=>"Complete este campo solo para modificar la contraseña",
			"passwordInvalid"=>"La contraseña debe contener al menos 8 caracteres alfanuméricos (idealmente con números, letras y caracteres especiales.)",
			"passwordModif"=>"Modificar la contraseña",
			"passwordTmp"=>"Contraseña temporal (a modificar en la página de inicio de sesión)",
			"passwordByDefault"=>"Contraseña predeterminada (modifíquela si es necesario en su perfil)",
			"resetPassword"=>"¿ Olvidó su contraseña ?",
			"resetPassword2"=>"Indique su email para restablecer su contraseña de acceso",
			"resetPasswordNotif"=>"El correo para restablecer su contraseña ha sido enviado.<br>Si no lo ha recibido, verifique la dirección ingresada",
			"resetPasswordMailTitle"=>"Restablecer su contraseña",
			"resetPasswordMailPassword"=>"Para restablecer su contraseña y volver a conectarse",
			"resetPasswordMailPassword2"=>"haga clic aquí",
			"resetPasswordMailLoginRemind"=>"Recordatorio de su identificador de inicio de sesión",
			"resetPasswordIdExpired"=>"El enlace para regenerar la contraseña ha expirado. Por favor, reinicie el procedimiento",

			////	Type d'affichage
			"displayMode"=>"Visualización",
			"displayMode_line"=>"líneas",
			"displayMode_block"=>"Bloques",

			////	Sélectionner / Déselectionner tous les éléments
			"select"=>"Seleccionar",
			"selectUnselect"=>"Seleccionar / Deseleccionar",
			"selectAll"=>"Seleccionar todo",
			"selectNone"=>"Deseleccionar todo",
			"selectSwitch"=>"Invertir selección",
			"deleteElems"=>"Eliminar elementos",
			"changeFolder"=>"Mover a otro carpeta",
			"showOnMap"=>"Mostrar en el mapa",
			"showOnMapTooltip"=>"Ver en un mapa los contactos con dirección, código postal, ciudad",
			"notifSelectUser"=>"Gracias por seleccionar al menos un usuario",
			"notifSelectUsers"=>"Gracias por seleccionar por lo menos dos usuarios",
			"selectSpace"=>"Gracias por elegir al menos un espacio",
			"visibleAllSpaces"=>"Visible en todos los espacios",/*cf. Categories, themes, etc*/
			"visibleOnSpace"=>"Disponible en el espacio",/*"..Mon espace"*/

			////	Temps ("de 11h à 12h", "le 25-01-2007 à 10h30", etc.)
			"from"=>"de",
			"at"=>"a",
			"begin"=>"Inicio",
			"end"=>"Fin",
			"beginEnd"=>"Inicio / Fin",
			"days"=>"dias",
			"day_1"=>"lunes",
			"day_2"=>"Martes",
			"day_3"=>"miércoles",
			"day_4"=>"Jueves",
			"day_5"=>"Viernes",
			"day_6"=>"Sábado",
			"day_7"=>"Domingo",
			"month_1"=>"Enero",
			"month_2"=>"Febrero",
			"month_3"=>"marzo",
			"month_4"=>"Abril",
			"month_5"=>"Mayo",
			"month_6"=>"Junio",
			"month_7"=>"julio",
			"month_8"=>"agosto",
			"month_9"=>"Septiembre",
			"month_10"=>"octubre",
			"month_11"=>"Noviembre",
			"month_12"=>"Diciembre",
			"today"=>"hoy",
			"displayToday"=>"Mostrar hoy",
			"beginEndError"=>"La fecha de inicio debe ser anterior a la fecha de finalización.",
			"dateFormatError"=>"La fecha debe estar en el formato dd/mm/AAAA",
			"timeFormatError"=>"La hora debe estar en el formato HH:mm",

			////	Menus d'édition des objets et editeur tinyMce
			"title"=>"Título",
			"name"=>"Nombre",
			"description"=>"Descripción",
			"specifyName"=>"Gracias por especificar un nombre",
			"editorDraft"=>"Recuperar mi texto",
			"editorDraftConfirm"=>"Recuperar el último texto introducido en el editor",
			"editorFileInsert"=>"Añadir imagen o video",
			"editorFileInsertNotif"=>"Seleccione una imagen en formato Jpeg, Png, Gif o Svg",
		
			////	Validation des formulaires
			"add"=>"Añadir",
			"modify"=>"Editar",
			"record"=>"Registrar",
			"modifyAndAccesRight"=>"Editar + derechos de acceso",
			"validate"=>"Validar",
			"send"=>"Enviar",
			"sendTo"=>"Enviar a",

			////	Tri d'affichage. Tous les éléments (dossier, tâche, lien, etc...) ont par défaut une date, un auteur & une description
			"sortBy"=>"Ordenado por",
			"sortBy2"=>"Ordenar por",
			"SORT_dateCrea"=>"fecha de creación",
			"SORT_dateModif"=>"fecha de modification",
			"SORT_title"=>"título",
			"SORT_description"=>"descripción",
			"SORT__idUser"=>"autor",
			"SORT_extension"=>"tipo de archivo",
			"SORT_octetSize"=>"tamaño",
			"SORT_downloadsNb"=>"downloads",
			"SORT_civility"=>"civilidad",
			"SORT_name"=>"apellido",
			"SORT_firstName"=>"nombre",
			"SORT_adress"=>"dirección",
			"SORT_postalCode"=>"código postal",
			"SORT_city"=>"ciudad",
			"SORT_country"=>"país",
			"SORT_function"=>"función",
			"SORT_companyOrganization"=>"compañía / organización",
			"SORT_lastConnection"=>"último acceso",
			"SORT_ascend"=>"Ascendente",
			"SORT_descend"=>"Descendente",
			
			////	Visibilité d'un Objet
			"guest"=>"invitado",
			"createdBy"=>"Creado por",
			"modifBy"=>"Modificado por",
			"objHistory"=>"Historial del elemento",
			"all"=>"todos",
			"deletedUser"=>"Antigua cuenta de usuario",
			"categoryNotifSpaceAccess"=>"solo es accesible en el espacio",
			"categoryNotifChangeOrder"=>"El orden de visualización ha sido modificado correctamente",
			"folderContent"=>"Contenido",

			////	Droit d'accès d'un Objet
			"accessRead"=>"Lectura",
			"accessReadTooltip"=>"Acceso de lectura --OBJ_LABEL_TO--",
			"accessWriteLimit"=>"Escritura limitada",
			"accessWriteLimitTooltip"=>"Acceso de lectura y <i>escritura limitada</i> --OBJ_LABEL_TO-- :<br>Derecho a añadir, modificar y eliminar solo --OBJ_LABEL_CONTENT-- que se han creado",
			"accessWrite"=>"Escritura",
			"accessWriteTooltip"=>"Acceso de lectura y escritura --OBJ_LABEL_TO--",
			"accessWriteTooltipContainer"=>"Acceso de lectura y escritura --OBJ_LABEL_TO-- :<br>Derecho a añadir, modificar y eliminar todos los --OBJ_LABEL_CONTENT--",
			"accessFullTooltip"=>"Administrador y Autor:<br>Acceso completo de lectura y escritura --OBJ_LABEL_TO--",
			"accessAllUsers"=>"Todos los usuarios",
			"accessAllUsersTooltip"=>"Derechos de acceso para los usuarios del espacio <i>--SPACENAME--</i>",
			"accessAllUsersGuests"=>"Todos los usuarios e invitados",
			"accessAllUsersGuestsTooltip"=>"Derechos de acceso para usuarios e invitados del espacio <i>--SPACENAME--</i>.<hr>Limitado a lectura para invitados (sin cuenta de usuario)",

			////	Libellé des objets (cf. "::objectType")
			"OBJ_space"=>"Espacio",								//ModSpace
			"OBJ_space_TO"=>"al espacio",
			"OBJ_user"=>"usuario",								//ModUser
			"OBJ_user_TO"=>"al usuario",
			"OBJ_mail"=>"email",     				//ModMail
			"OBJ_mail_TO"=>"al email",
			"OBJ_dashboardNews"=>"actualidad",    				//ModDashboard
			"OBJ_dashboardNews_TO"=>"a la actualidad",
			"OBJ_dashboardPoll"=>"encuesta",
			"OBJ_dashboardPoll_TO"=>"a la encuesta",
			"OBJ_fileFolder"=>"carpeta de archivos", 			//ModFile
			"OBJ_fileFolder_TO"=>"a la carpeta de archivos",
			"OBJ_file"=>"archivo",
			"OBJ_file_TO"=>"al archivo",
			"OBJ_file_CONTENT"=>"los archivos",
			"OBJ_contactFolder"=>"carpeta de contactos",		//ModContact
			"OBJ_contactFolder_TO"=>"a la carpeta de contactos",
			"OBJ_contact"=>"contacto",
			"OBJ_contact_TO"=>"al contacto",
			"OBJ_contact_CONTENT"=>"los contactos",
			"OBJ_linkFolder"=>"carpeta de favoritos", 			//ModLink
			"OBJ_linkFolder_TO"=>"a la carpeta de favoritos",
			"OBJ_link"=>"favorito",
			"OBJ_link_TO"=>"al favorito",
			"OBJ_link_CONTENT"=>"los favoritos",
			"OBJ_taskFolder"=>"carpeta de tareas",				//ModTask
			"OBJ_taskFolder_TO"=>"a la carpeta de tareas",
			"OBJ_task"=>"tarea",
			"OBJ_task_TO"=>"a la tarea",
			"OBJ_task_CONTENT"=>"las tareas",
			"OBJ_calendar"=>"calendario",  						//ModCalendar
			"OBJ_calendar_TO"=>"al calendario",
			"OBJ_calendarEvent"=>"evento",
			"OBJ_calendarEvent_TO"=>"al evento",
			"OBJ_calendarEvent_CONTENT"=>"los eventos",
			"OBJ_forumSubject"=>"tema del foro", 				//ModForum
			"OBJ_forumSubject_TO"=>"al tema del foro",
			"OBJ_forumMessage"=>"mensaje del foro",
			"OBJ_forumMessage_TO"=>"al mensaje del foro",
			"OBJ_forumMessage_CONTENT"=>"los mensajes del foro",

			////	Envoi d'un email
			"MAIL_sendOk"=>"¡ Email ha sido enviado!",
			"MAIL_sendNotOk"=>"El email no se pudo enviar..",
			"MAIL_recipients"=>"destinatarios",
			"MAIL_hello"=>"Hola",
			"MAIL_hideRecipients"=>"Ocultar destinatarios",
			"MAIL_hideRecipientsTooltip"=>"Poner todos los destinatarios en copia oculta. Tenga en cuenta que con esta opción su email puede llegar en spam en algunas mensajerías",
			"MAIL_addReplyTo"=>"pon mi correo en respuesta",
			"MAIL_addReplyToTooltip"=>"Añadir mi email en el campo ''Responder a'' <br> Tenga en cuenta que con esta opción su email puede llegar en spam en algunas mensajerías",
			"MAIL_noFooter"=>"No firme el mensaje",
			"MAIL_noFooterTooltip"=>"No firme el final del mensaje con el nombre del remitentey un enlace al espacio",
			"MAIL_receptionNotif"=>"Confirmación de entrega",
			"MAIL_receptionNotifTooltip"=>"Advertencia! algunos clientes de email no soportan el recibo de entrega",
			"MAIL_specificMails"=>"Añadir direcciones de email",
			"MAIL_specificMailsTooltip"=>"Añadir direcciones de email no enumeradas en el espacio",
			"MAIL_maxFileSizeConfirm"=>"El conjunto de archivos adjuntos excede el límite de recepción de algunos buzones de correo (--MAXFILESSIZE--). <br><br> ¿Enviarlo de todos modos?",
			"MAIL_maxFileSizeNotif"=>"El archivo no se agregó al email porque es demasiado grande",
			"MAIL_sendMail"=>"Enviar email",
			"MAIL_sendBy"=>"Enviado por",
			"MAIL_sendNotif"=>"El email de notificación ha sido enviado !",
			"MAIL_fromTheSpace"=>"desde el espacio",
			"MAIL_elemCreatedBy"=>"--OBJ_LABEL-- creado por",
			"MAIL_elemModifiedBy"=>"--OBJ_LABEL-- modificado por",
			"MAIL_elemAccessLink"=>"Ver en mi espacio",

			////	Dossier & fichier
			"gigaOctet"=>"GB",
			"megaOctet"=>"MB",
			"kiloOctet"=>"KB",
			"rootFolder"=>"Carpeta raíz",
			"rootFolderTooltip"=>"Abra la configuración del espacio para cambiar los derechos de acceso a la carpeta raíz",
			"addFolder"=>"añadir un directorio",
			"download"=>"Descargar archivos",
			"downloadFolder"=>"Descargar la carpeta",
			"diskSpaceUsed"=>"Espacio utilizado",
			"diskSpaceUsedModFile"=>"Espacio utilizado para los Archivos",
			"downloadAlert"=>"Su archivo es demasiado grande para descargarlo durante el día (--ARCHIVE_SIZE--). Por favor reiniciar la descarga a partir de las",
			"downloadBackToApp"=>"Volver a la aplicación",
			
			////	Infos sur une personne
			"civility"=>"Civilidad",
			"name"=>"Apellido",
			"firstName"=>"Nombre",
			"adress"=>"Dirección",
			"postalCode"=>"Código postal",
			"city"=>"Ciudad",
			"country"=>"País",
			"telephone"=>"Teléfono",
			"telmobile"=>"teléfono móvil",
			"mail"=>"Email",
			"function"=>"Función",
			"companyOrganization"=>"compañía / organización",
			"lastConnection"=>"Última conexión",
			"notConnected"=>"Aún no conectado",
			"connectedToday"=>"Conectado hoy",
			"connectedThe"=>"Conectado el",
			"displayProfil"=>"Ver perfil",
			
			////	Captcha
			"captcha"=>"Copiar los 5 caracteres",
			"captchaTooltip"=>"Por favor, escriba los 5 caracteres para su identificación",
			"captchaError"=>"La identificación visual no es valida",
			
			////	Rechercher
			"searchSpecifyText"=>"Especifique al menos 3 caracteres (alfanuméricos y sin caracteres especiales)",
			"search"=>"Buscar",
			"searchOnSpace"=>"Buscar en el espacio",
			"searchDateCrea"=>"Fecha de creación",
			"searchDateCreaDay"=>"menos de un día",
			"searchDateCreaWeek"=>"menos de una semana",
			"searchDateCreaMonth"=>"menos de un mes",
			"searchDateCreaYear"=>"menos de un año",
			"advancedSearch"=>"Búsqueda avanzada",
			"advancedSearchAnyWord"=>"cualquier palabra",
			"advancedSearchAllWords"=>"todas las palabras",
			"advancedSearchExactPhrase"=>"frase exacta",
			"keywords"=>"Palabras clave",
			"listModules"=>"Módulos",
			"listFields"=>"Campos",
			"listFieldsElems"=>"Elementos involucrados",
			"noResults"=>"No hay resultados",
			
			////	Inscription d'utilisateur
			"userInscription"=>"registrarme al espacio",
			"userInscriptionTooltip"=>"crear una nueva cuenta de usuario (validado por un administrador)",
			"userInscriptionSpace"=>"Registrarme al espacio",
			"userInscriptionRecorded"=>"Su registro será validado tan pronto como sea posible por el administrador del espacio",
			"userInscriptionEmailSubject"=>"Nuevo registro en el espacio",
			"userInscriptionEmailMessage"=>"<i>--NEW_USER_LABEL--</i> ha solicitado un nuevo registro para el espacio <i>--SPACE_NAME--</i> : <br><br><i>--NEW_USER_MESSAGE--<i> <br><br>Recuerde validar o invalidar este registro durante su próxima conexión.",
			"userInscriptionEdit"=>"Permitir a los visitantes que se registren en el espacio",
			"userInscriptionEditTooltip"=>"El registro se encuentra en la página de inicio. Debe ser validado por el administrador del espacio.",
			"userInscriptionNotif"=>"Notificar por email en cada registro",
			"userInscriptionNotifTooltip"=>"Envíe una notificación por email a los administradores del espacio, después de cada registro",
			"userInscriptionValidate"=>"Registros de usuarios",
			"userInscriptionValidateTooltip"=>"Validar registros de usuarios al espacio",
			"userInscriptionSelectValidate"=>"Validar registros",
			"userInscriptionSelectInvalidate"=>"Invalidar registros",
			"userInscriptionInvalidateMail"=>"Su cuenta no ha sido validado en",
			
			////	Importer ou Exporter : Contact OU Utilisateurs
			"importExport_user"=>"Importar / Exportar usuarios",
			"import_user"=>"Importar usuarios en el espacio actual",
			"export_user"=>"Exportar usuarios del espacio",
			"importExport_contact"=>"Importar / Exportar contactos",
			"import_contact"=>"Importar contactos en la carpeta actual",
			"export_contact"=>"Exportar contactos de la carpeta actual",
			"exportFormat"=>"formato",
			"specifyFile"=>"or favor, especifique un archivo",
			"fileExtension"=>"El tipo del archivo no es válido. Debe ser de tipo",
			"importContactRootFolder"=>"Los contactos se asignarán por defecto a &quot;todos los usuarios del espacio&quot;",
			"importInfo"=>"Seleccione los campos (Agora) de destino con las listas desplegables de cada columna.",
			"importNotif1"=>"Por favor, seleccione la columna de nombre en las listas desplegables",
			"importNotif2"=>"Por favor, seleccione al menos un contacto para importar",
			"importNotif3"=>"El campo Agora ya ha sido seleccionado en otra columna (cada campo Agora se puede seleccionar sólo una vez)",
			
			////	Messages d'erreur / Notifications
			"NOTIF_identification"=>"Nombre de usuario o contraseña no válida",
			"NOTIF_presentIp"=>"Esta cuenta de usuario se está utilizando actualmente desde otra computadora, con otra dirección IP",
			"NOTIF_noAccessNoSpaceAffected"=>"Su cuenta de usuario se ha identificado correctamente, pero actualmente no está asignado a ningún espacio. Por favor contacte al administrador",
			"NOTIF_noAccess"=>"No estas logueado",
			"NOTIF_fileOrFolderAccess"=>"El archivo o la carpeta no está disponible",
			"NOTIF_diskSpace"=>"El espacio para almacenar sus archivos no es suficiente, no se puede añadir archivos",
			"NOTIF_fileNotAllowed"=>"los archivos sensibles o no reconocidos deben comprimirse antes de añadirlos",
			"NOTIF_fileVersion"=>"Tipo de archivo diferente del original",
			"NOTIF_folderMove"=>"No se puede mover la carpeta dentro de sí mismo..!",
			"NOTIF_duplicateName"=>"Un elemento con el mismo nombre ya existe",
			"NOTIF_duplicateNameFolder"=>"Ya existe una carpeta con el mismo nombre",
			"NOTIF_fileName"=>"Un archivo con el mismo nombre ya existe (no ha sido reemplazado)",
			"NOTIF_chmodDATAS"=>"El directorio ''DATAS'' no es accesible por escrito. Usted necesita dar un acceso de lectura y escritura para el propietario y el grupo (''chmod 775'').",
			"NOTIF_usersNb"=>"No se puede añadir un nuevo usuario : se limita a ",
			
			////	Header
			"HEADER_displaySpace"=>"Espacios de trabajo",
			"HEADER_displayAdmin"=>"Visualización de Administrador",
			"HEADER_displayAdminInfo"=>"Permite mostrar elementos en el espacio que no están asignados directamente a mí : carpetas, calendarios, etc.",
			"HEADER_displayAdminEnabled"=>"Visualización de Administrador habilitado",
			"HEADER_displayAdminDisabled"=>"Visualización de Administrador deshabilitada",
			"HEADER_documentation"=>"Documentación",
			"HEADER_shortcuts"=>"Acceso directo",

			////	Messenger / Visio
			"MESSENGER_MODULE_NAME"=>"Mensajería",
			"MESSENGER_MODULE_DESCRIPTION"=>"Chatea o inicia una videoconferencia con personas en línea",
			"MESSENGER_messengerMultiUsers"=>"Chatea con varias personas en el sistema de mensajería (panel izquierdo para seleccionar destinatarios)",
			"MESSENGER_chatWithMulti"=>"Chatea con",
			"MESSENGER_chatWith"=>"Chatea o inicia una videoconferencia con",
			"MESSENGER_messageFrom"=>"Mensaje de",
			"MESSENGER_messageSentTo"=>"Enviado a",
			"MESSENGER_messageToSelected"=>"Mensaje a las personas seleccionadas",
			"MESSENGER_messageTo"=>"Mensaje para",
			"MESSENGER_addMessageNotif"=>"Especifica un mensaje",
			"MESSENGER_visioProposeTo"=>"Proponer una videoconferencia a",
			"MESSENGER_visioProposeToSelection"=>"Proponer una videoconferencia a las personas seleccionadas",
			"MESSENGER_visioProposeToUsers"=>"Haga clic aquí para iniciar la videoconferencia entre",
			"MESSENGER_nobody"=>"No hay otros usuarios conectados actualmente",
			
			////	Lancer une Visio
			"VISIO_urlAdd"=>"Añadir una videoconferencia",
			"VISIO_urlAddConfirm"=>"Añadir un enlace al final del texto para comenzar una nueva videoconferencia ?",
			"VISIO_urlCopy"=>"Copia el enlace de la videoconferencia",
			"VISIO_urlDelete"=>"Eliminar el enlace de la videoconferencia",
			"VISIO_launch"=>"Iniciar la videoconferencias",
			"VISIO_launchJitsi"=>"Iniciar videoconferencias <br>con la aplicación Jitsi",
			"VISIO_launchFromEvent"=>"Iniciar la videoconferencia de este evento",
			"VISIO_launchGuide"=>"Problemas con la cámara o el micrófono: sigue la guía",
			"VISIO_launchServerTooltip"=>"Elija el servidor secundario si el servidor principal no funciona correctamente.<br>Tus contactos deberán seleccionar el mismo servidor de video.",
			"VISIO_launchServerMain"=>"Servidor principal",
			"VISIO_launchServerAlt"=>"Servidor secundario",

			////	VueObjMenuEdit.php
			"EDIT_notifNoSelection"=>"Debe seleccionar al menos una persona o un espacio",
			"EDIT_notifNoPersoAccess"=>"¿ Usted no se ha asignado al elemento. validar todos lo mismo ?",
			"EDIT_parentFolderAccessError"=>"Verifique los derechos de acceso de la carpeta principal <br><i>--FOLDER_NAME--</i><br><br> También debe haber un derecho de acceso para <br><i>--SPACE_LABEL--</ i> &nbsp;>&nbsp; <i>--TARGET_LABEL--</i><br><br> ¡De lo contrario no se podrá acceder a este archivo!",
			"EDIT_accessRight"=>"Derechos de acceso",
			"EDIT_accessRightContent"=>"Derechos de acceso al contenido",
			"EDIT_spaceNoModule"=>"El módulo actual aún no se ha añadido a este espacio",
			"EDIT_showAllUsers"=>"Mostrar todos los usuarios",
			"EDIT_showAllSpaces"=>"Mostrar todos los espacios",
			"EDIT_notifMail"=>"Notificar",
			"EDIT_notifMail2"=>"Enviar una notificación de creación/cambio por email",
			"EDIT_notifMailTooltip"=>"Enviar una notificación por email a las personas con acceso --OBJ_LABEL_TO--",
			"EDIT_notifMailTooltipCal"=>"<hr>Calendario personal: enviado solo a las personas que pueden editar el calendario.<br>Calendario compartido: enviado a cualquier persona que pueda consultar el calendario.",
			"EDIT_notifMailAddFiles"=>"Adjuntar archivos a la notificación",
			"EDIT_notifMailSelect"=>"Seleccionar los destinatarios de las notificaciones",
			"EDIT_extendSubfolders"=>"Dar igualdad de derechos a todos los sub-carpetas",
			"EDIT_extendSubfoldersTooltip"=>"Extender los derechos de acceso, a los sub-carpetas que se pueden editar",
			"EDIT_shortcut"=>"Acceso directo",
			"EDIT_shortcutInfo"=>"Mostrar un acceso directo en el menú principal",
			"EDIT_attachedFile"=>"Adjuntos archivos",
			"EDIT_attachedFileAdd"=>"Añadir archivos",
			"EDIT_attachedFileInsert"=>"Insertar en texto",
			"EDIT_attachedFileInsertTooltip"=>"Insertar imagen/video en el texto del editor (formato jpg, png o mp4)",
			"EDIT_guestName"=>"Su nombre / apodo",
			"EDIT_guestNameNotif"=>"Por favor, especifique un nombre / apodo",
			"EDIT_guestMail"=>"Su email",
			"EDIT_guestMailTooltip"=>"Por favor especifique su email para la validación de su propuesta",
			"EDIT_guestElementRegistered"=>"Gracias por su propuesta : será examinada lo antes posible antes de la validación",
			
			////	Formulaire d'installation
			"INSTALL_dbConnect"=>"Conexión a la base de datos",
			"INSTALL_dbHost"=>"Nombre del servidor host (hostname)",
			"INSTALL_dbName"=>"Nombre de la base de datos",
			"INSTALL_dbLogin"=>"Nombre de Usuario",
			"INSTALL_adminAgora"=>"Administrador del Ágora",
			"INSTALL_errorDbNameFormat"=>"Advertencia: el nombre de la base de datos debe contener solo caracteres alfanuméricos y guiones o guiones bajos",
			"INSTALL_errorDbConnection"=>"No identificación con la base de datos MariaDB/MySQL",
			"INSTALL_errorDbExist"=>"Aplicación ya instalada: <a href='index.php'>haga clic aquí para acceder</a><br><br>Para reiniciar la instalación, recuerde eliminar la base de datos",
			"INSTALL_errorDbNoSqlFile"=>"No se puede acceder al archivo de instalación db.sql o se eliminó porque la instalación ya se realizó",
			"INSTALL_PhpOldVersion"=>"Agora-Project --CURRENT_VERSION-- requiere una versión más reciente de PHP",
			"INSTALL_confirmInstall"=>"¿ Confirmar instalación ?",
			"INSTALL_installOk"=>"Agora-Project ha sido instalado !",
			// Premiers enregistrements en DB
			"INSTALL_agoraDescription"=>"Espacio para el intercambio y el trabajo colaborativo",
			"INSTALL_dataDashboardNews"=>  '<h3>¡Bienvenido a tu nuevo espacio de trabajo colaborativo!</h3>
											<h4><a href="?ctrl=file"><img src="app/img/file/iconSmall.png">Comparte tus archivos con tu equipo en el administrador de archivos</a></h4>
											<h4><a href="?ctrl=calendar"><img src="app/img/calendar/iconSmall.png">Crea eventos en tu calendario compartido o calendario personal</a></h4>
											<h4><a href="?ctrl=dashboard"><img src="app/img/dashboard/iconSmall.png">Utilice el canal de noticias para difundir información sobre su actividad</a></h4>
											<h4><a href="?ctrl=forum"><img src="app/img/messenger.png">Comunícate a través del foro, mensajería o videoconferencias</a></h4>
											<h4><a href="?ctrl=task"><img src="app/img/task/iconSmall.png">Gestiona tus tareas y proyectos para organizar tu actividad</a></h4>
											<h4><a href="?ctrl=mail"><img src="app/img/mail/iconSmall.png">Envía boletines informativos para distribuir correos electrónicos con información sobre tu actividad.</a></h4>
											<h4><a href="docs/DOCUMENTATION_FR.pdf?displayFile=true" class="lightboxOpenHref"><img src="app/img/documentation.png">Consulta el manual del usuario para descubrir tu espacio de trabajo</a></h4>
											<h4><a href="?ctrl=user&action=SendInvitation" class="lightboxOpenHref"><img src="app/img/mail.png">Enviar invitaciones por email para unirse al espacio</a></h4>',
			"INSTALL_dataDashboardPoll"=>"¿ Qué opinas de la herramienta de noticias ?",
			"INSTALL_dataDashboardPollA"=>"Muy interesante !",
			"INSTALL_dataDashboardPollB"=>"Interesante",
			"INSTALL_dataDashboardPollC"=>"Sin interés",
			"INSTALL_dataCalendarEvt"=>"Bienvenido a Omnispace",
			"INSTALL_dataForumSubject1"=>"Bienvenido al foro de Omnispace",
			"INSTALL_dataForumSubject2"=>"Siéntase libre de compartir sus preguntas o discutir los temas que deseas.",
			"INSTALL_dataTaskStatus1"=>"Por hacer",
			"INSTALL_dataTaskStatus2"=>"En curso",
			"INSTALL_dataTaskStatus3"=>"A validar",
			"INSTALL_dataTaskStatus4"=>"Terminado",

			////	MOD : AGORA
			////
			"AGORA_generalSettings"=>"Administración general",
			"AGORA_Changelog"=>"Registro de versión",
			"AGORA_phpMailDisabled"=>"Función PHP Mail deshabilitada",
			"AGORA_phpLdapDisabled"=>"Función PHP LDAP deshabilitada",
			"AGORA_phpGD2Disabled"=> "Función PHP GD2 deshabilitada",
			"AGORA_backupFull"=>"Copia de seguridad completa",
			"AGORA_backupFullTooltip"=>"Recupere la copia de seguridad completa del espacio: todos los archivos y la base de datos",
			"AGORA_backupDb"=>"Hacer una copia de seguridad de la base de datos",
			"AGORA_backupDbTooltip"=>"Recupere solo la copia de seguridad de la base de datos espacial",
			"AGORA_backupConfirm"=>"¿ Esta operación puede tardar varios minutos: ¿confirmar la descarga ?",
			"AGORA_diskSpaceInvalid"=>"El espacio en disco para los archivos debe ser un número entero",
			"AGORA_visioHostInvalid"=>"La dirección web de su servidor de videoconferencia no es válida: debe comenzar con 'https'",
			"AGORA_gApiKeyInvalid"=>"Si elige Google Map como herramienta de mapeo, debe especificar una 'API Key'",
			"AGORA_gOAuthKeyInvalid"=>"Si elige la conexión opcional a través de Google, debe especificar una 'API Key' para Google SignIn",
			"AGORA_confirmModif"=>"¿ Confirmar los cambios ?",
			"AGORA_name"=>"Nombre del espacio",
			"AGORA_nameTooltip"=>"Nombre que se muestra en la página de inicio de sesión, en correos electrónicos, etc.",
			"AGORA_description"=>"Descripción en la página de inicio de sesión",
			"AGORA_footerHtml"=>"Texto en la parte inferior izquierda de cada página",
			"AGORA_logo"=>"Logotipo en la parte inferior derecha de cada página",
			"AGORA_logoUrl"=>"URL",
			"AGORA_logoConnect"=>"logo / Imagen de la página de conexión",
			"AGORA_logoConnectTooltip"=>"Desplegado encima del formulario de conexión",
			"AGORA_lang"=>"Lenguaje por defecto",
			"AGORA_timezone"=>"Zona horaria",
			"AGORA_diskSpaceLimit"=>"Espacio de disco disponible para los archivos",
			"AGORA_logsTimeOut"=>"Duración del historial de eventos (registros)",
			"AGORA_logsTimeOutTooltip"=>"El período de retención del historial de eventos se refiere a la adición o modificación de los elementos. Los registros de eliminación se mantienen durante al menos 1 año.",
			"AGORA_visioHost"=>"Servidor de videoconferencia Jitsi",
			"AGORA_visioHostTooltip"=>"Dirección del servidor de videoconferencia Jitsi. Ejemplo: : https://framatalk.org o https://meet.jit.si",
			"AGORA_visioHostAlt"=>"Servidor de videoconferencia alternativo",
			"AGORA_visioHostAltTooltip"=>"Servidor de videoconferencia alternativo : en caso de indisponibilidad del servidor de video principal",
			"AGORA_skin"=>"Color de la interfaz",
			"AGORA_black"=>"Negro",
			"AGORA_white"=>"Blanco",
			"AGORA_userMailDisplay"=>"Direcciones de email de usuario visibles para todos",
			"AGORA_userMailDisplayTooltip"=>"Mostrar el email de cada usuario en su perfil, notificaciones por email, etc.",
			"AGORA_moduleLabelDisplay"=>"Nombre de los módulos en la barra de menú",
			"AGORA_folderDisplayMode"=>"Visualización en las carpetas",
			"AGORA_wallpaperLogoError"=>"La imagen de fondo y el logotipo debe tener el formato jpg o png",
			"AGORA_deleteWallpaper"=>"Eliminar la imagen de fondo",
			"AGORA_usersCommentLabel"=>"Botón ''Comentarios'' de los elemento",
			"AGORA_usersComment"=>"comentario",
			"AGORA_usersComments"=>"comentarios",
			"AGORA_usersLikeLabel"=>"Botón ''Me gusta'' en los artículos",
			"AGORA_usersLike"=>"Me gusta !",
			"AGORA_mapTool"=>"Herramienta de mapeo",
			"AGORA_mapToolTooltip"=>"Herramienta de mapeo para ver usuarios y contactos en un mapa",
			"AGORA_gApiKey"=>"Clave API de Google para Maps y importación de contactos",
			"AGORA_gApiKeyTooltip"=>"Configuración para Google Maps:<br> https://developers.google.com/maps/documentation/javascript/get-api-key",
			"AGORA_gOAuth"=>"Iniciar sesión a través de mi dirección de Gmail",
			"AGORA_gOAuthTooltip"=>"Los usuarios pueden conectarse más fácilmente a su espacio a través de su cuenta de Google : para eso, un email <i>@gmail.com</ i> ya debe estar registrado en la cuenta del usuario",
			"AGORA_gOAuthClientId"=>"Configuración de Sign-In : Client ID",
			"AGORA_gOAuthClientIdTooltip"=>"Esta configuración es necesaria para Google Sign-In : https://developers.google.com/identity/sign-in/web/",
			"AGORA_messengerDisplay"=>"Mensajería instantánea",
			"AGORA_personsSort"=>"Ordenar los usuarios y contactos",
			//SMTP
			"AGORA_smtpLabel"=>"Conexión SMTP & sendMail",
			"AGORA_sendmailFrom"=>"Email 'From'",
			"AGORA_sendmailFromPlaceholder"=>"eg: 'noreply@mydomain.com'",
			"AGORA_smtpHost"=>"Dirección del servidor (hostname)",
			"AGORA_smtpPort"=>"Puerto de servidor",
			"AGORA_smtpPortTooltip"=>"'25' por defecto. '587' o '465' para SSL/TLS",
			"AGORA_smtpSecure"=>"Tipo de conexión cifrada (opcional)",
			"AGORA_smtpSecureTooltip"=>"'ssl' o 'tls'",
			"AGORA_smtpUsername"=>"Nombre del usuario",
			"AGORA_smtpPass"=>"Contraseña",
			//LDAP
			"AGORA_ldapLabel"=>"Conexión a un servidor LDAP",
			"AGORA_ldapLabelTooltip"=>"Conexión a un servidor LDAP para la creación de usuarios en el espacio : cf. Opción ''Importación/exportación de usuarios'' del módulo ''Usuario''",
			"AGORA_ldapUri"=>"URI LDAP",
			"AGORA_ldapUriTooltip"=>"URI de LDAP completo con el formato LDAP://hostname:port o LDAPS://hostname:port para el cifrado SSL.",
			"AGORA_ldapPort"=>"Puerto del servidor",
			"AGORA_ldapPortTooltip"=>"El puerto utilizado para la conexión: '' 389 '' por defecto",
			"AGORA_ldapLogin"=>"DN del administrador LDAP (Distinguished Name)",
			"AGORA_ldapLoginTooltip"=>"por ejemplo ''cn=admin,dc=mon-entreprise,dc=com''",
			"AGORA_ldapPass"=>"Contraseña del administrador",
			"AGORA_ldapDn"=>"DN del grupo de usuarios (Distinguished Name)",
			"AGORA_ldapDnTooltip"=>"DN del grupo de usuarios : ubicación de los usuarios en el directorio. Ejemplo ''ou=mon-groupe,dc=mon-entreprise,dc=com''",
			"importLdapFilterTooltip"=>"Filtro de búsqueda LDAP (cf. https://www.php.net/manual/function.ldap-search.php). Ejemplo ''(cn=*)'' o ''(&(samaccountname=MONLOGIN)(cn=*))''",
			"AGORA_ldapConnectError"=>"Error de conexión del servidor LDAP !",

			////	MOD : LOG
			////
			"LOG_MODULE_DESCRIPTION"=>"Logs - Registro de eventos",
			"LOG_download"=>"Descargar el archivo de historial",
			"LOG_path"=>"Camino",
			"LOG_filterBy"=>"Filtro",
			"LOG_date"=>"Fecha",
			"LOG_moduleName"=>"Módulo",
			"LOG_objectType"=>"typo de objeto",
			"LOG_action"=>"Acción",
			"LOG_userName"=>"Usuario",
			"LOG_comment"=>"Comentario",
			"LOG_noLogs"=>"Ningún registro",
			"LOG_search"=>"Buscar",
			"LOG_connexion"=>"conexión",
			"LOG_add"=>"añadir",
			"LOG_delete"=>"eliminar",
			"LOG_modif"=>"modificación",

			////	MOD : SPACE
			////
			"SPACE_MODULE_NAME"=>"Espacios",
			"SPACE_moduleTooltip"=>"El espacio principal se puede subdividir en varios espacios (ver ''subespacio'')",
			"SPACE_manageAllSpaces"=>"Administrar todos los espacios",
			"SPACE_config"=>"Administración del espacio",
			"SPACE_space"=>"Espacio",
			"SPACE_spaces"=>"Espacios",
			"SPACE_accessRightUndefined"=>"Definir !",
			"SPACE_modules"=>"Módulos",
			"SPACE_addSpace"=>"Añadir un espacio",
			//Edit
			"SPACE_userAdminAccess"=>"Usuarios y administradores del espacio",
			"SPACE_selectModule"=>"Debe seleccionar al menos un módulo",
			"SPACE_spaceModules"=>"Módulos del espacio",
			"SPACE_publicSpace"=>"Espacio público : acceso invitado",
			"SPACE_publicSpaceTooltip"=>"Un espacio público está abierto a personas que no tengan cuenta de usuario (invitados). Podrán acceder al espacio desde la página de inicio. Se puede especificar una contraseña para proteger el acceso a este espacio público. Los módulos 'Emails' y 'Usuarios' no están disponibles para invitados.",
			"SPACE_publicSpaceNotif"=>"Tu espacio es público: si contiene datos personales (teléfono, dirección, etc.) recuerda especificar una contraseña para cumplir con el RGPD: Reglamento General de Protección de Datos",
			"SPACE_usersInvitation"=>"Los usuarios pueden enviar invitaciones por correo",
			"SPACE_usersInvitationTooltip"=>"Todos los usuarios pueden enviar invitaciones por email para unirse al espacio",
			"SPACE_allUsers"=>"Todos los usuarios",
			"SPACE_allUsersTooltip"=>"Asignar todos los usuarios al espacio",
			"SPACE_user"=>" Usuarios",
			"SPACE_userTooltip"=>"Usuario del espacio : <br> Acceso normal al espacio",
			"SPACE_admin"=>"Administrador",
			"SPACE_adminTooltip"=>"El administrador de un espacio es un usuario que puede editar o eliminar todos los elementos presentes en el espacio. También puede configurar el espacio, crear nuevas cuentas de usuario, crear grupos de usuarios, enviar invitaciones por email para añadir nuevos usuarios, etc.",

			////	MOD : USER
			////
			"USER_MODULE_NAME"=>"Usuarios",
			"USER_MODULE_DESCRIPTION"=>"Usuarios del espacio",
			"USER_OPTION_allUsersAddGroup"=>"Los usuarios también pueden crear grupos",
			"USER_spaceOrAllUsersTooltip"=>"Usuarios del espacio actual / Usuarios de todos los espacios (vista de administrador)",
			"USER_spaceUsers"=>"Administrar usuarios del espacio",
			"USER_allUsers"=>"Administrar todos los usuarios",
			"USER_deleteDefinitely"=>"Eliminar definitivamente",
			"USER_deleteFromCurSpace"=>"Desasignar al espacio actual",
			"USER_deleteFromCurSpaceConfirm"=>"¿ Desasignar el usuario del espacio actual ?",
			"USER_user"=>"Usuario",
			"USER_users"=>"usuarios",
			"USER_addExistUser"=>"Añadir un usuario existente, a ese espacio",
			"USER_addExistUserTitle"=>"Añadir al espacio a un usuario ya existente en el sitio : asignación al espacio",
			"USER_addUser"=>"Añadir un usuario",
			"USER_addUserSite"=>"Crear un usuario en el sitio : por defecto, asignado a ningun espacio !",
			"USER_addUserSpace"=>"Crear un usuario en el espacio actual",
			"USER_sendCoords"=>"Enviar el nombre de usuario y contraseña",
			"USER_sendCoordsTooltip"=>"Envíe a los usuarios un email con su Login y un enlace web para inicializar su contraseña",
			"USER_sendCoordsTooltip2"=>"Enviar a cada nuevo usuario un email con información de acceso.",
			"USER_sendCoordsConfirm"=>"¿ Confirmar ?",
			"USER_sendCoordsMail"=>"Sus datos de acceso a su espacio",
			"USER_noUser"=>"Ningún usuario asignado a este espacio por el momento",
			"USER_spaceList"=>"Espacios del usuario",
			"USER_spaceNoAffectation"=>"Ningún espacio",
			"USER_adminGeneral"=>"Administrador General del Sitio",
			"USER_adminGeneralTooltip"=>"Advertencia: el derecho de acceso de ''administrador general'' otorga muchos privilegios y responsabilidades, en particular para editar todos los elementos (calendarios, carpetas, archivos, etc.), así como todos los usuarios y espacios. Por lo tanto, es recomendable asignar este privilegio a 2 o 3 usuarios como máximo.<br><br>Para privilegios más restringidos, elija el derecho de acceso ''administrador del espacio'' (ver menú principal > ''Configurar el espacio'')",
			"USER_adminSpace"=>"Administrador del espacio",
			"USER_userSpace"=>"Usuario del espacio",
			"USER_profilEdit"=>"Editar el perfil",
			"USER_myProfilEdit"=>"Editar mi perfil de usuario",
			// Invitation
			"USER_sendInvitation"=>"Enviar invitaciones por email",
			"USER_sendInvitationTooltip"=>"Enviar invitaciones por email para unirse al espacio actual :<br> Una vez validada la invitación, se crea automáticamente una cuenta de usuario para la persona interesada.",
			"USER_mailInvitationObject"=>"Invitación de",
			"USER_mailInvitationFromSpace"=>"le invita al espacio ",
			"USER_mailInvitationConfirm"=>"Haga clic aquí para confirmar la invitación",
			"USER_mailInvitationWait"=>"Invitaciones a confirmar",
			"USER_exired_idInvitation"=>"La enlace de su invitación ha caducado",
			"USER_invitPassword"=>"Confirmar su invitación",
			"USER_invitPassword2"=>"Elejir su contraseña para confirmar su invitación",
			"USER_invitationValidated"=>"Su invitación ha sido validado !",
			"USER_gPeopleImport"=>"Obtener mis contactos de mi dirección de Gmail",
			"USER_quotaExceeded"=>"Se alcanzó la cuota de número de usuario. Por favor, póngase en contacto con el administrador del espacio.",
			"USER_importQuotaExceeded"=>"Está limitado a --USERS_QUOTA_REMAINING-- nuevas cuentas de usuario, de un total de --LIMITE_NB_USERS-- usuarios",
			// groupes
			"USER_spaceGroups"=>"Grupos de usuarios",
			"USER_spaceGroupsEdit"=>"Editar grupos de usuarios del espacio",
			"USER_groupEditInfo"=>"Lista de grupos que puedo editar: autor del grupo o administrador del espacio",
			"USER_addGroup"=>"Añadir un grupo",
			"USER_userGroups"=>"Grupos del usuario",
			// Recherche/Affectation d'users
			"USER_allUsersOnSpace"=>"Todos los usuarios están asignados al espacio",
			"USER_userAffectConfirm"=>"¿Confirmar las asignaciones?",
			"USER_addExistUser"=>"Agregar usuarios existentes",
			"USER_addExistUserTitle"=>"Asignar usuarios existentes al espacio",
			// Utilisateur_edit & CO
			"USER_langs"=>"Idioma",
			"USER_persoCalendarDisabled"=>"Calendario personal desactivado",
			"USER_persoCalendarDisabledTooltip"=>"Se asigna un calendario personal por defecto a cada usuario (incluso si el módulo ''Calendario'' no está activado en el espacio). Marque esta opción para deshabilitar el calendario personal de este usuario.",
			"USER_connectionSpace"=>"Espacio de conexión",
			"USER_loginExists"=>"El login/email ya existe ¡ Gracias a especificar otro !",
			"USER_mailPresentInAccount"=>"ya existe una cuenta de usuario con esta dirección de email",
			"USER_loginAndMailDifferent"=>"Ambas direcciones de email deben ser idénticas",
			"USER_mailNotifObject"=>"Nueva cuenta en ",
			"USER_mailNotifContent"=>"Tu cuenta de usuario ha sido creada en",
			"USER_mailNotifContent2"=>"Conectar con el login y la contraseña siguientes",
			"USER_mailNotifContent3"=>"Gracias a mantener este email para sus archivos.",
			// Edition du Livecounter/Messenger
			"USER_livecounterVisibility"=>"Visibilidad en la mensajería",
			"USER_livecounterAllUsers"=>"Mostrar mi presencia cuando estoy conectado: mensajería / video habilitado",
			"USER_livecounterDisabled"=>"Ocultar mi presencia cuando estoy conectado: mensajería / video desactivado",
			"USER_livecounterSomeUsers"=>"Solo ciertos usuarios pueden verme cuando estoy conectado",

			////	MOD : DASHBOARD
			////	
			"DASHBOARD_MODULE_NAME"=>"Noticias",
			"DASHBOARD_MODULE_DESCRIPTION"=>"Noticias, Encuestas y Elementos recientes",
			"DASHBOARD_OPTION_adminAddNews"=>"Sólo el administrador puede añadir noticias",
			"DASHBOARD_OPTION_disablePolls"=>"Deshabilitar encuestas",
			"DASHBOARD_OPTION_adminAddPoll"=>"Sólo el administrador puede añadir encuestas",
			"DASHBOARD_menuNews"=>"Noticias",
			"DASHBOARD_menuPolls"=>"Encuestas",
			"DASHBOARD_menuElems"=>"Elementos recientes y actuales",
			"DASHBOARD_addNews"=>"Añadir una noticia",
			"DASHBOARD_offlineNews"=>"Mostrar noticias archivadas",
			"DASHBOARD_offlineNewsNb"=>"noticias archivadas",
			"DASHBOARD_noNews"=>"No hay noticias por el momento",
			"DASHBOARD_addPoll"=>"Añadir una encuesta",
			"DASHBOARD_pollsVoted"=>"Mostrar solo encuestas votadas",
			"DASHBOARD_pollsVotedNb"=>"encuestas por las que ya he votado",
			"DASHBOARD_pollsNotVoted"=>"encuestas no votadas",
			"DASHBOARD_vote"=>"Votar y ver los resultados !",
			"DASHBOARD_voteTooltip"=>"Los votos son anónimos : nadie sabrá su elección de voto",
			"DASHBOARD_answerVotesNb"=>"Votada --NB_VOTES-- veces",
			"DASHBOARD_pollVotesNb"=>"La encuesta fue votada --NB_VOTES-- veces",
			"DASHBOARD_pollVotedBy"=>"Votada por",
			"DASHBOARD_noPoll"=>"No hay encuesta por el momento",
			"DASHBOARD_plugins"=>"Nuevos elementos",
			"DASHBOARD_pluginsTooltip"=>"Elementos creados",
			"DASHBOARD_pluginsTooltip2"=>"entre",
			"DASHBOARD_plugins_day"=>"de hoy",
			"DASHBOARD_plugins_week"=>"de esta semana",
			"DASHBOARD_plugins_month"=>"del mes",
			"DASHBOARD_plugins_previousConnection"=>"desde la última conexión",
			"DASHBOARD_pluginsTooltipRedir"=>"Ver el elemento en la carpeta",
			"DASHBOARD_pluginEmpty"=>"No hay nuevos elementos sobre este periodo",
			// Actualite/News
			"DASHBOARD_topNews"=>"Noticia importante",
			"DASHBOARD_topNewsTooltip"=>"Noticia importante, en la parte superior de la lista",
			"DASHBOARD_offline"=>"Noticia archivada",
			"DASHBOARD_dateOnline"=>"En línea el",
			"DASHBOARD_dateOnlineTooltip"=>"Establecer una fecha de línea automático (en línea). La noticia será 'archivada' 'en el ínterin",
			"DASHBOARD_dateOnlineNotif"=>"La noticia esta archivado en la expectativa de su línea automática",
			"DASHBOARD_dateOffline"=>"Archivar el",
			"DASHBOARD_dateOfflineTooltip"=>"Fije una fecha de archivo automático (Desconectado)",
			// Sondage/Polls
			"DASHBOARD_titleQuestion"=>"Título / Pregunta",
			"DASHBOARD_multipleResponses"=>"Varias respuestas posibles para cada voto",
			"DASHBOARD_newsDisplay"=>"Mostrar con noticias (menú izquierdo)",
			"DASHBOARD_publicVote"=>"Voto público: la elección de los votantes es pública",
			"DASHBOARD_publicVoteInfos"=>"Tenga en cuenta que la votación pública puede ser una barrera para la participación en la encuesta.",
			"DASHBOARD_dateEnd"=>"Fin de votaciones",
			"DASHBOARD_responseList"=>"Posibles respuestas",
			"DASHBOARD_responseNb"=>"Respuesta n°",
			"DASHBOARD_addResponse"=>"Añadir una respuesta",
			"DASHBOARD_controlResponseNb"=>"Por favor, especifique al menos 2 respuestas posibles",
			"DASHBOARD_votedPollNotif"=>"Atención: tan pronto como se vota la encuesta, ya no es posible cambiar el título o las respuestas",
			"DASHBOARD_voteNoResponse"=>"Por favor seleccione una respuesta",
			"DASHBOARD_exportPoll"=>"Descarga los resultados de la encuesta en pdf",
			"DASHBOARD_exportPollDate"=>"resultado de la encuesta al",

			////	MOD : FILE
			////
			"FILE_MODULE_NAME"=>"Archivos",
			"FILE_MODULE_DESCRIPTION"=>"Administración de Archivos",
			"FILE_OPTION_adminRootAddContent"=>"Sólo el administrador puede añadir elementos en el directorio raíz",
			"FILE_addFile"=>"Añadir archivos",
			"FILE_addFileAlert"=>"Los directorios del servidor no son accesible en escritura !  gracias de contactar el administrador",
			"FILE_downloadSelection"=>"Descargar selección",
			"FILE_fileDownload"=>"Descargar",
			"FILE_fileSize"=>"Tamaño del archivo",
			"FILE_imageSize"=>"Tamaño de la imagen",
			"FILE_nbFileVersions"=>"Archivo versiones",
			"FILE_downloadsNb"=>"(descargado --NB_DOWNLOAD-- veces)",
			"FILE_downloadedBy"=>"archivo subido por",
			"FILE_addFileVersion"=>"Añadir nueva versión del archivo",
			"FILE_noFile"=>"No hay archivo en este momento",
			// Edit
			"FILE_fileSizeLimit"=>"Los archivos no deben exceder",
			"FILE_uploadSimple"=>"Formulario simple",
			"FILE_uploadMultiple"=>"Formulario multiple",
			"FILE_uploadSimpleMultiple"=>"Selección de uno o varios archivos",
			"FILE_imgReduce"=>"Optimizar la imagen",
			"FILE_updatedName"=>"El nombre del archivo será reemplazado por la nueva versión",
			"FILE_fileSizeError"=>"Archivo demasiado grande",
			"FILE_addMultipleFilesTooltip"=>"máximo por archivo. Seleccione varios archivos usando la tecla <i>Ctrl</i>.",
			"FILE_selectFile"=>"Gracias por elegir al menos un archivo",
			"FILE_fileContent"=>"contenido",
			// Versions
			"FILE_versionsOf"=>"Versiones de",
			"FILE_confirmDeleteVersion"=>"¿ Confirme la eliminación de esta versión ?",

			////	MOD : CALENDAR
			////
			"CALENDAR_MODULE_NAME"=>"Calendarios",
			"CALENDAR_MODULE_DESCRIPTION"=>"Calendarios personal y calendarios compartidos",
			"CALENDAR_OPTION_adminAddRessourceCalendar"=>"Sólo el administrador puede añadir calendarios de recursos",
			"CALENDAR_OPTION_adminAddCategory"=>"Sólo el administrador puede añadir categorías de eventos",
			"CALENDAR_OPTION_createSpaceCalendar"=>"Crear un calendario compartido para el espacio",
			"CALENDAR_CAT_menuTooltip"=>"Mostrar solo eventos con categoría",
			"CALENDAR_CAT_showAll"=>"Toda las categorías",
			"CALENDAR_CAT_showAllTooltip"=>"Mostrar toda las categorías",
			"CALENDAR_CAT_undefined"=>"Sin categoría",
			"CALENDAR_CAT_editTitle"=>"Editar las categorías",
			"CALENDAR_CAT_editInfo"=>"Cada categoría de evento puede ser modificada por su autor o por el administrador general",
			"CALENDAR_CAT_editAdd"=>"Añadir una categoría de evento",
			"CALENDAR_moduleAlwaysEnabledInfo"=>"Los usuarios que no hayan desactivado su calendario personal en su perfil de usuario seguirán viendo el módulo Calendario en la barra de menú.",
			"CALENDAR_readableCalendars"=>"Calendarios disponibles",
			"CALENDAR_hideAllCals"=>"Ocultar todo los calendarios",
			"CALENDAR_printCalendars"=>"Imprimir el/los calendarios",
			"CALENDAR_printCalendarsInfos"=>"imprimir la página en modo horizontal",
			"CALENDAR_addSharedCalendar"=>"Añadir un calendario compartido",
			"CALENDAR_addSharedCalendarTooltip"=>"Añadir un calendario compartido : para reservar une habitación, vehiculo, vídeo, etc.",
			"CALENDAR_exportIcal"=>"Exportar los eventos (iCal)",
			"CALENDAR_icalUrl"=>"Copie la dirección web (URL) para mostrar el calendario desde un calendario externo",
			"CALENDAR_icalUrlCopy"=>"Permite el acceso de lectura al calendario desde un calendario externo como Thunderbird, Outlook, Google Calendar, etc.",
			"CALENDAR_importIcal"=>"Importar los eventos (iCal)",
			"CALENDAR_importIgnoreOldEvt"=>"No importe eventos de más de un año",
			"CALENDAR_importEvtPresent"=>"Ya está presente",
			"CALENDAR_importEvtPresentInfo"=>"Evento ya presente en el calendario ?",
			"CALENDAR_display_1Day"=>"1 día",
			"CALENDAR_display_3Days"=>"3 días",
			"CALENDAR_display_7Days"=>"7 días",
			"CALENDAR_display_week"=>"Semana",
			"CALENDAR_display_workWeek"=>"Semana de trabajo",
			"CALENDAR_display_month"=>"Mes",
			"CALENDAR_yearWeekNum"=>"Ver la semana n°",
			"CALENDAR_periodNext"=>"Período siguiente",
			"CALENDAR_periodPrev"=>"Período anterior",
			"CALENDAR_evtAffects"=>"En el calendario de",
			"CALENDAR_evtAffectToConfirm"=>"Pendiente en el calendario de",
			"CALENDAR_evtProposition"=>"Propuesto de eventos a confirmar",
			"CALENDAR_evtProposedBy"=>"Propuestos por",
			"CALENDAR_evtProposeConfirm"=>"Confirma la propuesta",
			"CALENDAR_evtProposeConfirmed"=>"La propuesta del evento se ha integrado en la agenda",
			"CALENDAR_evtProposeConfirmedMail"=>"Tu propuesta de evento ha sido confirmada",
			"CALENDAR_evtProposeDecline"=>"Rechazar la propuesta",
			"CALENDAR_evtProposeDeclined"=>"La propuesta ha sido rechazada",
			"CALENDAR_evtProposeDeclinedMail"=>"Tu propuesta de evento ha sido rechazada",
			"CALENDAR_evtDelete"=>"Eliminar evento",
			"CALENDAR_evtDeleteCal"=>"Eliminar el evento de este calendario",
			"CALENDAR_evtDeleteDate"=>"Eliminar el evento en esta fecha",
			"CALENDAR_evtPrivate"=>"Évento privado",
			"CALENDAR_evtAutor"=>"Eventos que he creado",
			"CALENDAR_evtAutorInfo"=>"Mostrar solo eventos que he creado",
			"CALENDAR_evtAutorSortCrea"=>"Ordenar por fecha de creación (desc)",
			"CALENDAR_evtAutorSortBegin"=>"Ordenar por fecha de inicio del evento (desc)",
			"CALENDAR_evtChangeTime"=>"¿ Mover a",
			"CALENDAR_evtChangeTimeConfirmed"=>"El evento se ha movido correctamente",
			"CALENDAR_noEvt"=>"No hay eventos",
			"CALENDAR_noCalendarDisplayed"=>"No calendario",
			// Evenement
			"CALENDAR_importanceNormal"=>"Importancia normal",
			"CALENDAR_importanceHight"=>"Alta importancia",
			"CALENDAR_visibilityPublic"=>"Visibilidad normal",
			"CALENDAR_visibilityPublicHide"=>"Visibilidad de franja horaria",
			"CALENDAR_visibilityPrivate"=>"Visibilidad privada",
			"CALENDAR_visibilityTooltip"=>"Para personas que solo tienen acceso de lectura al calendario: <br>- Visibilidad de franja horaria : muestra solo la franja horaria ocupada por el evento y oculta los detalles<br>- Visualización privada: no muestra el evento",
			// Edit
			"CALENDAR_sharedCalendarDescription"=>"Calendario compartido del espacio",
			"CALENDAR_noRepeat"=>"Una vez",
			"CALENDAR_period_weekDay"=>"Cada semana",
			"CALENDAR_period_month"=>"Todos los meses",
			"CALENDAR_period_monthDetail"=>"Cada --DATE-- del mes",
			"CALENDAR_period_year"=>"Todos los años",
			"CALENDAR_period_yearDetail"=>"Cada --DATE-- del año",
			"CALENDAR_periodDateExceptions"=>"Fecha de excepción de repetición",
			"CALENDAR_periodDateEnd"=>"Fecha de fin de repetición",
			"CALENDAR_calendarAffectations"=>"Asignación a los calendarios",
			"CALENDAR_addEvt"=>"Añadir un evento",
			"CALENDAR_addEvtTooltip"=>"Añadir un evento",
			"CALENDAR_addEvtTooltip2"=>"Añadir el evento al calendario",
			"CALENDAR_proposeEvtTooltip"=>"Proponer un evento para este calendario en lectura : Luego validado por el propietario del calendario",
			"CALENDAR_proposeOptionTooltip"=>"Opción de proponer el evento : Luego validado por el propietario del calendario",
			"CALENDAR_verifCalNb"=>"Gracias por seleccionar por lo menos un calendario",
			"CALENDAR_busyTimeSlot"=>"La ranura ya está ocupado en este calendario :",
			"CALENDAR_timeSlot"=>"Rango de tiempo de la pantalla ''semana''",
			"CALENDAR_propositionNotif"=>"Notificar por email de cada propuesta de evento",
			"CALENDAR_propositionNotifTooltip"=>"Nota: Cada propuesta de evento es validada o invalidada por el administrador del calendario.",
			"CALENDAR_propositionGuest"=>"Los invitados pueden proponer eventos",
			"CALENDAR_propositionGuestTooltip"=>"Nota: Recuerde seleccionar 'todos los usuarios e invitados' en los derechos de acceso.",
			"CALENDAR_propositionEmailSubject"=>"Nuevo evento propuesto por",
			"CALENDAR_propositionEmailMessage"=>"Nuevo evento propuesto por --AUTOR_LABEL-- : &nbsp; <i><b>--EVT_TITLE_DATE--</b></i> <br><i>--EVT_DESCRIPTION--</i> <br>Accede a tu espacio para confirmar o cancelar esta propuesta",

			////	MOD : FORUM
			////
			"FORUM_MODULE_NAME"=>"Foro",
			"FORUM_MODULE_DESCRIPTION"=>"Foro",
			"FORUM_OPTION_adminAddSubject"=>"Sólo el administrador puede añadir sujetos",
			"FORUM_OPTION_adminAddTheme"=>"Sólo el administrador puede añadir temas",
			"FORUM_CAT_menuTooltip"=>"Mostrar solo sujetos con tema",
			"FORUM_CAT_showAll"=>"Todo los temas",
			"FORUM_CAT_showAllTooltip"=>"Mostrar todo los temas",
			"FORUM_CAT_undefined"=>"Sin tema",
			"FORUM_CAT_editTitle"=>"Editar los temas",
			"FORUM_CAT_editInfo"=>"Cada tema puede ser modificado por su autor o por el administrador general",
			"FORUM_CAT_editAdd"=>"Añadir un tema",
			"SORT_dateLastMessage"=>"último mensaje",
			"FORUM_forumRoot"=>"Inicio del foro",
			"FORUM_subject"=>"sujeto",
			"FORUM_subjects"=>"sujetos",
			"FORUM_message"=>"mensaje",
			"FORUM_messages"=>"mensajes",
			"FORUM_lastMessageFrom"=>"ultimo de",
			"FORUM_noSubject"=>"Sin sujeto por el momento",
			"FORUM_subjectBy"=>"sujeto de",
			"FORUM_addSubject"=>"Nuevo sujeto",
			"FORUM_displaySubject"=>"Ver el sujeto",
			"FORUM_addMessage"=>"Responder",
			"FORUM_quoteMessage"=>"Responder",
			"FORUM_quoteMessageInfo"=>"Responder y citar a ese mensaje",
			"FORUM_notifyLastPost"=>"Notificar por email",
			"FORUM_notifyLastPostTooltip"=>"Deseo recibir una notificación por correo a cada nuevo mensaje",
			"FORUM_notifOnlyReadAccess"=>"Si solo hay acceso de lectura, nadie puede contribuir al tema.",
			"FORUM_notifWriteAccess"=>"El acceso de ''escritura'' está destinado a los moderadores :<br>Si es necesario, prefiera los derechos de ''escritura limitada''",

			////	MOD : TASK
			////
			"TASK_MODULE_NAME"=>"Tareas",
			"TASK_MODULE_DESCRIPTION"=>"Tareas",
			"TASK_OPTION_adminRootAddContent"=>"Sólo el administrador puede añadir elementos en el directorio raíz",
			"TASK_OPTION_adminAddStatus"=>"Sólo el administrador puede crear status Kanban",
			"TASK_CAT_menuTooltip"=>"Mostrar solo tareas con estado",
			"TASK_CAT_showAll"=>"Todos los estados",
			"TASK_CAT_showAllTooltip"=>"Mostrar todos los estados",
			"TASK_CAT_undefined"=>"Estado indefinido",
			"TASK_CAT_editTitle"=>"Editar los estados",
			"TASK_CAT_editInfo"=>"Cada estado puede ser modificado por su autor o por el administrador general.",
			"TASK_CAT_editAdd"=>"Añadir un estado",
			"SORT_priority"=>"Prioridad",
			"SORT_advancement"=>"Progreso",
			"SORT_dateBegin"=>"Fecha de inicio",
			"SORT_dateEnd"=>"Fecha de fin",
			"TASK_addTask"=>"Añadir una tareas",
			"TASK_noTask"=>"No hay tarea por el momento",
			"TASK_advancement"=>"Progreso",
			"TASK_advancementAverage"=>"Progreso promedio",
			"TASK_priority"=>"Prioridad",
			"TASK_priorityUndefined"=>"Prioridad indefinida",
			"TASK_priority1"=>"Baja",
			"TASK_priority2"=>"promedia",
			"TASK_priority3"=>"alta",
			"TASK_assignedTo"=>"Asignado a",
			"TASK_advancementDelayed"=>"Progreso retrasado",
			"TASK_folderDateBeginEnd"=>"Fecha de inicio más temprana / de fin más reciente",

			////	MOD : CONTACT
			////
			"CONTACT_MODULE_NAME"=>"Contactos",
			"CONTACT_MODULE_DESCRIPTION"=>"Directorio de contactos",
			"CONTACT_OPTION_adminRootAddContent"=>"Sólo el administrador puede añadir elementos en el directorio raíz",
			"CONTACT_addContact"=>"Añadir un contacto",
			"CONTACT_noContact"=>"No hay contacto todavía",
			"CONTACT_createUser"=>"Crear un usuario en este espacio",
			"CONTACT_createUserConfirm"=>"¿ Crear un usuario en este espacio con este contacto ?",
			"CONTACT_createUserConfirmed"=>"El usuario fue creado",

			////	MOD : LINK
			////
			"LINK_MODULE_NAME"=>"Favoritos",
			"LINK_MODULE_DESCRIPTION"=>"Favoritos",
			"LINK_OPTION_adminRootAddContent"=>"Sólo el administrador puede añadir elementos en el directorio raíz",
			"LINK_addLink"=>"Añadir un enlace",
			"LINK_noLink"=>"No hay enlaces por el momento",
			"LINK_adress"=>"Dirección web",

			////	MOD : MAIL
			////
			"MAIL_MODULE_NAME"=>"Emails",
			"MAIL_MODULE_DESCRIPTION"=>"Enviar mensajes de email con un solo clic !",
			"MAIL_specifyMail"=>"Gracias especificar al menos un destinatario",
			"MAIL_title"=>"Asunto del email",
			"MAIL_description"=>"Mensaje del email",
			"MAIL_historyTitle"=>"Historia de los correos electrónicos enviados",
			"MAIL_delete"=>"Eliminar este email",
			"MAIL_resend"=>"Reenviar este email",
			"MAIL_resendInfo"=>"Recupere el contenido de este email e intégrelo directamente en el editor para un nuevo envío",
			"MAIL_historyEmpty"=>"No email",
		);
	}

	/*
	 * Jours Fériés de l'année
	 */
	public static function publicHolidays($year)
	{
		$dateList[$year."-01-01"]="Año Nuevo";
		$dateList[$year."-01-06"]="Día de Reyes";
		$dateList[$year."-05-01"]="Día del Trabajador";
		$dateList[$year."-08-15"]="Asunción";
		$dateList[$year."-10-12"]="Fiesta Nacional de España";
		$dateList[$year."-11-01"]="Día de todos los Santos";
		$dateList[$year."-12-06"]="Día de la Constitución";
		$dateList[$year."-12-08"]="Inmaculada Concepción";
		$dateList[$year."-12-25"]="Navidad";
		$dateList[$year."-12-26"]="Sant Esteve";
		if(function_exists("easter_date")){
			$easterTime=easter_date($year);
			$dateList[date('Y-m-d',strtotime("-3 days",$easterTime))]	="Jueves Santo";
			$dateList[date('Y-m-d',strtotime("-2 days",$easterTime))]	="Viernes Santo";
			$dateList[date('Y-m-d',$easterTime)]						="Pascua";
			$dateList[date('Y-m-d',strtotime("+1 days",$easterTime))]	="Lunes de Pascua";
		}
		$tmpDates=Txt::timeChangeDates($year);
		$dateList[$tmpDates["summer"]]="Horario de verano";
		$dateList[$tmpDates["winter"]]="Horario de invierno";
		return $dateList;
	}
}