<?php
/*
 * Traductions
 */
class Trad extends Txt
{
	/*
	 * Chargement les elements de traduction
	 */
	public static function loadTrads()
	{
		////	Dates formatées par PHP
		setlocale(LC_TIME, "fr_FR.utf8", "fr_FR.UTF-8", "fr_FR", "fr", "french");

		////	TRADUCTIONS
		self::$trad=array(
			////	Langue de l'appli, des dates et de l'éditeur
			"CURLANG"=>"fr",
			"DATELANG"=>"fr_FR",
			"EDITORLANG"=>"fr_FR",
			"FANCYBOXLANG"=>"fr",

			////	Divers
			"mainMenu"=>"Menu principal",
			"menuOptions"=>"Menu des options",
			"emptyFields"=>"Merci de remplir les champs du formulaire",
			"requiredFields"=>"Merci de remplir le champ",
			"inaccessibleElem"=>"L'élément demandé n'est pas accessible",
			"warning"=>"Attention",
			"elemEditedByAnotherUser"=>"Attention : cet élément est actuellement édité par",
			"yes"=>"oui",
			"no"=>"non",
			"none"=>"aucun",
			"or"=>"ou",
			"and"=>"et",
			"goToPage"=>"Aller à la page",
			"alphabetFilter"=>"Filtre alphabétique",
			"displayAll"=>"Tout afficher",
			"show"=>"Afficher",
			"hide"=>"Masquer",
			"byDefault"=>"Par défaut",
			"changeOrder"=>"Déplacer pour modifier l'ordre d'affichage",
			"mapLocalize"=>"Afficher sur une carte",
			"mapLocalizationFailure"=>"Echec de la localisation de l'adresse suivante",
			"mapLocalizationFailure2"=>"Merci de vérifier que l'adresse existe bien sur www.google.fr/maps ou www.openstreetmap.org",
			"sendMail"=>"Envoyer un email",
			"sendMailTo"=>"Envoyer un email à",
			"mailInvalid"=>"L'email n'est pas valide",
			"element"=>"élément",
			"elements"=>"éléments",
			"folder"=>"dossier",
			"folders"=>"dossiers",
			"close"=>"Fermer",
			"modifRecorded"=>"Les modifications ont bien été enregistrées",
			"comment"=>"Commentaire",
			"commentAdd"=>"Ajouter un commentaire",
			"optional"=>"(optionnel)",
			"objNew"=>"Nouvel élément",
			"objNewTooltip"=>"Créé aujourd'hui ou depuis ma précédente connexion",
			"personalAccess"=>"Accès personnel",
			"copyUrl"=>"Copier l'URL de partage",
			"copyUrlTooltip"=>"Permet d'accéder à l'élément depuis un email, un blog, etc.",
			"copyUrlNotif"=>"L'URL a bien été copiée",

			////	Confirm et Suppression
			"confirm"=>"Confirmer",
			"confirmOk"=>"Ok",
			"confirmCancel"=>"Annuler",
			"confirmDownload"=>"Télécharger le fichier ?",
			"confirmCloseForm"=>"Fermer le formulaire sans enregistrer ?",
			"delete"=>"Supprimer",
			"confirmDelete"=>"Confirmer la suppression ?",
			"confirmDeleteAlert"=>"suppression permanente",
			"confirmDeleteNotify"=>"La suppression a bien été effectuée",
			"confirmDeleteSelect"=>"Confirmer la suppression définitive des éléments sélectionnés ?",
			"confirmDeleteSelectNb"=>"éléments sélectionnés",
			"confirmDeleteFolder"=>"Certains sous-dossiers ne vous sont pas accessibles en lecture : confirmer tout de même ?",
			"confirmDeleteWait"=>"Merci de patienter un instant : la suppression du dossier peut prendre quelques secondes",
			"notifDeleteFolderUncomplete"=>"Certains éléments n'ont pas été supprimé car vous n'avez pas les droits d'accès nécessaires",

			////	Images
			"picture"=>"Photo",
			"pictureProfil"=>"Photo de profil",
			"wallpaper"=>"Fond d'écran",
			"keepImg"=>"Conserver l'image",
			"changeImg"=>"Changer l'image",
			"pixels"=>"pixels",

			////	Connexion
			"specifyLoginPassword"=>"Merci de spécifier un identifiant et un mot de passe",
			"specifyLogin"=>"Merci de spécifier un email/identifiant (sans espaces)",
			"mailLloginNotif"=>"Il est conseillé d'utiliser un email comme identifiant de connexion",
			"mailLlogin"=>"Email / Identifiant de connexion",
			"connect"=>"Connexion",
			"connectAuto"=>"Rester connecté",
			"connectAutoTooltip"=>"Mémoriser mes identifiants pour une connexion automatique",
			"gOAuthUserUnknown"=>"n'est pas enregistré sur l'espace",
			"connectSpaceSwitch"=>"Changer d'espace Omnispace",
			"guestAccess"=>"Connexion invité",
			"guestAccessTooltip"=>"Me connecter à cet espace en tant qu'invité",
			"publicSpacePasswordError"=>"Mot de passe erroné",
			"disconnectSpace"=>"Me déconnecter de l'espace",
			"disconnectSpaceConfirm"=>"Me déconnecter de l'espace ?",

			////	Password : connexion d'user / edition d'user / reset du password
			"password"=>"Mot de passe",
			"passwordModify"=>"Modifier le mot de passe",
			"passwordToModify"=>"Mot de passe temporaire (à modifier en page de connexion)",
			"passwordToModify2"=>"Mot de passe (à modifier si besoin sur votre profil utilisateur)",
			"passwordVerif"=>"Confirmer le mot de passe",
			"passwordTooltip"=>"Remplir les champs uniquement si vous souhaitez changer de mot de passe",
			"passwordInvalid"=>"Le mot de passe doit comporter 6 caractères minimum, avec au moins une majuscule, une minuscule et un chiffre",
			"passwordVerifError"=>"Votre confirmation de mot de passe n'est pas valide",
			"specifyPassword"=>"Merci de spécifier un mot de passe",
			"resetPassword"=>"Mot de passe oublié ?",
			"resetPassword2"=>"Indiquez votre adresse email pour réinitialiser votre mot de passe de connection",
			"resetPasswordNotif"=>"Un email vient de vous être envoyé pour réinitialiser votre mot de passe. Si vous ne l'avez pas reçu, vérifiez que votre email a correctement été saisi.",
			"resetPasswordMailTitle"=>"Réinitialiser votre mot de passe",
			"resetPasswordMailPassword"=>"Pour réinitialiser votre mot de passe et vous reconnecter",
			"resetPasswordMailPassword2"=>"merci de cliquer ici",
			"resetPasswordMailLoginRemind"=>"Rappel de votre identifiant de connexion",
			"resetPasswordIdExpired"=>"Le lien pour régénérer le mot de passe a expiré. Merci de recommencer la procédure",

			////	Type d'affichage
			"displayMode"=>"Affichage",
			"displayMode_line"=>"Lignes",
			"displayMode_block"=>"Blocs",
			
			////	Sélectionner / Déselectionner tous les éléments
			"select"=>"Sélectionner",
			"selectUnselect"=>"Sélectionner / Déselectionner",
			"selectAll"=>"Tout sélectionner",
			"selectNone"=>"Tout désélectionner",
			"selectSwitch"=>"Inverser la sélection",
			"deleteElems"=>"Supprimer la sélection",
			"changeFolder"=>"Déplacer vers un autre dossier",
			"showOnMap"=>"Voir les contacts sur une carte",
			"showOnMapTooltip"=>"Voir sur une carte les contacts avec une adresse, un code postal et une ville",
			"notifSelectUser"=>"Merci de sélectionner au moins un utilisateur",
			"notifSelectUsers"=>"Merci de sélectionner au moins 2 utilisateurs",
			"selectSpace"=>"Merci de sélectionner au moins un espace",
			"visibleAllSpaces"=>"Disponible sur tous les espaces",
			"visibleOnSpace"=>"Disponible sur l'espace",
			
			////	Temps ("de 11h à 12h", "le 25-01-2007 à 10h30", etc.)
			"from"=>"de",
			"at"=>"à",
			"begin"=>"Début",
			"end"=>"Fin",
			"beginEnd"=>"Début / Fin",
			"days"=>"jours",
			"day_1"=>"Lundi",
			"day_2"=>"Mardi",
			"day_3"=>"Mercredi",
			"day_4"=>"Jeudi",
			"day_5"=>"Vendredi",
			"day_6"=>"Samedi",
			"day_7"=>"Dimanche",
			"month_1"=>"janvier",
			"month_2"=>"fevrier",
			"month_3"=>"mars",
			"month_4"=>"avril",
			"month_5"=>"mai",
			"month_6"=>"juin",
			"month_7"=>"juillet",
			"month_8"=>"aout",
			"month_9"=>"septembre",
			"month_10"=>"octobre",
			"month_11"=>"novembre",
			"month_12"=>"décembre",
			"today"=>"aujourd'hui",
			"displayToday"=>"Afficher aujourd'hui",
			"beginEndError"=>"La date de fin ne peut précéder la date de début",
			"dateFormatError"=>"La date doit être au format jj/mm/AAAA",
			"timeFormatError"=>"L'heure doit être au format HH:mm",
			
			////	Menus d'édition des objets et editeur tinyMce
			"title"=>"Titre",
			"name"=>"Nom",
			"description"=>"Description",
			"specifyName"=>"Merci de spécifier un nom",
			"editorDraft"=>"Rétablir mon texte",
			"editorDraftConfirm"=>"Récuperer le dernier texte saisi dans l'éditeur",
			"editorFileInsert"=>"Ajouter une image ou vidéo",
			"editorFileInsertNotif"=>"Merci de sélectionner une image au format jpg, png, gif ou une vidéo au format mp4 ou webm",
			
			////	Validation des formulaires
			"add"=>"Ajouter",
			"modify"=>"Modifier",
			"record"=>"Enregistrer",
			"modifyAndAccesRight"=>"Modifier l'élément et ses droits d'accès",
			"validate"=>"Valider",
			"send"=>"Envoyer",
			"sendTo"=>"Envoyer à",

			////	Tri d'affichage. Tous les éléments (dossier, tâche, lien, etc...) ont par défaut une date, un auteur & une description
			"sortBy"=>"Trié par",
			"sortBy2"=>"Trier par",
			"SORT_dateCrea"=>"date de création",
			"SORT_dateModif"=>"date de modif",
			"SORT_title"=>"titre",
			"SORT_description"=>"description",
			"SORT__idUser"=>"auteur",
			"SORT_extension"=>"type de fichier",
			"SORT_octetSize"=>"taille",
			"SORT_downloadsNb"=>"nb de téléchargements",
			"SORT_civility"=>"civilité",
			"SORT_name"=>"nom",
			"SORT_firstName"=>"prénom",
			"SORT_adress"=>"adresse",
			"SORT_postalCode"=>"code postal",
			"SORT_city"=>"ville",
			"SORT_country"=>"pays",
			"SORT_function"=>"fonction",
			"SORT_companyOrganization"=>"société / organisme",
			"SORT_lastConnection"=>"dernière connexion",
			"SORT_ascend"=>"Ascendant",
			"SORT_descend"=>"Descendant",

			////	Visibilité d'un Objet
			"guest"=>"invité",
			"createdBy"=>"Créé par",
			"modifBy"=>"Modifié par",
			"objHistory"=>"Historique de l'élément",
			"all"=>"tous",
			"deletedUser"=>"Ancien compte utilisateur",
			"folderContent"=>"contenu",
			"accessRead"=>"Lecture",
			"accessReadTooltip"=>"Accès en lecture",
			"accessWriteLimit"=>"Ecriture limitée",
			"accessWriteLimitTooltip"=>"Accès en écriture limité : chaque utilisateur ne peut modifier ou supprimer que les -OBJCONTENT-s qu'il a créé dans ce/cet --OBJLABEL--.",//"Ce dossier"/"cet agenda"
			"accessWrite"=>"Ecriture",
			"accessWriteTooltip"=>"Accès en écriture",
			"accessWriteTooltipContainer"=>"Accès en écriture : possibilité de modifier ou supprimer tous les -OBJCONTENT-s dans ce/cet --OBJLABEL--",//"Ce dossier"/"cet agenda"
			"accessAutorPrivilege"=>"Seul l'auteur et les administrateurs peuvent modifier ou supprimer ce/cet --OBJLABEL--",//"Ce dossier"/"cet agenda"
			"accessRightsInherited"=>"Droits d'accès hérités du --OBJLABEL-- parent",
			"categoryNotifSpaceAccess"=>"n'est accessible que sur l'espace",
			"categoryNotifChangeOrder"=>"L'ordre d'affichage a bien été modifié",

			////	Libellé des objets (cf. "MdlObject::objectType")
			"OBJECTcontainer"=>"conteneur",
			"OBJECTelement"=>"élément",
			"OBJECTfolder"=>"dossier",
			"OBJECTdashboardNews"=>"actualité",
			"OBJECTdashboardPoll"=>"sondage",
			"OBJECTfile"=>"fichier",
			"OBJECTfileFolder"=>"dossier de fichiers",
			"OBJECTcalendar"=>"agenda",
			"OBJECTcalendarEvent"=>"événement",
			"OBJECTforumSubject"=>"sujet du forum",
			"OBJECTforumMessage"=>"message du forum",
			"OBJECTcontact"=>"contact",
			"OBJECTcontactFolder"=>"dossier de contacts",
			"OBJECTlink"=>"favori",
			"OBJECTlinkFolder"=>"dossier de favoris",
			"OBJECTtask"=>"tâche",
			"OBJECTtaskFolder"=>"dossier de tâches",
			"OBJECTuser"=>"utilisateur",
			"OBJECTmail"=>"email",

			////	Envoi d'un email
			"MAIL_sendOk"=>"L'email a bien été envoyé",
			"MAIL_sendNotOk"=>"L'email n'a pas pu être envoyé",
			"MAIL_recipients"=>"Destinataires",
			"MAIL_hello"=>"Bonjour",
			"MAIL_hideRecipients"=>"Masquer les destinataires",
			"MAIL_hideRecipientsTooltip"=>"Mettre tous les destinataires en copie caché",
			"MAIL_addReplyTo"=>"Mettre mon email en réponse",
			"MAIL_addReplyToTooltip"=>"Ajouter mon email dans le champ ''Répondre à'' <br><span style='font-size:1.5em'>&#9888;</span> Attention : avec cette option les emails peuvent arriver en spam sur certaines messageries",
			"MAIL_noFooter"=>"Ne pas signer le message",
			"MAIL_noFooterTooltip"=>"Ne pas signer la fin du message : nom de l'expéditeur et lien vers l'espace",
			"MAIL_receptionNotif"=>"Accusé de reception",
			"MAIL_receptionNotifTooltip"=>"Demander un accusé de réception à l'ouverture de l'email <br><span style='font-size:1.5em'>&#9888;</span> Attention : de nombreuses messageries ne prennent pas en charge cette fonctionnalité",
			"MAIL_specificMails"=>"Ajouter des adresses email",
			"MAIL_specificMailsTooltip"=>"Ajouter des adresses email non répertoriées sur l'espace",
			"MAIL_maxFileSizeConfirm"=>"L'ensemble des fichiers joints dépasse la limite de réception de certaines boites mails (--MAXFILESSIZE--)<br><br> Envoyer tout de même ?",
			"MAIL_maxFileSizeNotif"=>"Le fichier suivant n'a pas été ajouté à l'email car il est trop volumineux",
			"MAIL_sendMail"=>"Envoyer l'email",
			"MAIL_sendBy"=>"Envoyé par",
			"MAIL_sendNotif"=>"L'email de notification a bien été envoyé",
			"MAIL_fromTheSpace"=>"depuis l'espace",
			"MAIL_elemCreatedBy"=>"--OBJLABEL-- créé(e) par",
			"MAIL_elemModifiedBy"=>"--OBJLABEL-- modifié(e) par",
			"MAIL_elemAccessLink"=>"Voir sur mon espace",
			
			////	Dossier & fichier
			"gigaOctet"=>"Go",
			"megaOctet"=>"Mo",
			"kiloOctet"=>"Ko",
			"rootFolder"=>"Dossier principal",
			"rootFolderTooltip"=>"Pour modifier les droits d'accès du dossier principal, rendez-vous dans le menu ''Parametrer l'espace''",
			"addFolder"=>"Ajouter un dossier",
			"download"=>"Télécharger le fichier",
			"downloadFolder"=>"Télécharger le dossier",
			"diskSpaceUsed"=>"Espace disque utilisé",
			"diskSpaceUsedModFile"=>"Espace disque utilisé sur le module fichier",
			"downloadAlert"=>"Votre archive est trop volumineuse pour être téléchargée en journée (--ARCHIVE_SIZE--). Merci de relancer le download à partir de",
			"downloadBackToApp"=>"Retour à l'application",

			////	Infos sur une personne
			"civility"=>"Civilité",
			"name"=>"Nom",
			"firstName"=>"Prénom",
			"adress"=>"Adresse",
			"postalCode"=>"Code postal",
			"city"=>"Ville",
			"country"=>"Pays",
			"telephone"=>"Téléphone",
			"telmobile"=>"Tél. mobile",
			"mail"=>"Email",
			"function"=>"Fonction",
			"companyOrganization"=>"Organisme / Société",
			"lastConnection"=>"Dernière connexion",
			"notConnected"=>"Pas encore connecté",
			"connectedToday"=>"Connecté aujourd'hui",
			"connectedThe"=>"Connecté le",
			"displayProfil"=>"Afficher le profil",

			////	Captcha
			"captcha"=>"Recopier les 5 caracteres",
			"captchaTooltip"=>"Merci de recopier les 5 caractères pour votre identification",
			"captchaError"=>"L'identification visuelle est erronée (5 caractères du captcha)",
			
			////	Rechercher
			"searchSpecifyText"=>"Merci de préciser au moins 3 caractères (alphanumériques et sans caractères spéciaux)",
			"search"=>"Rechercher",
			"searchOnSpace"=>"Rechercher sur l'espace",
			"searchDateCrea"=>"Date de création",
			"searchDateCreaDay"=>"moins d'un jour",
			"searchDateCreaWeek"=>"moins d'une semaine",
			"searchDateCreaMonth"=>"moins d'un mois",
			"searchDateCreaYear"=>"moins d'un an",
			"advancedSearch"=>"Recherche avancée",
			"advancedSearchAnyWord"=>"n'importe quel mot",
			"advancedSearchAllWords"=>"tous les mots",
			"advancedSearchExactPhrase"=>"l'expression exacte",
			"keywords"=>"Mots clés",
			"listModules"=>"Modules",
			"listFields"=>"Champs",
			"listFieldsElems"=>"Eléments concernés",
			"noResults"=>"Aucun résultat",

			////	Inscription d'utilisateur
			"userInscription"=>"M'inscrire à cet espace",
			"userInscriptionTooltip"=>"Envoyer une demande d'inscription pour obtenir un compte utilisateur.<br>Une fois validé par un administrateur, une confirmation vous sera envoyée par email.",
			"userInscriptionSpace"=>"M'inscrire sur l'espace",
			"userInscriptionRecorded"=>"votre inscription a bien été enregistrée : elle sera validée dès que possible par l'administrateur de l'espace",
			"userInscriptionEmailSubject"=>"Nouvelle inscription sur l'espace",
			"userInscriptionEmailMessage"=>"Une nouvelle inscription a été demandée par <i>--NEW_USER_LABEL--</i> pour l'espace <i>--SPACE_NAME--</i> : <br><br><i>--NEW_USER_MESSAGE--<i> <br><br>Pensez à confirmer ou annuler cette inscription lors de votre prochaine connexion.",
			"userInscriptionEdit"=>"Formulaire d'inscription en page de connexion",
			"userInscriptionEditTooltip"=>"Les visiteurs peuvent demander à s'inscrire sur l'espace pour avoir un compte utilisateur&nbsp;: la demande est ensuite validée par l'administrateur de l'espace",
			"userInscriptionNotif"=>"Me notifier par email à chaque inscription",
			"userInscriptionNotifTooltip"=>"Envoyer une notification par mail aux administrateurs de l'espace après chaque inscription",
			"userInscriptionValidate"=>"Valider les demandes d'inscription",
			"userInscriptionValidateTooltip"=>"Valider les demandes d'inscription à l'espace",
			"userInscriptionSelectValidate"=>"Valider les inscriptions sélectionnées",
			"userInscriptionSelectInvalidate"=>"Invalider les inscriptions sélectionnées",
			"userInscriptionInvalidateMail"=>"Désolé mais votre inscription n'a pas été validée sur",

			////	Importer ou Exporter : Contact OU Utilisateurs
			"importExport_user"=>"Importer / Exporter des utilisateurs",
			"import_user"=>"Importer des utilisateurs dans l'espace courant",
			"export_user"=>"Exporter les utilisateurs de l'espace courant",
			"importExport_contact"=>"Importer / Exporter des contacts",
			"import_contact"=>"Importer des contacts dans le dossier courant",
			"export_contact"=>"Exporter les contacts du dossier courant",
			"exportFormat"=>"au format",
			"specifyFile"=>"Merci de spécifier un fichier",
			"fileExtension"=>"Le type de fichier n'est pas valide. Il doit être de type",
			"importContactRootFolder"=>"Les contacts importés dans le dossier principal sont affectés par défaut à &quot;tous les utilisateurs de l'espace&quot;",
			"importInfo"=>"Sélectionnez les champs Agora à cibler grâce aux listes déroulantes de chaque colonne",
			"importNotif1"=>"Merci de sélectionner la colonne 'nom' dans les listes déroulante",
			"importNotif2"=>"Merci de sélectionner au moins un élément à importer",
			"importNotif3"=>"Le champ agora à déjà été sélectionné sur une autre colonne (chaque champs agora ne peut être sélectionné qu'une fois)",

			////	Messages d'erreur / Notifications
			"NOTIF_identification"=>"Identifiant ou mot de passe invalide",
			"NOTIF_presentIp"=>"Ce compte utilisateur est actuellement utilisé depuis un autre terminal, avec une autre adresse IP",
			"NOTIF_noAccessNoSpaceAffected"=>"Votre compte utilisateur a bien été identifié, mais vous n'êtes actuellement affecté à aucun espace. Merci de contacter l'administrateur pour vérifier vos droits d'accès",
			"NOTIF_noAccess"=>"Vous êtes déconnecté",
			"NOTIF_fileOrFolderAccess"=>"Fichier/Dossier inaccessible",
			"NOTIF_diskSpace"=>"L'espace pour le stockage de vos fichiers est insuffisant, vous ne pouvez pas ajouter de fichier",
			"NOTIF_fileNotAllowed"=>"les fichiers sensibles ou non reconnus doivent être zippés/compressés avant d'être ajoutés",
			"NOTIF_fileVersion"=>"Type de fichier différent de l'original",
			"NOTIF_folderMove"=>"Vous ne pouvez pas déplacer le dossier à l'intérieur de lui-même !",
			"NOTIF_duplicateName"=>"Un élément ayant le même nom existe déjà : <br> Merci d'en spécifier un autre",
			"NOTIF_duplicateNameFolder"=>"Un dossier ayant le même nom existe déjà : <br> Merci d'en spécifier un autre",
			"NOTIF_fileName"=>"Un fichier ayant le même nom existe déjà.<br>Le nom a cependant été conservé.",
			"NOTIF_chmodDATAS"=>"Le dossier /DATAS/ n'est pas accessible en écriture (lancer au besoin ''chmod 770'')",
			"NOTIF_usersNb"=>"Vous ne pouvez pas créer de nouveau compte utilisateur : nombre limité à ",

			////	Header
			"HEADER_displaySpace"=>"Espaces de travail",
			"HEADER_displayAdmin"=>"Affichage Administrateur",
			"HEADER_displayAdminInfo"=>"affiche également les éléments qui ne me sont pas attribués : agendas, dossiers, etc",
			"HEADER_displayAdminEnabled"=>"Affichage Administrateur activé",
			"HEADER_displayAdminDisabled"=>"Affichage Administrateur désactivé",
			"HEADER_documentation"=>"Guide d'utilisation",
			"HEADER_shortcuts"=>"Raccourcis",

			////	Messenger / Visio
			"MESSENGER_MODULE_NAME"=>"Messagerie",
			"MESSENGER_MODULE_DESCRIPTION"=>"Discutez ou lancez une visioconférence avec les personnes en ligne",
			"MESSENGER_messengerMultiUsers"=>"Discuter à plusieurs sur la messagerie <br>(volet de gauche pour choisir les destinataires)",
			"MESSENGER_chatWithMulti"=>"Discuter avec",
			"MESSENGER_chatWith"=>"Discuter ou lancer une visio avec",
			"MESSENGER_messageFrom"=>"Message de",
			"MESSENGER_messageSentTo"=>"envoyé à",
			"MESSENGER_messageToSelected"=>"Message aux personnes selectionnées",
			"MESSENGER_messageTo"=>"Message à",
			"MESSENGER_addMessageNotif"=>"Merci de spécifier un message",
			"MESSENGER_visioProposeTo"=>"Proposer une visioconférence à",
			"MESSENGER_visioProposeToSelection"=>"Proposer une visioconférence aux personnes sélectionnées",
			"MESSENGER_visioProposeToUsers"=>"Cliquer ici pour lancer la visioconférence entre",
			"MESSENGER_nobody"=>"Aucun autre utilisateur n'est connecté actuellement",

			////	Lancer une Visio
			"VISIO_urlAdd"=>"Ajouter une visioconférence",
			"VISIO_urlAddConfirm"=>"Ajouter un lien pour lancer une nouvelle visiofonférence ?",
			"VISIO_urlCopy"=>"Copier le lien de la visioconférence",
			"VISIO_urlDelete"=>"Supprimer le lien de la visioconférence",
			"VISIO_launch"=>"Lancer la visioconférence",
			"VISIO_launchJitsi"=>"Lancer la visioconférence <br> avec l'application Jitsi",
			"VISIO_launchFromEvent"=>"Lancer la visioconférence de l'événement",
			"VISIO_launchGuide"=>"Problèmes de caméra ou de micro : suivez le guide",
			"VISIO_launchServerTooltip"=>"Choisissez le serveur secondaire si le serveur principal ne fonctionne pas correctement :<br>Important : vos interlocuteurs devront sélectionner le même serveur que vous.",
			"VISIO_launchServerMain"=>"Serveur de visio principal",
			"VISIO_launchServerAlt"=>"Serveur de visio secondaire",

			////	VueObjMenuEdit.php
			"EDIT_notifNoSelection"=>"Vous devez sélectionner au moins une personne ou un espace",
			"EDIT_notifNoPersoAccess"=>"Vous n'êtes pas affecté à l'élément.<br>valider tout de même ?",
			"EDIT_parentFolderAccessError"=>"Vérifiez les droits d'accès du dossier parent  <br><i>--FOLDER_NAME--</i><br><br>  Il doit aussi y avoir un droit d'accès pour  <br><i>--SPACE_LABEL--</i> : <i>--TARGET_LABEL--</i><br><br>  Sans quoi le présent dossier ne sera pas accessible !",
			"EDIT_accessRight"=>"Droits d'accès",
			"EDIT_accessRightContent"=>"Droits d'accès au contenu",
			"EDIT_spaceNoModule"=>"Le module courant n'a pas encore été ajouté à cet espace",
			"EDIT_allUsers"=>"Tout les utilisateurs",
			"EDIT_allUsersTooltip"=>"Droit d'accès pour tous les utilisateurs de l'espace <i>--SPACENAME--</i>",
			"EDIT_allUsersAndGuests"=>"Tout les utilisateurs et invités",
			"EDIT_allUsersAndGuestsTooltip"=>"Droit d'accès pour tous les utilisateurs et invités de l'espace <i>--SPACENAME--</i>.<hr>Les invités n'ont qu'un accès en lecture à l'espace (connexion sans compte utilisateur)",
			"EDIT_adminSpace"=>"Administrateur : accès total à tous les éléments de l'espace",
			"EDIT_showAllUsers"=>"Afficher tous les utilisateurs",
			"EDIT_showAllUsersAndSpaces"=>"Afficher tous les utilisateurs et espaces",
			"EDIT_notifMail"=>"Notifier par email",
			"EDIT_notifMail2"=>"Envoyer une notification par email",
			"EDIT_notifMailTooltip"=>"Envoyer une notification par email aux personnes affectées à l'élément (--OBJLABEL--)",
			"EDIT_notifMailTooltipCal"=>"<hr>Si vous affectez l'événement à des agendas personnels, alors la notification ne sera envoyée qu'aux propriétaires de ces agendas (accès en écriture).",
			"EDIT_notifMailAddFiles"=>"Joindre le/les fichiers à la notification",
			"EDIT_notifMailSelect"=>"Choisir les destinataires des notifications",
			"EDIT_accessRightSubFolders"=>"Donner les mêmes droits d'accès aux sous-dossiers",
			"EDIT_accessRightSubFoldersTooltip"=>"Etendre les droits d'accès aux sous-dossiers (uniquement ceux accessibles en écriture)",
			"EDIT_shortcut"=>"Raccourci",
			"EDIT_shortcutInfo"=>"Afficher un raccourci dans la barre de menu",
			"EDIT_attachedFile"=>"Fichiers joints",
			"EDIT_attachedFileAdd"=>"Joindre des fichiers",
			"EDIT_attachedFileInsert"=>"Ajouter dans le texte",
			"EDIT_attachedFileInsertTooltip"=>"Ajouter l'image dans le texte de l'éditeur (format .jpeg / .png / .mp4)",
			"EDIT_guestName"=>"Votre Nom / Pseudo",
			"EDIT_guestNameNotif"=>"Merci de préciser un nom ou un pseudo",
			"EDIT_guestMail"=>"Votre email",
			"EDIT_guestMailTooltip"=>"Merci de spécifier votre email pour la validation de votre proposition",
			"EDIT_guestElementRegistered"=>"Merci pour votre proposition <br> elle sera vérifiée prochainement avant validation",

			////	Formulaire d'installation
			"INSTALL_dbConnect"=>"Connexion à la base de données",
			"INSTALL_dbHost"=>"Serveur MariaDB ou MySql (Hostname)",
			"INSTALL_dbName"=>"Nom de la Base de Données",
			"INSTALL_dbLogin"=>"Nom d'utilisateur",
			"INSTALL_adminAgora"=>"Administrateur principal",
			"INSTALL_errorDbNameFormat"=>"Attention : le nom de la base de donnée doit comporter de préférence uniquement des caractères alphanumériques, tirets ou underscores",
			"INSTALL_errorDbConnection"=>"La connexion à la base de données a échoué :<br>merci de vérifier les coordonnées de connexion",
			"INSTALL_errorDbExist"=>"Application déjà installée : <a href='index.php'>cliquez ici pour y accéder</a><br><br>Pour relancer l'install, pensez à supprimer la BDD",
			"INSTALL_errorDbNoSqlFile"=>"Le fichier d'installation db.sql n'est pas accessible ou a été supprimé car l'installation a déjà été effectuée",
			"INSTALL_PhpOldVersion"=>"Agora-Project --CURRENT_VERSION-- necessite une version plus recente de PHP",
			"INSTALL_confirmInstall"=>"Confirmer l'installation ?",
			"INSTALL_installOk"=>"Votre espace a été correctement installé",
			// Premiers enregistrements en DB
			"INSTALL_agoraDescription"=>"Espace de partage et de travail collaboratif",
			"INSTALL_dataDashboardNews"=>  '<h3>Bienvenue sur votre nouvel espace de partage !</h3>
											<h4><a href="?ctrl=file"><img src="app/img/file/iconSmall.png"> Partagez vos fichiers avec votre équipe dans le gestionnaire de fichiers</a></h4>
											<h4><a href="?ctrl=calendar"><img src="app/img/calendar/iconSmall.png"> Créez des événements sur votre agenda partagé ou votre agenda personnel</a></h4>
											<h4><a href="?ctrl=dashboard"><img src="app/img/dashboard/iconSmall.png"> Utilisez le fil d"actualité pour diffuser des informations sur votre activité</a></h4>
											<h4><a href="?ctrl=forum"><img src="app/img/messenger.png"> Communiquez via le forum, la messagerie ou les visioconférences</a></h4>
											<h4><a href="?ctrl=task"><img src="app/img/task/iconSmall.png"> Gérez vos tâches et projets pour organiser votre activité</a></h4>
											<h4><a href="?ctrl=mail"><img src="app/img/mail/iconSmall.png"> Envoyez des newsletters pour diffuser des mails d\'information sur votre activité.</a></h4>
											<h4><a href="docs/DOCUMENTATION_FR.pdf?displayFile=true" class="lightboxOpenHref"><img src="app/img/documentation.png"> Consulter le guide d\'utilisation pour découvrir votre espace</a></h4>
											<h4><a href="?ctrl=user&action=SendInvitation" class="lightboxOpenHref"><img src="app/img/mail.png"> Envoyer des invitations par email pour rejoindre l\'espace</a></h4>',
			"INSTALL_dataDashboardPoll"=>"Que pensez-vous du fil d'actualité ?",
			"INSTALL_dataDashboardPollA"=>"Très intéressant !",
			"INSTALL_dataDashboardPollB"=>"Intéressant",
			"INSTALL_dataDashboardPollC"=>"Peu intéressant",
			"INSTALL_dataCalendarEvt"=>"Bienvenue sur votre espace !",
			"INSTALL_dataForumSubject1"=>"Bienvenue sur le forum !",
			"INSTALL_dataForumSubject2"=>"N'hésitez pas à partager vos questions sur ce forum et évoquer les sujets sur lesquels vous souhaitez échanger.",
			"INSTALL_dataTaskStatus1"=>"A faire",
			"INSTALL_dataTaskStatus2"=>"En cours",
			"INSTALL_dataTaskStatus3"=>"A valider",
			"INSTALL_dataTaskStatus4"=>"Terminé",

			////	MOD : AGORA
			////
			"AGORA_generalSettings"=>"Paramétrage général",
			"AGORA_Changelog"=>"Journal des versions",
			"AGORA_phpMailDisabled"=>"Fonction PHP Mail désactivée",
			"AGORA_phpLdapDisabled"=>"Fonction PHP LDAP désactivée",
			"AGORA_phpGD2Disabled"=> "Fonction PHP GD2 désactivée",
			"AGORA_backupFull"=>"Sauvegarde complète",
			"AGORA_backupFullTooltip"=>"Récupérer la sauvegarde complète de l'espace : ensemble des fichiers ainsi que la base de données",
			"AGORA_backupDb"=>"Sauvegarder la base de données",
			"AGORA_backupDbTooltip"=>"Récupérer uniquement la sauvegarde de la base de données de l'espace",
			"AGORA_backupConfirm"=>"Cette opération peut durer de nombreuses minutes : confirmer le téléchargement ?",
			"AGORA_diskSpaceInvalid"=>"L'espace disque pour les fichiers doit être un entier",
			"AGORA_visioHostInvalid"=>"L'URL du serveur de visioconférence est invalide : elle doit commencer par 'https'",
			"AGORA_gApiKeyInvalid"=>"Si vous choisissez Google Map comme outil de cartographie, vous devez y spécifier un 'API Key'",
			"AGORA_gOAuthKeyInvalid"=>"Si vous choisissez la connexion optionnelle via Google, vous devez y spécifier un 'API Key' pour Google SignIn",
			"AGORA_confirmModif"=>"Confirmer les modifications ?",
			"AGORA_name"=>"Nom de l'espace principal",
			"AGORA_nameTooltip"=>"Nom affiché en page de connexion, dans les emails, etc.",
			"AGORA_description"=>"Description en page de connexion",
			"AGORA_footerHtml"=>"Texte en bas à gauche de chaque page",
			"AGORA_logo"=>"Logo en bas à droite de chaque page",
			"AGORA_logoUrl"=>"URL",
			"AGORA_logoConnect"=>"Logo en page de connexion",
			"AGORA_logoConnectTooltip"=>"Logo affiché en tête du formulaire de connexion",
			"AGORA_lang"=>"Langue par défaut",
			"AGORA_timezone"=>"Fuseau horaire",
			"AGORA_diskSpaceLimit"=>"Espace disque pour les fichiers",
			"AGORA_logsTimeOut"=>"Conservation de l'historique des événements",
			"AGORA_logsTimeOutTooltip"=>"La durée de conservation de l'historique des événements concerne l'ajout ou la modif des éléments. Les logs de suppression sont conservés 1 an minimum.",
			"AGORA_visioHost"=>"Serveur de visioconférence Jitsi",
			"AGORA_visioHostTooltip"=>"Url du serveur de visioconférence principal. Exemple : https://framatalk.org ou https://meet.jit.si",
			"AGORA_visioHostAlt"=>"Serveur de visioconférence alternatif",
			"AGORA_visioHostAltTooltip"=>"Url du serveur de visioconférence alternatif : en cas d'indisponibilité du serveur Jitsi principal",
			"AGORA_skin"=>"Couleur de l'interface",
			"AGORA_black"=>"Affichage sombre",
			"AGORA_white"=>"Affichage clair",
			"AGORA_userMailDisplay"=>"Adresses email des utilisateurs visibles par tous",
			"AGORA_userMailDisplayTooltip"=>"Afficher/Masquer l'email dans le profil de chaque utilisateur, les notifications par mail, etc.<br>Note : l'administrateur principal pourra toujours consulter l'email de chaque utilisateur",
			"AGORA_moduleLabelDisplay"=>"Nom des modules dans la barre de menu",
			"AGORA_folderDisplayMode"=>"Affichage par défaut des dossiers",
			"AGORA_wallpaperLogoError"=>"Le fond d'écran et le logo doivent être au format .jpg ou .png",
			"AGORA_deleteWallpaper"=>"Supprimer le fond d'écran",
			"AGORA_usersCommentLabel"=>"Bouton ''commenter'' sur les éléments",
			"AGORA_usersComment"=>"commentaire",
			"AGORA_usersComments"=>"commentaires",
			"AGORA_usersLikeLabel"=>"Bouton ''J'aime'' sur les éléments",
			"AGORA_usersLike"=>"J'aime !",
			"AGORA_mapTool"=>"Outil de cartographie",
			"AGORA_mapToolTooltip"=>"Outil de cartographie pour voir les utilisateurs et contacts sur une carte",
			"AGORA_gApiKey"=>"Google API Key pour Maps",
			"AGORA_gApiKeyTooltip"=>"Parametrage obligatoire pour Google Maps :<br> https://developers.google.com/maps/documentation/javascript/get-api-key",
			"AGORA_gOAuth"=>"Connexion via un compte Google Gmail",
			"AGORA_gOAuthTooltip"=>"Les utilisateurs ayant un identifiant avec une adresse <i>@gmail.com</i> pourront aussi se connecter via leur compte Google",
			"AGORA_gOAuthClientId"=>"Client ID pour la connexion via Google",
			"AGORA_gOAuthClientIdTooltip"=>"Parametrage obligatoire pour la connexion via un compte Google :<br> https://developers.google.com/identity/protocols/oauth2",
			"AGORA_messengerDisplay"=>"Messagerie",
			"AGORA_personsSort"=>"Trier les utilisateurs et contacts par",
			//SMTP
			"AGORA_smtpLabel"=>"Connexion SMTP & sendMail",
			"AGORA_sendmailFrom"=>"Email 'From'",
			"AGORA_sendmailFromPlaceholder"=>"Ex: 'noreply@mydomain.com'",
			"AGORA_smtpHost"=>"Adresse du serveur SMTP (hostname)",
			"AGORA_smtpPort"=>"Port sur serveur",
			"AGORA_smtpPortTooltip"=>"'25' par défaut. '587' ou '465' pour une connexion SSL/TLS",
			"AGORA_smtpSecure"=>"Type de connexion chiffrée (optionnel)",
			"AGORA_smtpSecureTooltip"=>"'ssl' ou 'tls'",
			"AGORA_smtpUsername"=>"Nom d'utilisateur",
			"AGORA_smtpPass"=>"Mot de passe",
			//LDAP
			"AGORA_ldapLabel"=>"Connexion à un serveur LDAP",
			"AGORA_ldapLabelTooltip"=>"Connexion à un serveur LDAP pour la création d'utilisateur sur votre espace : cf. option ''Import/export d'utilisateur'' du module ''Utilisateur''",
			"AGORA_ldapUri"=>"URI LDAP",
			"AGORA_ldapUriTooltip"=>"URI LDAP complet de la forme LDAP://hostname:port ou LDAPS://hostname:port pour le chiffrement SSL.",
			"AGORA_ldapPort"=>"Port du serveur",
			"AGORA_ldapPortTooltip"=>"Le port utilisé pour la connexion : ''389'' par défaut",
			"AGORA_ldapLogin"=>"DN de l'administrateur LDAP (Distinguished Name)",
			"AGORA_ldapLoginTooltip"=>"par exemple ''cn=admin,dc=mon-entreprise,dc=com''",
			"AGORA_ldapPass"=>"Mot de passe de l'administrateur LDAP",
			"AGORA_ldapDn"=>"DN du groupe d'utilisateurs (Distinguished Name)",
			"AGORA_ldapDnTooltip"=>"DN du groupe d'utilisateurs : emplacement des utilisateurs dans l'annuaire. Exemple ''ou=mon-groupe,dc=mon-entreprise,dc=com''",
			"importLdapFilterTooltip"=>"Filtre de recherche LDAP (cf. https://www.php.net/manual/function.ldap-search.php). Exemple ''(cn=*)'' ou ''(&(samaccountname=MONLOGIN)(cn=*))''",
			"AGORA_ldapConnectError"=>"Erreur de connexion au serveur LDAP !",

			////	MOD : LOG
			////
			"LOG_MODULE_DESCRIPTION"=>"Historique des événements",
			"LOG_download"=>"Télécharger le fichier d'historique",
			"LOG_path"=>"Chemin",
			"LOG_filterBy"=>"Filtrer par",
			"LOG_date"=>"Date",
			"LOG_moduleName"=>"Module",
			"LOG_objectType"=>"Type d'objet",
			"LOG_action"=>"Action",
			"LOG_userName"=>"Utilisateur",
			"LOG_comment"=>"Commentaire",
			"LOG_noLogs"=>"Aucun log",
			"LOG_search"=>"Chercher",
			"LOG_connexion"=>"connexion",
			"LOG_add"=>"ajout",
			"LOG_delete"=>"suppression",
			"LOG_modif"=>"modification",

			////	MOD : SPACE
			////
			"SPACE_moduleTooltip"=>"L'espace principal peut être subdivisé en plusieurs espaces (alias ''sous-espace'')",
			"SPACE_manageAllSpaces"=>"Gérer tous les espaces de travail",
			"SPACE_config"=>"Gérer l'espace de travail",
			"SPACE_space"=>"espace",
			"SPACE_spaces"=>"espaces",
			"SPACE_accessRightUndefined"=>"A définir !",
			"SPACE_modules"=>"Modules",
			"SPACE_addSpace"=>"Nouvel espace",
			//Edit
			"SPACE_userAdminAccess"=>"Utilisateurs et Administrateurs de l'espace",
			"SPACE_selectModule"=>"Vous devez sélectionner au moins un module",
			"SPACE_spaceModules"=>"Modules de l'espace",
			"SPACE_publicSpace"=>"Espace public : accès invité",
			"SPACE_publicSpaceTooltip"=>"Un espace public est ouvert aux personnes n'ayant pas de compte utilisateur (invités). Ils pourront alors accéder à l'espace depuis la page d'accueil. Vous pouvez spécifier un mot de passe pour protéger l'accès à cet espace public. Les modules 'Email' et 'Utilisateurs' ne sont pas disponibles pour les invités.",
			"SPACE_publicSpaceNotif"=>"Si votre espace public contient des données personnelles (téléphone, adresse, etc) pensez à spécifier un mot de passe pour être conforme à la RGPD : Règlement Général sur la Protection des Données",
			"SPACE_usersInvitation"=>"Les utilisateurs peuvent envoyer des invitations par email",
			"SPACE_usersInvitationTooltip"=>"Tous les utilisateurs peuvent envoyer des invitations par email pour rejoindre l'espace",
			"SPACE_allUsers"=>"Tous les utilisateurs",
			"SPACE_user"=>"Utilisateur",
			"SPACE_userTooltip"=>"Accès normal à l'espace",
			"SPACE_admin"=>"Administrateur",
			"SPACE_adminTooltip"=>"L'administrateur peut éditer/supprimer tous les élements présents sur l'espace.<br>Il peut également paramétrer l'espace, créer de nouveaux utilisateurs ou groupes d'utilisateurs, envoyer des invitations par mail, etc.",

			////	MOD : USER
			////
			"USER_MODULE_NAME"=>"Utilisateurs",
			"USER_MODULE_DESCRIPTION"=>"Utilisateurs de l'espace",
			"USER_OPTION_allUsersAddGroup"=>"Tous les utilisateurs peuvent créer des groupes",
			"USER_spaceOrAllUsersTooltip"=>"Utilisateurs de l'espace courant / Utilisateurs de tous les espaces (affichage administrateur)",
			"USER_spaceUsers"=>"Gérer les utilisateurs de l'espace",
			"USER_allUsers"=>"Gérer tous les utilisateurs",
			"USER_deleteDefinitely"=>"Supprimer définitivement",
			"USER_deleteFromCurSpace"=>"Supprimer/désaffecter de l'espace courant",
			"USER_deleteFromCurSpaceConfirm"=>"Supprimer/désaffecter l'utilisateur de l'espace courant ?",
			"USER_user"=>"Utilisateur",
			"USER_users"=>"utilisateurs",
			"USER_addExistUser"=>"Ajouter un utilisateur existant",
			"USER_addExistUserTitle"=>"Ajouter à l'espace courant un utilisateur déjà existant (affecter à l'espace courant)",
			"USER_addUser"=>"Nouvel utilisateur",
			"USER_addUserSite"=>"Créer un utilisateur : affecté par défaut à aucun espace !",
			"USER_addUserSpace"=>"Créer un utilisateur pour l'espace courant",
			"USER_sendCoords"=>"Envoyer des identifiants",
			"USER_sendCoordsTooltip"=>"Envoyer à plusieurs utilisateurs un email avec leur identifiant de connexion et un lien pour initialiser leur mot de passe",
			"USER_sendCoordsTooltip2"=>"Envoyer à chaque nouvel utilisateur un email avec leurs coordonnées de connexion.",
			"USER_sendCoordsConfirm"=>"Confirmer l'envoi ?",
			"USER_sendCoordsMail"=>"Vos coordonnées de connexion à votre espace",
			"USER_noUser"=>"Aucun utilisateur affecté à cet espace pour le moment",
			"USER_spaceList"=>"Espaces de l'utilisateur",
			"USER_spaceNoAffectation"=>"aucun espace",
			"USER_adminGeneral"=>"Administrateur principal",
			"USER_adminGeneralTooltip"=>"Attention : l'Administrateur principal peut éditer/supprimer tous les éléments de l'espace (dossiers, fichiers, agendas, etc) ainsi que tous les utilisateurs et espaces !<br>Il est donc conseillé d'attribuer ce privilège à 2 ou 3 personnes maximum.<br><br>Pour des privilèges plus restreints, choississez le droit ''Administrateur'' (ci-dessous)",
			"USER_adminSpace"=>"Administrateur de l'espace",
			"USER_userSpace"=>"Utilisateur de l'espace",
			"USER_profilEdit"=>"Modifier le profil utilisateur",
			"USER_myProfilEdit"=>"Modifier mon profil",
			// Invitations
			"USER_sendInvitation"=>"Envoyer des invitations",
			"USER_sendInvitationTooltip"=>"Envoyer des mails d'invitation à rejoindre l'espace courant :<br> Dès qu'une invitation est validée, un compte utilisateur est automatiquement créé pour la personne concernée.",
			"USER_mailInvitationObject"=>"Invitation de",
			"USER_mailInvitationFromSpace"=>"vous invite sur l'espace",
			"USER_mailInvitationConfirm"=>"Merci de confirmer l'invitation",
			"USER_mailInvitationWait"=>"Invitation(s) en attente de confirmation",
			"USER_exired_idInvitation"=>"Le lien de votre invitation a expiré...",
			"USER_invitPassword"=>"Confirmez votre invitation",
			"USER_invitPassword2"=>"Choisissez votre mot de passe puis validez votre invitation",
			"USER_invitationValidated"=>"Votre invitation a été validée !",
			"USER_gPeopleImport"=>"Importer mes contacts Gmail",
			"USER_quotaExceeded"=>"Quota du nombre d'utilisateur atteint. Merci de contacter l'administrateur de l'espace.",
			"USER_importQuotaExceeded"=>"Vous êtes limité à --USERS_QUOTA_REMAINING-- nouveaux comptes utilisateurs, sur un total de --LIMITE_NB_USERS-- utilisateurs",
			// groupes
			"USER_spaceGroups"=>"Groupes d'utilisateurs",
			"USER_spaceGroupsEdit"=>"Editer les groupes d'utilisateurs de l'espace",
			"USER_groupEditInfo"=>"Liste des groupes que je peux éditer : auteur du groupe ou administrateur de l'espace",
			"USER_addGroup"=>"Nouveau groupe",
			"USER_userGroups"=>"Groupes de l'utilisateur",
			// Utilisateur_affecter
			"USER_searchPrecision"=>"Merci de préciser un nom, un prénom ou une adresse email",
			"USER_userAffectConfirm"=>"Confirmer les affectations ?",
			"USER_userSearch"=>"Rechercher des utilisateurs pour les ajouter à l'espace",
			"USER_allUsersOnSpace"=>"Tous les utilisateurs sont affectés à l'espace courant",
			"USER_usersSpaceAffectation"=>"Affecter des utilisateurs à l'espace :",
			"USER_usersSearchNoResult"=>"Aucun utilisateur pour cette recherche",
			"USER_usersSearchBack"=>"Retour",
			// Utilisateur_edit & CO
			"USER_langs"=>"Langue",
			"USER_persoCalendarDisabled"=>"Agenda personnel désactivé",
			"USER_persoCalendarDisabledTooltip"=>"Cocher cette option pour désactiver l'agenda personnel de l'utilisateur.<br><br> Note : un agenda personnel est attribué par défaut à chaque utilisateur. Il reste toujours accessible, quelquesoit l'espace affiché.",
			"USER_connectionSpace"=>"Espace affiché à la connexion",
			"USER_loginExists"=>"L'identifiant / email existe déjà. Merci d'en spécifier un autre",
			"USER_mailPresentInAccount"=>"un compte utilisateur existe déjà avec cette adresse email",
			"USER_loginAndMailDifferent"=>"Les deux adresses email doivent être identiques",
			"USER_mailNotifObject"=>"Bienvenue sur ",
			"USER_mailNotifContent"=>"Votre compte utilisateur vient d'être créé sur",
			"USER_mailNotifContent2"=>"Connectez-vous ici avec les coordonnées suivantes",
			"USER_mailNotifContent3"=>"Pensez à conserver cet email dans vos archives",
			// Edition du Livecounter/Messenger
			"USER_livecounterVisibility"=>"Visibilité sur la messagerie",
			"USER_livecounterAllUsers"=>"Afficher ma présence lorsque je suis connecté",
			"USER_livecounterDisabled"=>"Toujours masquer ma présence",
			"USER_livecounterSomeUsers"=>"Afficher ma présence pour certains utilisateurs",

			////	MOD : DASHBOARD
			////
			"DASHBOARD_MODULE_NAME"=>"Actualités",
			"DASHBOARD_MODULE_DESCRIPTION"=>"Fil d'actualité, Sondages et Nouveaux éléments",
			"DASHBOARD_OPTION_adminAddNews"=>"Seul l'administrateur peut créer des actualités",
			"DASHBOARD_OPTION_disablePolls"=>"Désactiver les sondages",
			"DASHBOARD_OPTION_adminAddPoll"=>"Seul l'administrateur peut créer des sondages",
			"DASHBOARD_menuNews"=>"Fil d'actualité",
			"DASHBOARD_menuPolls"=>"Sondages",
			"DASHBOARD_menuElems"=>"Nouveautés",
			"DASHBOARD_addNews"=>"Nouvelle actualité",
			"DASHBOARD_offlineNews"=>"Afficher les actualités archivées",
			"DASHBOARD_offlineNewsNb"=>"actualités archivées",
			"DASHBOARD_noNews"=>"Aucune actualité pour le moment",
			"DASHBOARD_addPoll"=>"Nouveau sondage",
			"DASHBOARD_pollsVoted"=>"Voir uniquement les sondages votés",
			"DASHBOARD_pollsVotedNb"=>"sondages pour lesquels j'ai déjà voté",
			"DASHBOARD_pollsNotVoted"=>"sondages non votés",
			"DASHBOARD_vote"=>"Voter et voir les résultats !",
			"DASHBOARD_voteTooltip"=>"Le vote est anonyme : personne n'aura connaissance de votre choix",
			"DASHBOARD_answerVotesNb"=>"Voté --NB_VOTES-- fois",
			"DASHBOARD_pollVotesNb"=>"Le sondage a été voté --NB_VOTES-- fois",
			"DASHBOARD_pollVotedBy"=>"Voté par",
			"DASHBOARD_noPoll"=>"Aucun sondage pour le moment",
			"DASHBOARD_plugins"=>"Nouveaux éléments créés",
			"DASHBOARD_pluginsTooltip"=>"Eléments créés",
			"DASHBOARD_pluginsTooltip2"=>"entre le",
			"DASHBOARD_plugins_day"=>"aujourd'hui",
			"DASHBOARD_plugins_week"=>"cette semaine",
			"DASHBOARD_plugins_month"=>"ce mois",
			"DASHBOARD_plugins_previousConnection"=>"depuis la dernière connexion",
			"DASHBOARD_pluginsTooltipRedir"=>"Afficher l'élément dans son dossier",
			"DASHBOARD_pluginEmpty"=>"Pas de nouvel element sur cette période",
			// Actualite/News
			"DASHBOARD_topNews"=>"Actualité à la une",
			"DASHBOARD_topNewsTooltip"=>"Actualité toujours affichée en haut de liste",
			"DASHBOARD_offline"=>"Actualité archivée",
			"DASHBOARD_dateOnline"=>"Publication programmée",
			"DASHBOARD_dateOnlineTooltip"=>"Programmer une date de publication automatique. Dans cette attente, l'actualité sera archivée",
			"DASHBOARD_dateOnlineNotif"=>"L'actualité est momentanément archivée dans l'attente de sa publication automatique",
			"DASHBOARD_dateOffline"=>"Archivage programmé",
			"DASHBOARD_dateOfflineTooltip"=>"Programmer une date d'archivage automatiquement de l'actualité",
			// Sondage/Polls
			"DASHBOARD_titleQuestion"=>"Titre / Question",
			"DASHBOARD_multipleResponses"=>"Plusieurs réponses possibles pour chaque vote",
			"DASHBOARD_newsDisplay"=>"Afficher avec les actualités (menu de gauche)",
			"DASHBOARD_publicVote"=>"Le choix de chaque votant est public",
			"DASHBOARD_publicVoteInfos"=>"Le choix de chaque votant sera affiché dans le résultat du sondage.",
			"DASHBOARD_dateEnd"=>"Fin des votes",
			"DASHBOARD_responseList"=>"Responses possibles",
			"DASHBOARD_responseNb"=>"Response n°",
			"DASHBOARD_addResponse"=>"Ajouter une réponse",
			"DASHBOARD_controlResponseNb"=>"Merci de spécifier au moins 2 réponses possibles",
			"DASHBOARD_votedPollNotif"=>"Attention : dès que le sondage a commencé à être voté, il n'est plus possible de modifier le titre et les réponses du sondage",
			"DASHBOARD_voteNoResponse"=>"Merci de sélectionner une réponse",
			"DASHBOARD_exportPoll"=>"Télécharger le résultat du sondage en pdf",
			"DASHBOARD_exportPollDate"=>"Résultat du sondage à la date du",

			////	MOD : FILE
			////
			"FILE_MODULE_NAME"=>"Fichiers",
			"FILE_MODULE_DESCRIPTION"=>"Gestionnaire de fichiers",
			"FILE_OPTION_adminRootAddContent"=>"Seul l'administrateur peut créer des dossiers et fichiers à la racine",
			"FILE_addFile"=>"Nouveau fichier",
			"FILE_addFileAlert"=>"Dossier du serveur inaccessible en écriture!  merci de contacter l'administrateur",
			"FILE_downloadSelection"=>"télécharger la sélection",
			"FILE_fileDownload"=>"Télécharger",
			"FILE_fileSize"=>"Taille du fichier",
			"FILE_imageSize"=>"Dimension de l'image",
			"FILE_nbFileVersions"=>"versions du fichier",
			"FILE_downloadsNb"=>"(téléchargé --NB_DOWNLOAD-- fois)",
			"FILE_downloadedBy"=>"fichier téléchargé par",
			"FILE_addFileVersion"=>"Ajouter une nouvelle version du fichier",
			"FILE_noFile"=>"Aucun fichier pour le moment",
			// Edit
			"FILE_fileSizeLimit"=>"Les fichiers ne doivent pas dépasser",
			"FILE_uploadSimple"=>"Envoi simple",
			"FILE_uploadMultiple"=>"Envoi multiple",
			"FILE_uploadSimpleMultiple"=>"Sélection simple ou multiple de fichiers",
			"FILE_imgReduce"=>"Optimiser les images",
			"FILE_updatedName"=>"Le nom du fichier est différent : celui de la nouvelle version sera donc conservé",
			"FILE_fileSizeError"=>"Fichier trop volumineux",
			"FILE_addMultipleFilesTooltip"=>"maximum par fichier. Sélectionnez plusieurs fichiers via la touche <i>Ctrl</i>",
			"FILE_selectFile"=>"Merci de sélectionner au moins un fichier",
			"FILE_fileContent"=>"contenu",
			// Versions
			"FILE_versionsOf"=>"Versions de",
			"FILE_confirmDeleteVersion"=>"Confirmer la suppression de cette version ?",

			////	MOD : CALENDAR
			////
			"CALENDAR_MODULE_NAME"=>"Agenda",
			"CALENDAR_MODULE_DESCRIPTION"=>"Agendas partagés et personnels",
			"CALENDAR_OPTION_adminAddRessourceCalendar"=>"Seul l'administrateur peut créer des agendas partagés",
			"CALENDAR_OPTION_adminAddCategory"=>"Seul l'administrateur peut créer des categories d'événement",
			"CALENDAR_OPTION_createSpaceCalendar"=>"Créer un agenda partagé pour l'espace",
			"CALENDAR_CAT_menuTooltip"=>"Afficher uniquement les événements avec la catégorie",
			"CALENDAR_CAT_showAll"=>"Toutes les catégories",
			"CALENDAR_CAT_showAllTooltip"=>"Afficher toutes les catégories",
			"CALENDAR_CAT_undefined"=>"Catégorie non définie",
			"CALENDAR_CAT_editTitle"=>"Editer les catégories d'événement",
			"CALENDAR_CAT_editInfo"=>"Chaque catégorie peut être modifiée par son auteur ou par l'admin général",
			"CALENDAR_CAT_editAdd"=>"Ajouter une catégorie",
			"CALENDAR_moduleAlwaysEnabledInfo"=>"Les utilisateurs n'ayant pas désactivé leur agenda personnel dans leur profil utilisateur verront toujours le module Agenda dans la barre de menu",
			"CALENDAR_readableCalendars"=>"Agendas disponibles",
			"CALENDAR_hideAllCals"=>"Masquer tous les agendas",
			"CALENDAR_printCalendars"=>"Imprimer l'agenda",
			"CALENDAR_printCalendarsInfos"=>"Imprimez la page en mode paysage",
			"CALENDAR_addSharedCalendar"=>"Nouvel agenda partagé",
			"CALENDAR_addSharedCalendarTooltip"=>"Créer un agenda partagé : pour les réservation d'une salle, véhicule, vidéoprojecteur, etc.",
			"CALENDAR_exportIcal"=>"Exporter les événements au format iCal",
			"CALENDAR_icalUrl"=>"Copier l'URL pour voir/synchroniser l'agenda via une appli externe",
			"CALENDAR_icalUrlCopy"=>"Permet un accès en lecture à l'agenda depuis une application externe : Outlook, Thunderbird, Google Calendar, etc.",
			"CALENDAR_importIcal"=>"Importer des événements au format iCal",
			"CALENDAR_ignoreOldEvt"=>"Ne pas importer les événements de plus d'un an",
			"CALENDAR_importIcalPresent"=>"Déjà présent ?",
			"CALENDAR_importIcalPresentInfo"=>"Evenement déjà présent dans l'agenda ?",
			"CALENDAR_display_1Day"=>"1 jour",
			"CALENDAR_display_3Days"=>"3 jours",
			"CALENDAR_display_7Days"=>"7 jours",
			"CALENDAR_display_week"=>"Semaine",
			"CALENDAR_display_workWeek"=>"Semaine de travail",
			"CALENDAR_display_month"=>"Mois",
			"CALENDAR_yearWeekNum"=>"Voir la semaine n°",
			"CALENDAR_periodNext"=>"Période suivante",
			"CALENDAR_periodPrev"=>"Période précédente",
			"CALENDAR_evtAffects"=>"Dans l'agenda : ",
			"CALENDAR_evtAffectToConfirm"=>"A confirmer dans l'agenda :",
			"CALENDAR_evtProposition"=>"Proposition d'événement à confirmer",
			"CALENDAR_evtProposedBy"=>"Proposé par",
			"CALENDAR_evtProposeConfirm"=>"Confirmer la proposition",
			"CALENDAR_evtProposeConfirmed"=>"La proposition d'événement a bien été ajouté à l'agenda <br>Un email de notification a été envoyé à l'auteur",
			"CALENDAR_evtProposeConfirmedMail"=>"Votre proposition d'événement a bien été confirmée par",
			"CALENDAR_evtProposeDecline"=>"Décliner la proposition",
			"CALENDAR_evtProposeDeclined"=>"La proposition a été décliné <br>Un email de notification a été envoyé à l'auteur",
			"CALENDAR_evtProposeDeclinedMail"=>"Votre proposition d'événement a été déclinée",
			"CALENDAR_evtDelete"=>"Supprimer l'événement",
			"CALENDAR_evtDeleteCal"=>"Enlever l'événement de cet agenda",
			"CALENDAR_evtDeleteDate"=>"Enlever l'événement à cette date",
			"CALENDAR_evtPrivate"=>"Événement privé",
			"CALENDAR_evtAutor"=>"Événements que j'ai créés",
			"CALENDAR_evtAutorInfo"=>"Afficher les événements que j'ai créés",
			"CALENDAR_evtAutorSortCrea"=>"Trier par date de création (desc)",
			"CALENDAR_evtAutorSortBegin"=>"Trier par date de début de l'événement (desc)",
			"CALENDAR_evtChangeTime"=>"Déplacer à",
			"CALENDAR_evtChangeTimeConfirmed"=>"L'événement a bien été déplacé",
			"CALENDAR_noEvt"=>"Aucun événement",
			"CALENDAR_noCalendarDisplayed"=>"Aucun agenda affiché",
			// Evenement
			"CALENDAR_importanceNormal"=>"Importance normale",
			"CALENDAR_importanceHight"=>"Importance haute",
			"CALENDAR_visibilityPublic"=>"Affichage normal",
			"CALENDAR_visibilityPublicHide"=>"Affichage de la plage horaire",
			"CALENDAR_visibilityPrivate"=>"Affichage privé",
			"CALENDAR_visibilityTooltip"=>"Pour les personnes n'ayant qu'un accès en lecture à l'agenda : <br>- ''Affichage de la plage horaire'' : montre le créneau occupé mais masque les détails de l'événement<br>- ''Affichage privé'' : masque l'événement dans l'agenda",
			// Edit
			"CALENDAR_sharedCalendarDescription"=>"Agenda partagé de l'espace",
			"CALENDAR_noRepeat"=>"Une seule fois",
			"CALENDAR_period_weekDay"=>"Toutes les semaines",
			"CALENDAR_period_month"=>"Tous les mois",
			"CALENDAR_period_monthDetail"=>"Tous les --DATE-- du mois",
			"CALENDAR_period_year"=>"Tous les ans",
			"CALENDAR_period_yearDetail"=>"Tous les --DATE-- de l'année",
			"CALENDAR_periodDateExceptions"=>"Date d'exception de répétition",
			"CALENDAR_periodDateEnd"=>"Date de fin de répétition",
			"CALENDAR_calendarAffectations"=>"Affectation aux agendas",
			"CALENDAR_addEvt"=>"Nouvel événement",
			"CALENDAR_addEvtTooltip"=>"Ajouter un événement à l'agenda",
			"CALENDAR_addEvtTooltip2"=>"Ajouter l'événement à l'agenda",
			"CALENDAR_proposeEvtTooltip"=>"Proposer l'événement pour cet agenda (accessible en lecture seule) :<br>l'événement devra être validé par le propriétaire de l'agenda",
			"CALENDAR_proposeOptionTooltip"=>"Option pour proposer l'événement pour cet agenda :<br>l'événement devra être validé par le propriétaire de l'agenda",
			"CALENDAR_verifCalNb"=>"Merci de sélectionner au moins un agenda",
			"CALENDAR_busyTimeSlot"=>"Créneau déjà occupé sur l'agenda :",
			"CALENDAR_timeSlot"=>"Plage horaire pour l'affichage ''semaine''",
			"CALENDAR_propositionNotif"=>"Me notifier par email à chaque propositions d'événement",
			"CALENDAR_propositionNotifTooltip"=>"Chaque proposition d'événement sera validé ou invalidé par l'administrateur de l'agenda.",
			"CALENDAR_propositionGuest"=>"Les invités peuvent proposer des événements",
			"CALENDAR_propositionGuestTooltip"=>"Pensez à sélectionnez 'tous les utilisateur et invités' dans les droits d'accès ci-dessous.",
			"CALENDAR_propositionEmailSubject"=>"Nouvel événement proposé par",
			"CALENDAR_propositionEmailMessage"=>"Nouvel événement proposé par --AUTOR_LABEL-- : &nbsp; <i><b>--EVT_TITLE_DATE--</b></i> <br><i>--EVT_DESCRIPTION--</i> <br>Accédez à votre espace pour confirmer ou annuler cette proposition",

			////	MOD : FORUM
			////
			"FORUM_MODULE_NAME"=>"Forum",
			"FORUM_MODULE_DESCRIPTION"=>"Forum de discussion",
			"FORUM_OPTION_adminAddSubject"=>"Seul l'administrateur peut créer des sujets",
			"FORUM_OPTION_adminAddTheme"=>"Seul l'administrateur peut créer des thèmes",
			"FORUM_CAT_menuTooltip"=>"Afficher uniquement les sujets avec le thème",
			"FORUM_CAT_showAll"=>"Tous les thèmes",
			"FORUM_CAT_showAllTooltip"=>"Afficher tous les thèmes",
			"FORUM_CAT_undefined"=>"Thème non défini",
			"FORUM_CAT_editTitle"=>"Editer les thèmes du forum",
			"FORUM_CAT_editInfo"=>"Chaque theme peut être modifié par son auteur ou par l'admin général",
			"FORUM_CAT_editAdd"=>"Ajouter un theme",
			"SORT_dateLastMessage"=>"dernier message",
			"FORUM_forumRoot"=>"Accueil du forum",
			"FORUM_subject"=>"sujet",
			"FORUM_subjects"=>"sujets",
			"FORUM_message"=>"message",
			"FORUM_messages"=>"messages",
			"FORUM_lastMessageFrom"=>"dernier de",
			"FORUM_noSubject"=>"Aucun sujet pour le moment",
			"FORUM_subjectBy"=>"Sujet de",
			"FORUM_addSubject"=>"Nouveau sujet",
			"FORUM_displaySubject"=>"Voir le sujet",
			"FORUM_addMessage"=>"Ajouter un message",
			"FORUM_quoteMessage"=>"Répondre",
			"FORUM_quoteMessageInfo"=>"Répondre en citant ce message",
			"FORUM_notifyLastPost"=>"Notifier chaque nouveau message",
			"FORUM_notifyLastPostTooltip"=>"M'envoyer un email de notification à chaque nouveau message",
			"FORUM_notifOnlyReadAccess"=>"Attention : s'il n'y que des accès en lecture, personne ne pourra contribuer au sujet...",
			"FORUM_notifWriteAccess"=>"L'accès en ''Ecriture'' est destiné aux modérateurs du sujet :<br>Il est donc conseillé d'utiliser le droit en ''Ecriture limité''",

			////	MOD : TASK
			////
			"TASK_MODULE_NAME"=>"Tâches",
			"TASK_MODULE_DESCRIPTION"=>"Tâches / Notes",
			"TASK_OPTION_adminRootAddContent"=>"Seul l'administrateur peut créer des dossiers et tâches à la racine",
			"TASK_OPTION_adminAddStatus"=>"Seul l'administrateur peut créer des statuts de tâches",
			"TASK_CAT_menuTooltip"=>"Afficher uniquement les tâches avec le statut",
			"TASK_CAT_showAll"=>"Tous les statuts",
			"TASK_CAT_showAllTooltip"=>"Afficher tous les statuts",
			"TASK_CAT_undefined"=>"Statut non défini",
			"TASK_CAT_editTitle"=>"Editer les statuts des tâches",
			"TASK_CAT_editInfo"=>"Chaque statut Kanban peut être modifié par son auteur ou par l'admin général",
			"TASK_CAT_editAdd"=>"Ajouter un statut Kanban",
			"SORT_priority"=>"Priorité",
			"SORT_advancement"=>"Avancement",
			"SORT_dateBegin"=>"Date de debut",
			"SORT_dateEnd"=>"Date de fin",
			"TASK_addTask"=>"Nouvelle tâche",
			"TASK_noTask"=>"Aucune tâche pour le moment",
			"TASK_advancement"=>"Avancement",
			"TASK_advancementAverage"=>"Avancement moyen",
			"TASK_priority"=>"Priorité",
			"TASK_priorityUndefined"=>"Priorité non défini",
			"TASK_priority1"=>"Basse",
			"TASK_priority2"=>"Normale",
			"TASK_priority3"=>"Haute",
			"TASK_assignedTo"=>"Assigné à",
			"TASK_advancementDelayed"=>"Avancement en retard",
			"TASK_folderDateBeginEnd"=>"Debut au plus tôt / Fin au plus tard",

			////	MOD : CONTACT
			////
			"CONTACT_MODULE_NAME"=>"Contacts",
			"CONTACT_MODULE_DESCRIPTION"=>"Annuaire de contacts",
			"CONTACT_OPTION_adminRootAddContent"=>"Seul l'administrateur peut créer des dossiers et contacts à la racine",
			"CONTACT_addContact"=>"Nouveau contact",
			"CONTACT_noContact"=>"Aucun contact pour le moment",
			"CONTACT_createUser"=>"Créer un utilisateur sur cet espace",
			"CONTACT_createUserConfirm"=>"Créer un nouveau compte utilisateur pour l'espace courant, à partir de ce contact ?",
			"CONTACT_createUserConfirmed"=>"L'utilisateur a été créé",

			////	MOD : LINK
			////
			"LINK_MODULE_NAME"=>"Liens",
			"LINK_MODULE_DESCRIPTION"=>"Liens Internet et sites Internet favoris",
			"LINK_OPTION_adminRootAddContent"=>"Seul l'administrateur peut créer des dossiers et liens à la racine",
			"LINK_addLink"=>"Nouveau lien",
			"LINK_noLink"=>"Aucun lien pour le moment",
			"LINK_adress"=>"Adresse web",

			////	MOD : MAIL
			////
			"MAIL_MODULE_NAME"=>"Email",
			"MAIL_MODULE_DESCRIPTION"=>"Envoi d'email aux utilisateurs et/ou contacts (Newsletter)",
			"MAIL_specifyMail"=>"Merci de spécifier au moins un destinataire",
			"MAIL_title"=>"Sujet de l'email",
			"MAIL_description"=>"Message de l'email",
			"MAIL_historyTitle"=>"Historique des emails envoyés",
			"MAIL_delete"=>"Supprimer l'email",
			"MAIL_resend"=>"Renvoyer l'email",
			"MAIL_resendInfo"=>"Récupérer le contenu de cet email pour l'envoyer à nouveau",
			"MAIL_historyEmpty"=>"Aucun email pour le moment",
		);
	}

	/*
	 * Jours Fériés de l'année
	 */
	public static function publicHolidays($year)
	{
		$dateList[$year."-01-01"]="Jour de l'an";
		$dateList[$year."-05-01"]="Fête du Travail";
		$dateList[$year."-05-08"]="Fête de la Victoire";
		$dateList[$year."-07-14"]="Fête nationale";
		$dateList[$year."-08-15"]="Assomption";
		$dateList[$year."-11-01"]="Toussaint";
		$dateList[$year."-11-11"]="Armistice";
		$dateList[$year."-12-25"]="Noël";
		if(function_exists("easter_date")){
			$easterTime=easter_date($year);
			$dateList[date('Y-m-d',$easterTime)]						="Pâques";
			$dateList[date('Y-m-d',strtotime("+1 days",$easterTime))]	="Lundi de Pâques";
			$dateList[date('Y-m-d',strtotime("+39 days",$easterTime))]	="Jeudi de l'Ascension";
			$dateList[date('Y-m-d',strtotime("+49 days",$easterTime))]	="Pentecôte";
			$dateList[date('Y-m-d',strtotime("+50 days",$easterTime))]	="Lundi de pentecôte";
		}
		$tmpDates=Txt::timeChangeDates($year);
		$dateList[$tmpDates["summer"]]="Heure d'été";
		$dateList[$tmpDates["winter"]]="Heure d'hiver";
		return $dateList;
	}
}