<?php
/*
 * Traductions
 */
class Trad extends Txt
{
	/*
	 * Chargement les elements de traduction
	 */
	public static function loadTrads()
	{
		////	Dates formatées par PHP
		setlocale(LC_TIME, "pt_PT.utf8", "pt_PT.UTF-8", "pt_PT", "pt", "portuguese");

		////	TRADUCTIONS
		self::$trad=array(
			////	Langue de l'appli, des dates et de l'éditeur
			"CURLANG"=>"pt",
			"DATELANG"=>"pt_PT",
			"EDITORLANG"=>"pt_PT.js",
			"FANCYBOXLANG"=>"en",

			////	Divers
			"mainMenu"=>"Menu principal",
			"menuOptions"=>"Menu de opções",
			"emptyFields"=>"Por favor, preencha os campos de formulário",
			"requiredFields"=>"Campo obrigatório",
			"inaccessibleElem"=>"Elemento inacessível",
			"warning"=>"Atenção",
			"elemEditedByAnotherUser"=>"O item está sendo editado por",
			"yes"=>"sim",
			"no"=>"não",
			"none"=>"não",
			"or"=>"ou",
			"and"=>"e",
			"goToPage"=>"Ir para a página",
			"alphabetFilter"=>"Filtro alfabético",
			"displayAll"=>"Mostrar tudo",
			"show"=>"Mostrar",
			"hide"=>"Ocultar",
			"byDefault"=>"Por padrão",
			"changeOrder"=>"Mover para estabelecer a ordem de apresentação dos módulos",
			"mapLocalize"=>"Localizar no mapa",
			"mapLocalizationFailure"=>"Falha de localização do seguinte endereço",
			"mapLocalizationFailure2"=>"Verifique se o endereço existe em www.google.com/maps ou www.opersetmap.org",
			"sendMail"=>"enviar um e-mail",
			"mailInvalid"=>"E-mail não é válido",
			"element"=>"item",
			"elements"=>"itens",
			"folder"=>"pasta",
			"folders"=>"pastas",
			"close"=>"Fechar",
			"modifRecorded"=>"As mudanças foram registradas",
			"comment"=>"Comentário",
			"commentAdd"=>"Adicione um comentário",
			"optional"=>"(opcional)",
			"objNew"=>"Elemento criado recentemente",
			"objNewTooltip"=>"Criado em 24 horas ou desde o login anterior",
			"personalAccess"=>"Acesso pessoal",
			"copyUrl"=>"Copie o endereço web (URL)",
			"copyUrlTooltip"=>"Permite o acesso externo ao elemento : a partir de uma notícia, de um e-mail, de uma mensagem de fórum, de um blogue, etc.",
			"copyUrlNotif"=>"O endereço da web foi copiado corretamente.",
			
			////	Confirm et Suppression
			"confirm"=>"Confirmar",
			"confirmOk"=>"Ok",
			"confirmCancel"=>"Cancelar",
			"confirmDownload"=>"Descarregar o ficheiro ?",
			"confirmCloseForm"=>"Você quer fechar o formulário?",
			"delete"=>"Deletar",
			"confirmDelete"=>"Confirmar eliminação ?",
			"confirmDeleteAlert"=>"Atenção : esta ação é definitiva !",
			"confirmDeleteNotify"=>"A eliminação foi bem-sucedida",
			"confirmDeleteSelect"=>"Você quer excluir permanentemente a seleção?",
			"confirmDeleteSelectNb"=>"itens selecionados",
			"confirmDeleteFolder"=>"Algumas subpastas não lhe estão acessíveis: pode confirmar isso mesmo assim ?",
			"confirmDeleteWait"=>"Aguarde um momento: a eliminação da pasta pode demorar alguns segundos",
			"notifDeleteFolderUncomplete"=>"Alguns itens não foram excluídos porque você não tem os direitos de acesso necessários",

			////	imagens
			"picture"=>"Foto",
			"pictureProfil"=>"Foto de perfil",
			"wallpaper"=>"Wallpaper",
			"keepImg"=>"Manter a imagem",
			"changeImg"=>"Mudar a imagem",
			"pixels"=>"pixels",

			////	Conexão
			"specifyLoginPassword"=>"Por favor, informe um nome de usuário e senha",
			"specifyLogin"=>"Por favor, informe um E-mail/Identificador (sem espaço)",
			"mailLloginNotif"=>"Recomenda-se usar um e-mail como identificador de sessão",
			"mailLlogin"=>"E-mail / Login ID",
			"connect"=>"Entrar",
			"connectAuto"=>"Fique ligado",
			"connectAutoTooltip"=>"Lembre-se dos meus dados de login para ligação automática",
			"gIdentityUserUnknown"=>"Não está registrado no espaço",
			"connectSpaceSwitch"=>"Conecte-se a outro espaço",
			"guestAccess"=>"Login como convidado",
			"guestAccessTooltip"=>"Login neste espaço como convidado",
			"publicSpacePasswordError"=>"Senha incorreta",
			"disconnectSpace"=>"Fechar Sessão",
			"disconnectSpaceConfirm"=>"Desconexão do espaço?",

			////	Password : connexion d'user / edition d'user / reset du password
			"password"=>"Senha",
			"passwordModify"=>"Alterar a senha",
			"passwordToModify"=>"Senha temporária (para alterar no login)",
			"passwordToModify2"=>"Senha (altere se necessário)",
			"passwordVerif"=>"confirmar senha",
			"passwordTooltip"=>"Deixe em branco se quiser manter sua senha",
			"passwordInvalid"=>"Sua senha deve conter números, letras e pelo menos 6 caracteres",
			"passwordVerifError"=>"Sua senha de confirmação não é válida",
			"specifyPassword"=>"Por favor, informe uma senha",
			"resetPassword"=>"Recuperar acesso",
			"resetPassword2"=>"Digite seu endereço de e -mail para receber seus dados de acesso",
			"resetPasswordNotif"=>"Você acabou de enviar um e-mail para o seu endereço para restaurar sua senha. Se não recebeu um e-mail, verifique se o endereço especificado está correto ou se o e-mail não está na sua caixa de SPAM.",
			"resetPasswordMailTitle"=>"Redefina sua senha",
			"resetPasswordMailPassword"=>"Para fazer login no seu Omnispace e restaurar sua senha",
			"resetPasswordMailPassword2"=>"Clique aqui",
			"resetPasswordMailLoginRemind"=>"Lembrete do seu login",
			"resetPasswordIdExpired"=>"O link da web para recuperar a senha expirou... Por favor, reinicie o procedimento",

			////	Type d'affichage
			"displayMode"=>"Visualização",
			"displayMode_line"=>"Lista",
			"displayMode_block"=>"Bloco",

			////	Sélectionner / Déselectionner tous les éléments
			"select"=>"Selecionar",
			"selectUnselect"=>"Marcar / Desmarcar",
			"selectAll"=>"Selecionar tudo",
			"selectNone"=>"Desmarcar tudo",
			"selectSwitch"=>"Alternar seleção",
			"deleteElems"=>"Remover os itens selecionados",
			"changeFolder"=>"Mover em outra pasta",
			"showOnMap"=>"Mostrar em um mapa",
			"showOnMapTooltip"=>"Veja em um mapa os contatos com um endereço, código postal, cidade",
			"notifSelectUser"=>"Obrigado por selecionar um usuário",
			"notifSelectUsers"=>"Obrigado por selecionar pelo menos 2 usuários",
			"selectSpace"=>"Obrigado por selecionar pelo menos um espaço",
			"visibleAllSpaces"=>"Visível em todos os espaços",/*cf. Categories, themes, etc*/
			"visibleOnSpace"=>"Visível no espaço",/*"..Mon espace"*/
			
			////	Temps ("de 11h à 12h", "le 25-01-2007 à 10h30", etc.)
			"from"=>"de ",
			"at"=>"para",
			"begin"=>"Começo",
			"end"=>"Fim",
			"beginEnd"=>"Começo / Fim",
			"days"=>"dias",
			"day_1"=>"Segunda-feira",
			"day_2"=>"Terça-feira",
			"day_3"=>"Quarta-feira",
			"day_4"=>"Quinta-feira",
			"day_5"=>"Sexta-feira",
			"day_6"=>"Sábado",
			"day_7"=>"Domingo",
			"month_1"=>"Janeiro",
			"month_2"=>"Fevereiro",
			"month_3"=>"Março",
			"month_4"=>"Abril",
			"month_5"=>"Maio",
			"month_6"=>"Junho",
			"month_7"=>"Julho",
			"month_8"=>"Agosto",
			"month_9"=>"Setembro",
			"month_10"=>"Outubro",
			"month_11"=>"Novembro",
			"month_12"=>"Dezembro",
			"today"=>"Hoje",
			"displayToday"=>"Mostrar hoje",
			"beginEndError"=>"A data de início deve preceder a data de fim",
			"dateFormatError"=>"A data deve estar no formato dd/mm/aaaa",
			"timeFormatError"=>"A hora deve estar no formato HH:mm",
			
			////	Menus d'édition des objets et editeur tinyMce
			"title"=>"Título",
			"name"=>"Nome",
			"description"=>"Descrição",
			"specifyName"=>"Obrigado por especificar um nome",
			"editorDraft"=>"Recuperar meu texto",
			"editorDraftConfirm"=>"Recuperar o último texto introduzido no editor",
			"editorFileInsert"=>"Adicionar imagem ou vídeo",
			"editorFileInsertNotif"=>"Selecione uma imagem em formato JPEG, PNG, GIF ou SVG",
			
			////	Validation des formulaires
			"add"=>"Adicionar",
			"modify"=>"Modificar",
			"record"=>"Gravar",
			"modifyAndAccesRight"=>"Modificar e definir acesso",
			"validate"=>"Validar",
			"send"=>"Enviar",
			"sendTo"=>"Enviar para",
			
			////	Tri d'affichage. Tous les elements (dossier, tache, lien, etc...) ont par défaut une date, un auteur & une description
			"sortBy"=>"Classificado por",
			"sortBy2"=>"Ordenar por",
			"SORT_dateCrea"=>"data de criação",
			"SORT_dateModif"=>"Data de modificação",
			"SORT_title"=>"título",
			"SORT_description"=>"descrição",
			"SORT__idUser"=>"autor",
			"SORT_extension"=>"tipo de arquivo",
			"SORT_octetSize"=>"tamanho",
			"SORT_downloadsNb"=>"transferências",
			"SORT_civility"=>"título",
			"SORT_name"=>"sobrenome",
			"SORT_firstName"=>"primeiro nome",
			"SORT_adress"=>"endereço",
			"SORT_postalCode"=>"CEP",
			"SORT_city"=>"cidade",
			"SORT_country"=>"país",
			"SORT_function"=>"função",
			"SORT_companyOrganization"=>"Empresa / Organização",
			"SORT_lastConnection"=>"Último Login",
			"SORT_ascend"=>"Ascendente",
			"SORT_descend"=>"Descendente",
			
			////	Visibilité d'un Objet
			"guest"=>"Convidado",
			"createdBy"=>"Criado por",
			"modifBy"=>"Modificado por",
			"objHistory"=>"História do item",
			"all"=>"todos",
			"deletedUser"=>"conta de usuário excluída",
			"folderContent"=>"conteúdo",
			"accessRead"=>"Ler",
			"accessReadTooltip"=>"Acesso na leitura",
			"accessWriteLimit"=>"Escrita limitada",
			"accessWriteLimitTooltip"=>"Acesso de gravação limitado: é possível adicionar -OBJCONTENT- em --OBJLABEL--,<br> mas cada usuário pode apenas modificar/excluir o -OBJCONTENT- que ele criou.",
			"accessWrite"=>"escrita",
			"accessWriteTooltip"=>"Acesso à escrita",
			"accessWriteTooltipContainer"=>"Acesso à escrita: Possibilidade de adicionar, modificar ou suprimir todos os -OBJCONTENT- do --OBJLABEL--",
			"accessAutorPrivilege"=>"Somente o autor e os administradores podem alterar as licenças de acesso ou eliminar --OBJLABEL--",
			"accessRightsInherited"=>"Direitos de acesso herdado de --OBJLABEL--",
			"categoryNotifSpaceAccess"=>"só é acessível no espaço",
			"categoryNotifChangeOrder"=>"A ordem de visualização foi alterada.",

			////	Libellé des objets
			"OBJECTcontainer"=>"recipiente",
			"OBJECTelement"=>"item",
			"OBJECTfolder"=>"pasta",
			"OBJECTdashboardNews"=>"notícias",
			"OBJECTdashboardPoll"=>"enquete",
			"OBJECTfile"=>"arquivo",
			"OBJECTfileFolder"=>"pasta",
			"OBJECTcalendar"=>"calendário",
			"OBJECTcalendarEvent"=>"evento",
			"OBJECTforumSubject"=>"tópico",
			"OBJECTforumMessage"=>"mensagem",
			"OBJECTcontact"=>"contato",
			"OBJECTcontactFolder"=>"pasta",
			"OBJECTlink"=>"favorito",
			"OBJECTlinkFolder"=>"pasta",
			"OBJECTtask"=>"tarefa",
			"OBJECTtaskFolder"=>"pasta",
			"OBJECTuser"=>"usuário",

			////	Envoi d'un e-mail
			"MAIL_sendOk"=>"O e-mail foi enviado com sucesso",
			"MAIL_sendNotOk"=>"Não foi possível enviar o e-mail...",
			"MAIL_recipients"=>"Destinatários",
			"MAIL_hello"=>"Olá",
			"MAIL_hideRecipients"=>"Ocultar destinatários",
			"MAIL_hideRecipientsTooltip"=>"Coloque todos os destinatários em uma cópia oculta. Observe que, com esta opção, seu e-mail pode chegar como SPAM em alguns mensageiros",
			"MAIL_addReplyTo"=>"Coloque meu e-mail em resposta",
			"MAIL_addReplyToTooltip"=>"Adicione meu e-mail no campo 'Responder a'. Observe que, com esta opção, seu e-mail pode chegar como SPAM em alguns mensageiros",
			"MAIL_noFooter"=>"Não assine a mensagem",
			"MAIL_noFooterTooltip"=>"Não assine o final da mensagem com o nome do remetente e um link para o espaço",
			"MAIL_receptionNotif"=>"Confirmação de entrega",
			"MAIL_receptionNotifTooltip"=>"Aviso! Alguns clientes de e-mail não oferecem suporte ao recibo de entrega",
			"MAIL_specificMails"=>"Adicionar endereços de e-mail",
			"MAIL_specificMailsTooltip"=>"Adicionar endereços de e-mail não listados no espaço",
			"MAIL_maxFileSizeConfirm"=>"O conjunto de ficheiros anexados excede o limite de receção de algumas caixas de correio (--MAXFILESSIZE--)<br><br> Enviar na mesma?",
			"MAIL_maxFileSizeNotif"=>"O arquivo não foi adicionado ao e-mail porque é muito grande",
			"MAIL_sendMail"=>"Enviar e-mail",
			"MAIL_sendBy"=>"Enviado por",
			"MAIL_sendNotif"=>"O e-mail de notificação foi enviado!",
			"MAIL_fromTheSpace"=>"Do espaço",
			"MAIL_elemCreatedBy"=>"--OBJLABEL-- criado por",
			"MAIL_elemModifiedBy"=>"--OBJLABEL-- modificado por",
			"MAIL_elemAccessLink"=>"Clique aqui para acessar o item no espaço",

			////	Dossier & fichier
			"gigaOctet"=>"GB",
			"megaOctet"=>"MB",
			"kiloOctet"=>"KB",
			"rootFolder"=>"Diretório raiz",
			"rootFolderTooltip"=>"Abra a configuração do espaço para alterar os direitos de acesso à pasta raiz",
			"addFolder"=>"Adicionar um diretório",
			"download"=>"Baixar arquivos",
			"downloadFolder"=>"Baixar a pasta",
			"diskSpaceUsed"=>"Espaço usado",
			"diskSpaceUsedModFile"=>"Espaço usado para arquivos",
			"downloadAlert"=>"Seu arquivo é grande demais para baixá-lo durante o dia (--ARCHIVE_SIZE--). Reinicie o download depois de",
			"downloadBackToApp"=>"Voltar para a aplicação",
			
			////	Infos sur une personne
			"civility"=>"Civilidade",
			"name"=>"Apelido",
			"firstName"=>"Nome",
			"adress"=>"Endereço",
			"postalCode"=>"Código postal",
			"city"=>"Cidade",
			"country"=>"País",
			"telephone"=>"Telefone",
			"telmobile"=>"Celular",
			"mail"=>"E-mail",
			"function"=>"Função",
			"companyOrganization"=>"Empresa / Organização",
			"lastConnection"=>"Última ligação",
			"notConnected"=>"Ainda não está ligado",
			"connectedToday"=>"Ligado hoje",
			"connectedThe"=>"Ligou o",
			"displayProfil"=>"Ver perfil",
			
			////	Captcha
			"captcha"=>"Copiar os 5 caracteres",
			"captchaTooltip"=>"Escreva os 5 caracteres para identificação",
			"captchaError"=>"A identificação visual não é válida",
			
			////	Rechercher
			"searchSpecifyText"=>"Especifique pelo menos 3 caracteres (alfanumérico e sem caracteres especiais)",
			"search"=>"Buscar",
			"searchOnSpace"=>"Buscar pelo espaço",
			"searchDateCrea"=>"Data de criação",
			"searchDateCreaDay"=>"menos de um dia",
			"searchDateCreaWeek"=>"menos de uma semana",
			"searchDateCreaMonth"=>"menos de um mês",
			"searchDateCreaYear"=>"menos de um ano",
			"advancedSearch"=>"Busca avançada",
			"advancedSearchAnyWord"=>"qualquer palavra",
			"advancedSearchAllWords"=>"todas as palavras",
			"advancedSearchExactPhrase"=>"Frase exata",
			"keywords"=>"Palavras-chave",
			"listModules"=>"Módulos",
			"listFields"=>"Campos",
			"listFieldsElems"=>"Elementos envolvidos",
			"noResults"=>"Não há resultados",
			
			////	Inscription d'utilisateur
			"userInscription"=>"Registre-se no espaço",
			"userInscriptionTooltip"=>"Criar uma nova conta de usuário (validada por um administrador)",
			"userInscriptionSpace"=>"Registre-se no espaço",
			"userInscriptionRecorded"=>"Seu registro será validado o mais rápido possível pelo administrador do espaço",
			"userInscriptionEmailSubject"=>"Novo registro no espaço",
			"userInscriptionEmailMessage"=>"<i>--NEW_USER_LABEL--</i> solicitou um novo registro para o espaço <i>--SPACE_NAME--</i> : <br><br><i>--NEW_USER_MESSAGE--<i> <br><br>Lembre-se de validar ou invalidar esse registro durante sua próxima conexão.",
			"userInscriptionEdit"=>"Permitir que os visitantes se registrem no espaço",
			"userInscriptionEditTooltip"=>"O registro está na página inicial. Deve ser validado pelo administrador do espaço.",
			"userInscriptionNotif"=>"Notificar por e-mail em cada registro",
			"userInscriptionNotifTooltip"=>"Envie uma notificação por e-mail aos administradores de espaço, após cada registro",
			"userInscriptionValidate"=>"Registros de usuários",
			"userInscriptionValidateTooltip"=>"Validar registros de usuário para o espaço",
			"userInscriptionSelectValidate"=>"Validar registros",
			"userInscriptionSelectInvalidate"=>"Invalidar registros",
			"userInscriptionInvalidateMail"=>"Sua conta não foi validada em",
			
			////	Importer ou Exporter : Contact OU Utilisateurs
			"importExport_user"=>"Importar / Exportar usuários",
			"import_user"=>"Importar usuários no espaço atual",
			"export_user"=>"Exportar usuários do espaço",
			"importExport_contact"=>"Importar / Exportar contatos",
			"import_contact"=>"Importar contatos na pasta atual",
			"export_contact"=>"Exportar contatos da pasta atual",
			"exportFormat"=>"formato",
			"specifyFile"=>"Por favor, especifique um arquivo",
			"fileExtension"=>"O tipo de arquivo não é válido. Deve ser do tipo",
			"importContactRootFolder"=>"Os contatos serão atribuídos por padrão a &quot;todos os usuários do espaço&quot;",
			"importInfo"=>"Selecione os campos (Agora) do destino com as listas de suspensão de cada coluna.",
			"importNotif1"=>"Por favor, selecione a coluna de nome nas listas de suspensão",
			"importNotif2"=>"Por favor, selecione pelo menos um contato para importar",
			"importNotif3"=>"O campo Agora já foi selecionado em outra coluna (cada campo Agora pode ser selecionado apenas uma vez)",
			
			////	Messages d'erreur / Notifications
			"NOTIF_identification"=>"Nome de usuário ou senha inválida",
			"NOTIF_presentIp"=>"Esta conta de usuário está sendo usada atualmente em outro computador, com outro endereço IP",
			"NOTIF_noAccessNoSpaceAffected"=>"Sua conta de usuário foi identificada corretamente, mas atualmente não está atribuída a nenhum espaço. Entre em contato com o administrador",
			"NOTIF_noAccess"=>"Você não está logado",
			"NOTIF_fileOrFolderAccess"=>"O arquivo ou pasta não está disponível",
			"NOTIF_diskSpace"=>"O espaço para armazenar seus arquivos não é suficiente, você não pode adicionar arquivos",
			"NOTIF_fileVersionForbidden"=>"Tipo de arquivo não permitido",
			"NOTIF_fileVersion"=>"Tipo de arquivo diferente do original",
			"NOTIF_folderMove"=>"Você não pode mover a pasta para dentro de si mesma!",
			"NOTIF_duplicateName"=>"Um item com o mesmo nome já existe",
			"NOTIF_duplicateNameFolder"=>"Já existe uma pasta com o mesmo nome",
			"NOTIF_fileName"=>"Um arquivo com o mesmo nome já existe (não foi substituído)",
			"NOTIF_chmodDATAS"=>"O diretório 'DATAS' não permite acesso de escrita. Você precisa dar um acesso de leitura e escrita para o proprietário e o grupo (''chmod 775'').",
			"NOTIF_usersNb"=>"Você não pode adicionar um novo usuário: é limitado a ",
			
			////	Header
			"HEADER_displaySpace"=>"Espaços de trabalho",
			"HEADER_displayAdmin"=>"Visualização de Administrador",
			"HEADER_displayAdminInfo"=>"Permite exibir itens no espaço que não me estão directamente atribuídos : pastas, calendários, etc.",
			"HEADER_displayAdminEnabled"=>"Visualização do administrador ativada",
			"HEADER_displayAdminDisabled"=>"Visualização do administrador desativada",
			"HEADER_documentation"=>"Documentação",
			"HEADER_shortcuts"=>"Acesso direto",

			////	Messenger / Visio
			"MESSENGER_MODULE_NAME"=>"Mensagens",
			"MESSENGER_MODULE_DESCRIPTION"=>"Converse ou inicie uma videoconferência com pessoas online",
			"MESSENGER_messengerMultiUsers"=>"Falar com várias pessoas no sistema de mensagens (painel esquerdo para selecionar os destinatários)",
			"MESSENGER_chatWithMulti"=>"Falar com",
			"MESSENGER_chatWith"=>"Converse ou inicie uma videoconferência com",
			"MESSENGER_messageFrom"=>"Mensagem de",
			"MESSENGER_messageSentTo"=>"enviado para",
			"MESSENGER_messageToSelected"=>"Mensagem para pessoas selecionadas",
			"MESSENGER_messageTo"=>"Mensagem para",
			"MESSENGER_addMessageNotif"=>"Especifique uma mensagem",
			"MESSENGER_visioProposeTo"=>"Propor uma videoconferência para",
			"MESSENGER_visioProposeToSelection"=>"Propor uma videoconferência para as pessoas selecionadas",
			"MESSENGER_visioProposeToUsers"=>"Clique aqui para iniciar a videoconferência entre",
			"MESSENGER_nobody"=>"Nenhum outro utilizador está ligado de momento",
			
			////	Lancer une Visio
			"VISIO_urlAdd"=>"Adicionar uma videoconferência",
			"VISIO_urlAddConfirm"=>"Adicionar um link ao final do texto para iniciar uma nova videoconferência ?",
			"VISIO_urlCopy"=>"Copiar o link de videoconferência",
			"VISIO_urlDelete"=>"Eliminar o link de videoconferência",
			"VISIO_launch"=>"Iniciar a videoconferências",
			"VISIO_launchJitsi"=>"Inicie a videoconferências <br>com a aplicação Jitsi",
			"VISIO_launchFromEvent"=>"Iniciar a videoconferência deste evento",
			"VISIO_launchTooltip"=>"Lembre-se de permitir o acesso à sua webcam e microfone",
			"VISIO_launchTooltip2"=>"Clique aqui se tiver problemas para começar a videoconferência",
			"VISIO_launchServerTooltip"=>"Escolha o servidor secundário se o servidor principal não funcionar corretamente.<br>Seus contatos devem selecionar o mesmo servidor de vídeo.",
			"VISIO_launchServerMain"=>"Servidor principal",
			"VISIO_launchServerAlt"=>"Servidor secundário",

			////	VueObjMenuEdit.php
			"EDIT_notifNoSelection"=>"Você deve selecionar ao menos uma pessoa ou um espaço",
			"EDIT_notifNoPersoAccess"=>"Você não foi designado para o item. Validar todos mesmo assim?",
			"EDIT_parentFolderAccessError"=>"Verifique os direitos de acesso da pasta principal <br><i>--FOLDER_NAME--</i><br><br> Também deve haver um direito de acesso a <br><i>--SPACE_LABEL--</ i> &nbsp;>&nbsp; <i>--TARGET_LABEL--</i><br><br> Caso contrário, este arquivo não pode ser acessado!",
			"EDIT_accessRight"=>"Direitos de acesso",
			"EDIT_accessRightContent"=>"Direitos de Acesso ao Conteúdo",
			"EDIT_spaceNoModule"=>"O módulo atual ainda não foi adicionado a este espaço",
			"EDIT_allUsers"=>"Todos os usuários",
			"EDIT_allUsersTooltip"=>"Direito de acesso de todos os utilizadores do espaço <i>--SPACENAME--</i>",
			"EDIT_allUsersAndGuests"=>"Todos os utilizadores e convidados",
			"EDIT_allUsersAndGuestsTooltip"=>"Direito de acesso para todos os utilizadores e convidados do espaço <i>--SPACENAME--</i>.<hr>Os convidados apenas têm acesso de leitura ao espaço (pessoas sem conta de utilizador)",
			"EDIT_adminSpace"=>"Administrador do espaço:<br>Acesso de escrita a todos os itens do espaço",
			"EDIT_showAllUsers"=>"Mostrar todos os usuários",
			"EDIT_showAllUsersAndSpaces"=>"Mostre todos os usuários e espaços",
			"EDIT_notifMail"=>"Notificar",
			"EDIT_notifMail2"=>"Envie uma notificação de criação/alteração por e-mail",
			"EDIT_notifMailTooltip"=>"A notificação será enviada para as pessoas designadas para o item (--OBJLABEL--)",
			"EDIT_notifMailTooltipCal"=>"<hr>Se você atribuir o evento a calendários pessoais, a notificação será enviada apenas aos proprietários desses calendários (acesso a escrita).",
			"EDIT_notifMailAddFiles"=>"Anexar arquivos à notificação",
			"EDIT_notifMailSelect"=>"Selecionar os destinatários das notificações",
			"EDIT_accessRightSubFolders"=>"Dar direitos iguais a todas as subpastas",
			"EDIT_accessRightSubFoldersTooltip"=>"Estender os direitos de acesso a subpastas que podem ser editadas",
			"EDIT_shortcut"=>"Acesso direto",
			"EDIT_shortcutInfo"=>"Mostrar acesso direto no menu principal",
			"EDIT_attachedFile"=>"Arquivos anexados",
			"EDIT_attachedFileAdd"=>"Adicionar arquivos",
			"EDIT_attachedFileInsert"=>"Inserir em texto",
			"EDIT_attachedFileInsertTooltip"=>"Inserir imagem/vídeo no texto do editor (formato jpg, png ou mp4)",
			"EDIT_guestName"=>"Seu nome / apelido",
			"EDIT_guestNameNotif"=>"Por favor, especifique um nome / apelido",
			"EDIT_guestMail"=>"Seu e-mail",
			"EDIT_guestMailTooltip"=>"Especifique seu e-mail para a validação de sua proposta",
			"EDIT_guestElementRegistered"=>"Obrigado pela sua proposta: ela será examinada o mais rápido possível antes da validação",
			
			////	Formulaire d'installation
			"INSTALL_dbConnect"=>"Conexão do banco de dados",
			"INSTALL_dbHost"=>"Nome do servidor host (hostname)",
			"INSTALL_dbName"=>"Nome do banco de dados",
			"INSTALL_dbLogin"=>"Nome de usuário",
			"INSTALL_adminAgora"=>"Administrador do Ágora",
			"INSTALL_errorDbNameFormat"=>"Aviso: o nome do banco de dados deve conter apenas caracteres alfanuméricos, hífens ou sublinhados",
			"INSTALL_errorDbConnection"=>"Sem identificação com o banco de dados MariaDB/MySQL",
			"INSTALL_errorDbExist"=>"Aplicativo já instalado: <a href='index.php'>Clique aqui para acessar</a><br><br>Para reiniciar a instalação, lembre-se de excluir o banco de dados",
			"INSTALL_errorDbNoSqlFile"=>"Você não pode acessar o arquivo de instalação do DB.SQL ou foi excluído porque a instalação já foi realizada",
			"INSTALL_PhpOldVersion"=>"Agora-Project --CURRENT_VERSION-- requer uma versão mais recente do PHP",
			"INSTALL_confirmInstall"=>"Confirmar a instalação?",
			"INSTALL_installOk"=>"Agora-Project foi instalado!",
			// Premiers enregistrements en DB
			"INSTALL_agoraDescription"=>"Espaço para troca e trabalho colaborativo",
			"INSTALL_dataDashboardNews"=>"<h3>Bem-vindo ao seu novo espaço de trabalho colaborativo !</h3>
											<h4 onclick=\"redir('?ctrl=file')\"><img src='app/img/file/iconSmall.png'>Partilhe os seus ficheiros com a sua equipa no gestor de ficheiros</h4>
											<h4 onclick=\"redir('?ctrl=calendar')\"><img src='app/img/calendar/iconSmall.png'> Crie eventos no seu calendário partilhado ou calendário pessoal</h4>
											<h4 onclick=\"redir('?ctrl=dashboard')\"><img src='app/img/dashboard/iconSmall.png'> Utilize o feed de notícias para transmitir informação sobre a sua atividade</h4>
											<h4 onclick=\"redir('?ctrl=forum')\"><img src='app/img/messenger.png'> Comunique através do fórum, mensagens ou videoconferências</h4>
											<h4 onclick=\"redir('?ctrl=task')\"><img src='app/img/task/iconSmall.png'> Gerir as suas tarefas e projetos para organizar a sua atividade</h4>
											<h4 onclick=\"redir('?ctrl=mail')\"><img src='app/img/mail/iconSmall.png'> Envie newsletters para distribuir e-mails informativos sobre a sua atividade.</h4>
											<h4 onclick=\"lightboxOpen('docs/DOCUMENTATION_FR.pdf?displayFile=true')\"><img src='app/img/documentation.png'> Consulte o manual do utilizador para descobrir o seu espaço de trabalho</h4>
											<h4 onclick=\"lightboxOpen('?ctrl=user&action=SendInvitation')\"><img src='app/img/mail.png'>Enviar convites por e-mail para participar no espaço</h4>",
			"INSTALL_dataDashboardPoll"=>"O que você acha da ferramenta de notícias?",
			"INSTALL_dataDashboardPollA"=>"Muito interessante!",
			"INSTALL_dataDashboardPollB"=>"Interessante",
			"INSTALL_dataDashboardPollC"=>"Sem interesse",
			"INSTALL_dataCalendarEvt"=>"Bem-vindo ao Omnispace",
			"INSTALL_dataForumSubject1"=>"Bem-vindo ao fórum do Omnispace",
			"INSTALL_dataForumSubject2"=>"Sinta-se à vontade para compartilhar suas perguntas ou discutir os problemas que você deseja.",
			"INSTALL_dataTaskStatus1"=>"Por fazer",
			"INSTALL_dataTaskStatus2"=>"Em andamento",
			"INSTALL_dataTaskStatus3"=>"A validar",
			"INSTALL_dataTaskStatus4"=>"Concluído",

			////	MOD : AGORA
			////
			"AGORA_generalSettings"=>"Administração Geral",
			"AGORA_Changelog"=>"Registro da versão",
			"AGORA_phpMailDisabled"=>"Função PHP Mail desativada",
			"AGORA_phpLdapDisabled"=>"Função PHP LDAP desativada",
			"AGORA_phpGD2Disabled"=>"Função PHP GD2 desativada",
			"AGORA_backupFull"=>"Backup completo",
			"AGORA_backupFullTooltip"=>"Recupere o backup completo do espaço: todos os arquivos e banco de dados",
			"AGORA_backupDb"=>"Faça um backup de banco de dados",
			"AGORA_backupDbTooltip"=>"Recupere apenas o backup do banco de dados espacial",
			"AGORA_backupConfirm"=>"Esta operação pode levar alguns minutos: continuar o download?",
			"AGORA_diskSpaceInvalid"=>"O espaço do disco para arquivos deve ser um número inteiro",
			"AGORA_visioHostInvalid"=>"O endereço da web do seu servidor de videoconferência não é válido: você deve começar com 'https'",
			"AGORA_gApiKeyInvalid"=>"Se escolher Google Map como ferramenta de mapa, deve especificar uma 'API Key'",
			"AGORA_gIdentityKeyInvalid"=>"Se você escolher a conexão opcional através do Google, deve especificar uma 'API Key' para o Google SignIn",
			"AGORA_confirmModif"=>"Confirmar alterações ?",
			"AGORA_name"=>"Nome do espaço principal",
			"AGORA_nameTooltip"=>"Nome exibido na página de login, em e-mails, etc.",
			"AGORA_description"=>"Descrição na página de login",
			"AGORA_footerHtml"=>"Texto no canto inferior esquerdo de cada página",
			"AGORA_logo"=>"Logotipo no canto inferior direito de cada página",
			"AGORA_logoUrl"=>"URL",
			"AGORA_logoConnect"=>"Logotipo na página de login",
			"AGORA_logoConnectTooltip"=>"Logotipo exibido na parte superior do formulário de conexão",
			"AGORA_lang"=>"Idioma padrão",
			"AGORA_timezone"=>"Fuso horário",
			"AGORA_diskSpaceLimit"=>"Disco disponível para arquivos",
			"AGORA_logsTimeOut"=>"Duração do histórico de eventos (registros)",
			"AGORA_logsTimeOutTooltip"=>"O período de retenção do histórico de eventos diz respeito à adição ou modificação de elementos. Os registros de exclusão são mantidos por no mínimo 1 ano.",
			"AGORA_visioHost"=>"Servidor web de videoconferência Jitsi",
			"AGORA_visioHostTooltip"=>"URL do servidor principal de videoconferência. Exemplo : https://framatalk.org ou https://meet.jit.si",
			"AGORA_visioHostAlt"=>"Servidor alternativo de videoconferência",
			"AGORA_visioHostAltTooltip"=>"URL do servidor alternativo de videoconferência: em caso de indisponibilidade do servidor Jitsi principal",
			"AGORA_skin"=>"Cor da interface",
			"AGORA_black"=>"Modo escuro",
			"AGORA_white"=>"Modo claro",
			"AGORA_userMailDisplay"=>"Endereços de e-mail dos usuários visíveis para todos",
			"AGORA_userMailDisplayTooltip"=>"Mostrar/ocultar e-mail no perfil de cada usuário, notificações por e-mail, etc.<br>Observação: o administrador principal sempre poderá visualizar o e-mail de cada usuário",
			"AGORA_moduleLabelDisplay"=>"Nome dos módulos na barra de menu",
			"AGORA_folderDisplayMode"=>"Visualização de pasta padrão",
			"AGORA_wallpaperLogoError"=>"O papel de parede e o logotipo devem estar no formato .jpg ou .png",
			"AGORA_deleteWallpaper"=>"Remover papel de parede",
			"AGORA_usersCommentLabel"=>"Botão 'Comentário' nos itens",
			"AGORA_usersComment"=>"Comente",
			"AGORA_usersComments"=>"comentários",
			"AGORA_usersLikeLabel"=>"Botão 'Eu gosto' nos itens",
			"AGORA_usersLike"=>"Eu gosto !",
			"AGORA_mapTool"=>"Ferramenta de mapeamento",
			"AGORA_mapToolTooltip"=>"Ferramenta de mapeamento para exibir usuários e contatos em um mapa",
			"AGORA_gApiKey"=>"Chave API da Google para Maps e importação de contactos",
			"AGORA_gApiKeyTooltip"=>"Configuração para Google Maps :<br> https://developers.google.com/maps/documentation/javascript/get-api-key",
			"AGORA_gIdentity"=>"Opção de login via Google",
			"AGORA_gIdentityTooltip"=>"Usuários com um identificador com endereço <i>@gmail.com</i> também poderão se conectar por meio de sua conta do Google",
			"AGORA_gIdentityClientId"=>"Chave API para login via Google",
			"AGORA_gIdentityClientIdTooltip"=>"É necessária uma 'chave API' para conexão via Google. Mais informações em <a href='https://developers.google.com/identity/sign-in/web' target='_blank'>https://developers.google.com/identity/sign-in/web</a>",
			"AGORA_messengerDisplay"=>"Mensagem instantânea",
			"AGORA_personsSort"=>"Classifique usuários e contatos por",
			//SMTP
			"AGORA_smtpLabel"=>"Conexão SMTP & sendMail",
			"AGORA_sendmailFrom"=>"E-mail 'De'",
			"AGORA_sendmailFromPlaceholder"=>"ex: 'noreply@mydomain.com'",
			"AGORA_smtpHost"=>"Endereço do servidor (hostname)",
			"AGORA_smtpPort"=>"Porta do servidor",
			"AGORA_smtpPortTooltip"=>"'25' por padrão. '587' ou '465' para SSL/TLS",
			"AGORA_smtpSecure"=>"Tipo de conexão segura (opcional)",
			"AGORA_smtpSecureTooltip"=>"'ssl' ou 'tls'",
			"AGORA_smtpUsername"=>"Nome do usuário",
			"AGORA_smtpPass"=>"Senha",
			//LDAP
			"AGORA_ldapLabel"=>"Conexão a um servidor LDAP",
			"AGORA_ldapLabelTooltip"=>"Conexão a um servidor LDAP para a criação de usuários no espaço: cf. Opção ''Importação/exportação de usuários'' do módulo ''Usuário''",
			"AGORA_ldapUri"=>"URI LDAP",
			"AGORA_ldapUriTooltip"=>"URI do LDAP completo no formato LDAP://hostname:port ou LDAPS://hostname:port para a criptografia SSL.",
			"AGORA_ldapPort"=>"Porta do servidor",
			"AGORA_ldapPortTooltip"=>"A porta usada para a conexão: '' 389 '' por padrão",
			"AGORA_ldapLogin"=>"DN do administrador LDAP (Distinguished Name)",
			"AGORA_ldapLoginTooltip"=>"por exemplo ''cn=admin,dc=mon-entreprise,dc=com''",
			"AGORA_ldapPass"=>"Senha do administrador",
			"AGORA_ldapDn"=>"DN do grupo de usuários (Distinguished Name)",
			"AGORA_ldapDnTooltip"=>"DN do grupo de usuários: localização dos usuários no diretório. Exemplo ''ou=mon-groupe,dc=mon-entreprise,dc=com''",
			"importLdapFilterTooltip"=>"Filtro de pesquisa LDAP (cf. https://www.php.net/manual/function.ldap-search.php). Exemplo ''(cn=*)'' ou ''(&(samaccountname=MONLOGIN)(cn=*))''",
			"AGORA_ldapConnectError"=>"Erro de conexão do servidor LDAP!",

			////	MOD : LOG
			////
			"LOG_MODULE_DESCRIPTION"=>"Logs - Registro de eventos",
			"LOG_path"=>"Caminho",
			"LOG_filter"=>"Filtro",
			"LOG_date"=>"Data e hora",
			"LOG_spaceName"=>"Espaço",
			"LOG_moduleName"=>"Módulo",
			"LOG_objectType"=>"Tipo de objeto",
			"LOG_action"=>"Ação",
			"LOG_userName"=>"Usuário",
			"LOG_ip"=>"IP",
			"LOG_comment"=>"Comentário",
			"LOG_noLogs"=>"Sem registro",
			"LOG_filterSince"=>"filtrado desde",
			"LOG_search"=>"Buscar",
			"LOG_connexion"=>"conexão",
			"LOG_add"=>"adicionar",
			"LOG_delete"=>"eliminar",
			"LOG_modif"=>"modificação",

			////	MOD : SPACE
			////
			"SPACE_moduleTooltip"=>"O espaço principal pode ser subdividido em vários espaços (consulte ''subespaço'')",
			"SPACE_manageAllSpaces"=>"Administrar todos os espaços",
			"SPACE_config"=>"Administração do Espaço",
			"SPACE_space"=>"Espaço",
			"SPACE_spaces"=>"Espaços",
			"SPACE_accessRightUndefined"=>"Definir",
			"SPACE_modules"=>"Módulos",
			"SPACE_addSpace"=>"Adicionar um espaço",
			//Edit
			"SPACE_userAdminAccess"=>"Usuários e administradores do espaço",
			"SPACE_selectModule"=>"Você deve selecionar pelo menos um módulo",
			"SPACE_spaceModules"=>"Módulos do espaço",
			"SPACE_publicSpace"=>"Espaço público: acesso de convidado",
			"SPACE_publicSpaceTooltip"=>"Um espaço público está aberto a pessoas que não têm uma conta de usuário (convidados). Eles podem acessar o espaço da página inicial. Você pode especificar uma senha para proteger o acesso a esse espaço público. Os módulos 'E-mails' e 'Usuarios' não estão disponíveis para os convidados.",
			"SPACE_publicSpaceNotif"=>"Seu espaço é público: se ele contiver dados pessoais (telefone, endereço etc.), lembre-se de especificar uma senha para cumprir a LGPD: Lei Geral de Proteção de Dados",
			"SPACE_usersInvitation"=>"Os usuários podem enviar convites por correio",
			"SPACE_usersInvitationTooltip"=>"Todos os usuários podem enviar e-mail para participar do espaço",
			"SPACE_allUsers"=>"Todos os usuários",
			"SPACE_user"=>"Usuários",
			"SPACE_userTooltip"=>"Usuário do espaço: <br> Acesso normal ao espaço",
			"SPACE_admin"=>"Administrador",
			"SPACE_adminTooltip"=>"O administrador de um espaço é um usuário que pode editar ou eliminar todos os itens presentes no espaço. Você também pode configurar o espaço, criar novas contas de usuário, criar grupos de usuários, enviar e-mail para adicionar novos usuários, etc.",

			////	MOD : USER
			////
			"USER_MODULE_NAME"=>"Usuários",
			"USER_MODULE_DESCRIPTION"=>"Usuários do espaço",
			"USER_OPTION_allUsersAddGroup"=>"Os usuários também podem criar grupos",
			"USER_spaceOrAllUsersTooltip"=>"Gerenciar usuários do espaço atual / Gerenciar usuários de todos os espaços (reservado ao administrador geral)",
			"USER_spaceUsers"=>"Gerir os utilizadores do espaço",
			"USER_allUsers"=>"Gerir todos os utilizadores",
			"USER_deleteDefinitely"=>"Deletar definitivamente",
			"USER_deleteFromCurSpace"=>"Desatribuir ao espaço atual",
			"USER_deleteFromCurSpaceConfirm"=>"Cancelar atribuição ao usuário do espaço atual?",
			"USER_user"=>"Usuário",
			"USER_users"=>"Usuários",
			"USER_addExistUser"=>"Adicionar um usuário existente, a esse espaço",
			"USER_addExistUserTitle"=>"Adicionar ao espaço um usuário existente no site: atribuição de espaço",
			"USER_addUser"=>"Adicionar um usuário",
			"USER_addUserSite"=>"Crie um usuário no site: padrão, atribuído a qualquer espaço!",
			"USER_addUserSpace"=>"Crie um usuário no espaço atual",
			"USER_sendCoords"=>"Envie o nome de usuário e a senha",
			"USER_sendCoordsTooltip"=>"Envie aos usuários um e-mail com seu login e um link da web para inicializar sua senha",
			"USER_sendCoordsTooltip2"=>"Envie a cada novo usuário um e-mail com informações de acesso.",
			"USER_sendCoordsConfirm"=>"Confirmar?",
			"USER_sendCoordsMail"=>"Seus dados de acesso ao seu espaço",
			"USER_noUser"=>"Nenhum usuário atribuído a este espaço no momento",
			"USER_spaceList"=>"Espaços do usuário",
			"USER_spaceNoAffectation"=>"Sem espaço",
			"USER_adminGeneral"=>"Administrador geral do site",
			"USER_adminGeneralTooltip"=>"Atenção: O direito de acesso ''administrador geral'' concede muitos privilégios e responsabilidades, em particular para editar todos os itens (calendários, pastas, arquivos, etc.), bem como todos os usuários e espaços. Portanto, é aconselhável atribuir este privilégio a no máximo 2 ou 3 usuários.<br><br>Para privilégios mais restritos, escolha o direito de acesso ''administrador do espaço'' (ver menu principal > ''Configurar o espaço'' )",
			"USER_adminSpace"=>"Administrador do espaço",
			"USER_userSpace"=>"Usuário do espaço",
			"USER_profilEdit"=>"Editar o perfil",
			"USER_myProfilEdit"=>"Editar meu perfil de usuário",
			// Invitation
			"USER_sendInvitation"=>"Envie convites por e-mail",
			"USER_sendInvitationTooltip"=>"Envie os convites por e-mail para aderir ao espaço atual :<br> Assim que um convite é validado, é automaticamente criada uma conta de utilizador para a pessoa em questão",
			"USER_mailInvitationObject"=>"Convite de",
			"USER_mailInvitationFromSpace"=>"convida você para ",
			"USER_mailInvitationConfirm"=>"Clique aqui para confirmar o convite",
			"USER_mailInvitationWait"=>"Convites para confirmar",
			"USER_exired_idInvitation"=>"O link do seu convite expirou",
			"USER_invitPassword"=>"Confirmar seu convite",
			"USER_invitPassword2"=>"Escolha sua senha para confirmar seu convite",
			"USER_invitationValidated"=>"Seu convite foi validado!",
			"USER_gPeopleImport"=>"Obtener mis contactos de mi dirección de Gmail",
			"USER_quotaExceeded"=>"Quota de utentes atingida. Entre em contacto com o administrador do espaço.",
			"USER_importQuotaExceeded"=>"Está limitado a --USERS_QUOTA_REMAINING-- novas contas de usuário, de um total de --LIMITE_NB_USERS-- usuários",
			// groupes
			"USER_spaceGroups"=>"Grupos de utilizadores",
			"USER_spaceGroupsEdit"=>"Editar grupos de utilizadores do espaço",
			"USER_groupEditInfo"=>"Lista de grupos que posso editar: autor do grupo ou administrador do espaço",
			"USER_addGroup"=>"Adicionar um grupo",
			"USER_userGroups"=>"Grupos do usuário",
			// Utilisateur_affecter
			"USER_searchPrecision"=>"Por favor, escolha um nome, sobrenome ou endereço de e-mail",
			"USER_userAffectConfirm"=>"Confirmar as atribuições?",
			"USER_userSearch"=>"Buscar usuários para adicionar ao espaço",
			"USER_allUsersOnSpace"=>"Todos os utilizadores são atribuídos ao espaço atual",
			"USER_usersSpaceAffectation"=>"Atribuir usuários ao espaço:",
			"USER_usersSearchNoResult"=>"Não há usuários para esta pesquisa",
			"USER_usersSearchBack"=>"Voltar",
			// Utilisateur_edit & CO
			"USER_langs"=>"Idioma",
			"USER_persoCalendarDisabled"=>"Calendário pessoal desativado",
			"USER_persoCalendarDisabledTooltip"=>"Um calendário pessoal é atribuído por padrão a cada usuário (mesmo que o módulo ''Calendario'' não esteja ativado no espaço). Marque esta opção para desabilitar o calendário pessoal deste usuário.",
			"USER_connectionSpace"=>"Espaço de conexão",
			"USER_loginExists"=>"O login/e-mail já existe. Por favor, escolha outro!",
			"USER_mailPresentInAccount"=>"Já existe uma conta de usuário com este endereço de e-mail",
			"USER_loginAndMailDifferent"=>"Ambos os endereços de e-mail devem ser idênticos",
			"USER_mailNotifObject"=>"Nova conta em",
			"USER_mailNotifContent"=>"Sua conta de usuário foi criada em",
			"USER_mailNotifContent2"=>"Conecte-se com o login e senha seguintes",
			"USER_mailNotifContent3"=>"Por favor, guarde este e-mail para seus registros.",
			// Edition du Livecounter/Messenger
			"USER_livecounterVisibility"=>"Visibilidade em mensagens",
			"USER_livecounterAllUsers"=>"Mostrar minha presença quando estou conectado: mensagens / vídeo habilitado",
			"USER_livecounterDisabled"=>"Esconder minha presença quando estou conectado: mensagens / vídeo desativado",
			"USER_livecounterSomeUsers"=>"Apenas certos usuários podem me ver quando estou conectado",

			////	MOD : DASHBOARD
			////	
			"DASHBOARD_MODULE_NAME"=>"Notícias",
			"DASHBOARD_MODULE_DESCRIPTION"=>"Notícias, Pesquisas e Itens recentes",
			"DASHBOARD_OPTION_adminAddNews"=>"Somente o administrador pode adicionar notícias",
			"DASHBOARD_OPTION_disablePolls"=>"Desativar pesquisas",
			"DASHBOARD_OPTION_adminAddPoll"=>"Somente o administrador pode adicionar pesquisas",
			"DASHBOARD_menuNews"=>"Notícias",
			"DASHBOARD_menuPolls"=>"Pesquisas",
			"DASHBOARD_menuElems"=>"Itens recentes e atuais",
			"DASHBOARD_addNews"=>"Adicionar uma notícia",
			"DASHBOARD_offlineNews"=>"Mostrar notícias arquivadas",
			"DASHBOARD_offlineNewsNb"=>"notícias arquivadas",
			"DASHBOARD_noNews"=>"Não há notícias no momento",
			"DASHBOARD_addPoll"=>"Adicionar uma pesquisa",
			"DASHBOARD_pollsVoted"=>"Mostrar apenas pesquisas votadas",
			"DASHBOARD_pollsVotedNb"=>"pesquisas nas quais já votei",
			"DASHBOARD_pollsNotVoted"=>"pesquisas não votadas",
			"DASHBOARD_vote"=>"Vote e veja os resultados",
			"DASHBOARD_voteTooltip"=>"Os votos são anônimos: ninguém saberá sua escolha de voto",
			"DASHBOARD_answerVotesNb"=>"Votada --NB_VOTES-- vezes",
			"DASHBOARD_pollVotesNb"=>"A pesquisa foi votada --NB_VOTES-- vezes",
			"DASHBOARD_pollVotedBy"=>"Votada por",
			"DASHBOARD_noPoll"=>"Não há pesquisa no momento",
			"DASHBOARD_plugins"=>"Novos itens",
			"DASHBOARD_pluginsTooltip"=>"Itens criados",
			"DASHBOARD_pluginsTooltip2"=>"entre",
			"DASHBOARD_plugins_day"=>"de hoje",
			"DASHBOARD_plugins_week"=>"desta semana",
			"DASHBOARD_plugins_month"=>"do mês",
			"DASHBOARD_plugins_previousConnection"=>"desde a última conexão",
			"DASHBOARD_pluginsTooltipRedir"=>"Ver o item na pasta",
			"DASHBOARD_pluginEmpty"=>"Não há novos itens para este período",
			// Actualite/News
			"DASHBOARD_topNews"=>"Principais notícias",
			"DASHBOARD_topNewsTooltip"=>"Notícias no topo da lista",
			"DASHBOARD_offline"=>"Notícia arquivada",
			"DASHBOARD_dateOnline"=>"online em",
			"DASHBOARD_dateOnlineTooltip"=>"Selecione uma data para colocar as notícias on-line automaticamente.<br>Enquanto isso, as notícias permanecem off-line",
			"DASHBOARD_dateOnlineNotif"=>"A notícia é momentaneamente arquivada",
			"DASHBOARD_dateOffline"=>"Data de arquivamento",
			"DASHBOARD_dateOfflineTooltip"=>"Selecione uma data para arquivar automaticamente as notícias",
			// Sondage/Polls
			"DASHBOARD_titleQuestion"=>"Título / Pergunta",
			"DASHBOARD_multipleResponses"=>"Várias respostas possíveis para cada voto",
			"DASHBOARD_newsDisplay"=>"Mostrar com notícias (menu à esquerda)",
			"DASHBOARD_publicVote"=>"Votação do público: a escolha dos eleitores é pública",
			"DASHBOARD_publicVoteInfos"=>"Considere que a votação na modalidade pública pode ser uma barreira à participação na pesquisa.",
			"DASHBOARD_dateEnd"=>"Fim das votações",
			"DASHBOARD_responseList"=>"Possíveis respostas",
			"DASHBOARD_responseNb"=>"Resposta n°",
			"DASHBOARD_addResponse"=>"Adicionar uma resposta",
			"DASHBOARD_controlResponseNb"=>"Por favor, especifique pelo menos 2 respostas possíveis",
			"DASHBOARD_votedPollNotif"=>"Atenção: assim que a enquete for votada, não será mais possível alterar o título ou as respostas",
			"DASHBOARD_voteNoResponse"=>"Por favor, selecione uma resposta",
			"DASHBOARD_exportPoll"=>"Baixar os resultados da pesquisa em PDF",
			"DASHBOARD_exportPollDate"=>"resultado da pesquisa para",

			////	MOD : FILE
			////
			"FILE_MODULE_NAME"=>"Arquivos",
			"FILE_MODULE_DESCRIPTION"=>"Administração de Arquivos",
			"FILE_OPTION_adminRootAddContent"=>"Somente o administrador pode adicionar itens no diretório raiz",
			"FILE_addFile"=>"Adicionar arquivos",
			"FILE_addFileAlert"=>"Os diretórios do servidor não são acessíveis para gravação! Por favor, entre em contato com o administrador",
			"FILE_downloadSelection"=>"Baixar a seleção",
			"FILE_fileDownload"=>"Baixar",
			"FILE_fileSize"=>"Tamanho do arquivo",
			"FILE_imageSize"=>"Tamanho da imagem",
			"FILE_nbFileVersions"=>"versões de arquivo",
			"FILE_downloadsNb"=>"(baixado --NB_DOWNLOAD-- vezes)",
			"FILE_downloadedBy"=>"arquivo enviado por",
			"FILE_addFileVersion"=>"Adicionar nova versão do arquivo",
			"FILE_noFile"=>"Não há arquivo neste momento",
			// Edit
			"FILE_fileSizeLimit"=>"Os arquivos não devem exceder",
			"FILE_uploadSimple"=>"Envio simples",
			"FILE_uploadMultiple"=>"Enviar múltiplos",
			"FILE_imgReduce"=>"Otimizar a imagem",
			"FILE_updatedName"=>"O nome do arquivo será substituído pela nova versão",
			"FILE_fileSizeError"=>"Arquivo muito grande",
			"FILE_addMultipleFilesTooltip"=>"Pressione '⌘' ou 'Ctrl' para selecionar vários arquivos",
			"FILE_selectFile"=>"Por favor, escolha pelo menos um arquivo",
			"FILE_fileContent"=>"conteúdo",
			// Versions
			"FILE_versionsOf"=>"Versões de",
			"FILE_confirmDeleteVersion"=>"Confirma a eliminação desta versão?",

			////	MOD : CALENDAR
			////
			"CALENDAR_MODULE_NAME"=>"Calendários",
			"CALENDAR_MODULE_DESCRIPTION"=>"Calendários pessoal e calendários compartilhados",
			"CALENDAR_OPTION_adminAddRessourceCalendar"=>"Somente o administrador pode adicionar recursos de calendários",
			"CALENDAR_OPTION_adminAddCategory"=>"Somente o administrador pode adicionar categorias de eventos",
			"CALENDAR_OPTION_createSpaceCalendar"=>"Criar um calendário compartilhado para o espaço",
			"CALENDAR_CAT_menuTooltip"=>"Mostrar somente eventos com categoria",
			"CALENDAR_CAT_showAll"=>"Todas as categorias",
			"CALENDAR_CAT_showAllTooltip"=>"Mostrar todas as categorias",
			"CALENDAR_CAT_undefined"=>"Sem categoria",
			"CALENDAR_CAT_editTitle"=>"Edite as categorias",
			"CALENDAR_CAT_editInfo"=>"Cada categoria de evento pode ser modificada por seu autor ou pelo administrador geral",
			"CALENDAR_CAT_editAdd"=>"Adicionar uma categoria de evento",
			"CALENDAR_moduleAlwaysEnabledInfo"=>"Os usuários que não desativaram seu calendário pessoal em seu perfil de usuário ainda verão o módulo Calendário na barra de menus.",
			"CALENDAR_calsList"=>"Calendários disponíveis",
			"CALENDAR_hideAllCals"=>"Ocultar todos os calendários",
			"CALENDAR_printCalendars"=>"Imprimir calendários",
			"CALENDAR_printCalendarsInfos"=>"imprimir a página no modo horizontal",
			"CALENDAR_addSharedCalendar"=>"Adicionar um calendário compartilhado",
			"CALENDAR_addSharedCalendarTooltip"=>"Adicionar um calendário compartilhado: para reservar um quarto, veículo, vídeo, etc.",
			"CALENDAR_exportIcal"=>"Exportar eventos (iCal)",
			"CALENDAR_icalUrl"=>"Copie endereço web (URL) para apresentar o calendário de um calendário externo",
			"CALENDAR_icalUrlCopy"=>"Permite o acesso de leitura ao calendário a partir de um calendário externo, como o Thunderbird, Outlook, Google Calendar, etc.",
			"CALENDAR_importIcal"=>"Importar eventos (iCal)",
			"CALENDAR_ignoreOldEvt"=>"Não importe eventos com mais de um ano",
			"CALENDAR_importIcalPresent"=>"Já está presente?",
  			"CALENDAR_importIcalPresentInfo"=>"Evento já presente no calendário ?",
			"CALENDAR_display_1Day"=>"1 dia",
			"CALENDAR_display_3Days"=>"3 dias",
			"CALENDAR_display_7Days"=>"7 dias",
			"CALENDAR_display_week"=>"Semana",
			"CALENDAR_display_workWeek"=>"Semana de trabalho",
			"CALENDAR_display_month"=>"Mês",
			"CALENDAR_yearWeekNum"=>"Ver a semana n°",
			"CALENDAR_periodNext"=>"Período seguinte",
			"CALENDAR_periodPrev"=>"Período anterior",
			"CALENDAR_evtAffects"=>"No calendario de",
			"CALENDAR_evtAffectToConfirm"=>"Pendente no calendario de",
			"CALENDAR_evtProposition"=>"Eventos propostos a serem confirmados",
			"CALENDAR_evtProposedBy"=>"Propostos por",
			"CALENDAR_evtProposeConfirm"=>"Confirmar a proposta",
			"CALENDAR_evtProposeConfirmed"=>"A proposta do evento foi integrada à agenda",
			"CALENDAR_evtProposeConfirmedMail"=>"Sua proposta de evento foi confirmada",
			"CALENDAR_evtProposeDecline"=>"Rejeitar a proposta",
			"CALENDAR_evtProposeDeclined"=>"A proposta foi rejeitada",
			"CALENDAR_evtProposeDeclinedMail"=>"Sua proposta de evento foi rejeitada",
			"CALENDAR_evtDelete"=>"Remover evento",
			"CALENDAR_evtDeleteCal"=>"Remover o evento deste calendário",
			"CALENDAR_evtDeleteDate"=>"Remover o evento nesta data",
			"CALENDAR_evtPrivate"=>"Evento privado",
			"CALENDAR_evtAutor"=>"Eventos que criei",
			"CALENDAR_evtAutorInfo"=>"Mostrar somente os eventos que criei",
			"CALENDAR_evtChangeTime"=>"Mover para",
			"CALENDAR_evtChangeTimeConfirmed"=>"O evento foi movido com sucesso",
			"CALENDAR_noEvt"=>"Não há eventos",
			"CALENDAR_noCalendarDisplayed"=>"Sem calendário",
			// Evenement
			"CALENDAR_importanceNormal"=>"Importância normal",
			"CALENDAR_importanceHight"=>"Alta importância",
			"CALENDAR_visibilityPublic"=>"Visibilidade normal",
			"CALENDAR_visibilityPublicHide"=>"Visibilidade de intervalo de tempo",
			"CALENDAR_visibilityPrivate"=>"Visibilidade privada",
			"CALENDAR_visibilityTooltip"=>"Para pessoas que apenas têm acesso de leitura ao calendário: <br>- Visibilidade de intervalo de tempo : mostrar a hora ocupada pelo evento e ocultar os detalhes<br>- Visualização privada: não apresentar o evento",
			// Edit
			"CALENDAR_sharedCalendarDescription"=>"Calendario compartilhado do espaço",
			"CALENDAR_noPeriodicity"=>"Uma vez",
			"CALENDAR_period_weekDay"=>"Cada semana",
			"CALENDAR_period_month"=>"Todos os meses",
			"CALENDAR_period_monthDetail"=>"Todo o --DATE-- do mês",
			"CALENDAR_period_year"=>"Todos os anos",
			"CALENDAR_period_yearDetail"=>"Toda a --DATE-- do ano",
			"CALENDAR_periodDateExceptions"=>"Exceção da repetição",
			"CALENDAR_periodDateEnd"=>"Fim da repetição",
			"CALENDAR_calendarAffectations"=>"Atribuição a calendários",
			"CALENDAR_addEvt"=>"Adicionar um evento",
			"CALENDAR_addEvtTooltip"=>"Adicionar um evento",
			"CALENDAR_addEvtTooltip2"=>"Adicionar o evento ao calendário",
			"CALENDAR_proposeEvtTooltip"=>"Propor um evento para este calendário (legível):<br> De seguida, validado pelo proprietário do calendário",
			"CALENDAR_verifCalNb"=>"Por favor, selecione pelo menos um calendário",
			"CALENDAR_busyTimeSlot"=>"A vaga já está ocupada neste calendário:",
			"CALENDAR_timeSlot"=>"Intervalo de tempo da tela ''semana''",
			"CALENDAR_propositionNotif"=>"Notificar por e-mail de cada proposta de evento",
			"CALENDAR_propositionNotifTooltip"=>"Nota: Cada proposta de evento é validada ou invalidada pelo administrador do calendário.",
			"CALENDAR_propositionGuest"=>"Os convidados podem propor eventos",
			"CALENDAR_propositionGuestTooltip"=>"Nota: Lembre-se de selecionar 'todos os usuários e convidados' em direitos de acesso.",
			"CALENDAR_propositionE-mailSubject"=>"Novo evento proposto por",
			"CALENDAR_propositionE-mailMessage"=>"Novo evento proposto por --AUTOR_LABEL-- : &nbsp; <i><b>--EVT_TITLE_DATE--</b></i> <br><i>--EVT_DESCRIPTION--</i> <br>Acesse seu espaço para confirmar ou cancelar esta proposta",

			////	MOD : FORUM
			////
			"FORUM_MODULE_NAME"=>"Fórum",
			"FORUM_MODULE_DESCRIPTION"=>"Fórum",
			"FORUM_OPTION_adminAddSubject"=>"Somente o administrador pode adicionar assuntos",
			"FORUM_OPTION_adminAddTheme"=>"Somente o administrador pode adicionar tópicos",
			"FORUM_CAT_menuTooltip"=>"Mostrar apenas assuntos com tópico",
			"FORUM_CAT_showAll"=>"Todo os tópicos",
			"FORUM_CAT_showAllTooltip"=>"Mostrar todos os temas",
			"FORUM_CAT_undefined"=>"Sem tópico",
			"FORUM_CAT_editTitle"=>"Editar tópicos",
			"FORUM_CAT_editInfo"=>"Cada tópico pode ser modificado pelo seu autor ou pelo administrador geral",
			"FORUM_CAT_editAdd"=>"Adicionar um tópico",
			"SORT_dateLastMessage"=>"última mensagem",
			"FORUM_forumRoot"=>"Início do fórum",
			"FORUM_subject"=>"assunto",
			"FORUM_subjects"=>"assuntos",
			"FORUM_message"=>"mensagem",
			"FORUM_messages"=>"mensagens",
			"FORUM_lastMessageFrom"=>"última mensagem",
			"FORUM_noSubject"=>"Sem assunto no momento",
			"FORUM_subjectBy"=>"assunto de",
			"FORUM_addSubject"=>"Novo assunto",
			"FORUM_displaySubject"=>"Mostrar o assunto",
			"FORUM_addMessage"=>"Responder",
			"FORUM_quoteMessage"=>"Responder",
			"FORUM_quoteMessageInfo"=>"Responder e citar essa mensagem",
			"FORUM_notifyLastPost"=>"Notificar por e-mail",
			"FORUM_notifyLastPostTooltip"=>"Quero receber uma notificação por e-mail para cada nova mensagem",
			"FORUM_notifOnlyReadAccess"=>"Se houver apenas acesso à leitura, ninguém poderá contribuir com o assunto.",
			"FORUM_notifWriteAccess"=>"O acesso de ''escrita'' é destinado aos moderadores:<br>Se for necessário, prefira os direitos de ''escrita limitada''",

			////	MOD : TASK
			////
			"TASK_MODULE_NAME"=>"Tarefas",
			"TASK_MODULE_DESCRIPTION"=>"Tarefas",
			"TASK_OPTION_adminRootAddContent"=>"Somente o administrador pode adicionar itens no diretório raiz",
			"TASK_OPTION_adminAddStatus"=>"Somente o administrador pode criar status Kanban",
			"TASK_CAT_menuTooltip"=>"Mostrar apenas tarefas com estado",
			"TASK_CAT_showAll"=>"Todos os estados",
			"TASK_CAT_showAllTooltip"=>"Mostrar todos os status",
			"TASK_CAT_undefined"=>"Status indefinido",
			"TASK_CAT_editTitle"=>"Editar os estados",
			"TASK_CAT_editInfo"=>"Cada estado pode ser modificado pelo seu autor ou pelo administrador geral.",
			"TASK_CAT_editAdd"=>"Adicionar um estado",
			"SORT_priority"=>"Prioridade",
			"SORT_advancement"=>"Progresso",
			"SORT_dateBegin"=>"Data de início",
			"SORT_dateEnd"=>"Data de fim",
			"TASK_addTask"=>"Adicionar uma tarefa",
			"TASK_noTask"=>"Nenhuma tarefa no momento",
			"TASK_advancement"=>"Progresso",
			"TASK_advancementAverage"=>"Progresso médio",
			"TASK_priority"=>"Prioridade",
			"TASK_priorityUndefined"=>"Prioridade indefinida",
			"TASK_priority1"=>"Baixa",
			"TASK_priority2"=>"média",
			"TASK_priority3"=>"alta",
			"TASK_assignedTo"=>"Atribuído a",
			"TASK_advancementLate"=>"Progresso atrasado",
			"TASK_folderDateBeginEnd"=>"Data de início mais antiga/última data de término",

			////	MOD : CONTACT
			////
			"CONTACT_MODULE_NAME"=>"Contatos",
			"CONTACT_MODULE_DESCRIPTION"=>"Diretório de contatos",
			"CONTACT_OPTION_adminRootAddContent"=>"Somente o administrador pode adicionar itens no diretório raiz",
			"CONTACT_addContact"=>"Adicionar um contato",
			"CONTACT_noContact"=>"Nenhum contato ainda",
			"CONTACT_createUser"=>"Criar um usuário neste espaço",
			"CONTACT_createUserConfirm"=>"Criar um usuário neste espaço com este contato?",
			"CONTACT_createUserConfirmed"=>"O usuário foi criado",

			////	MOD : LINK
			////
			"LINK_MODULE_NAME"=>"Favoritos",
			"LINK_MODULE_DESCRIPTION"=>"Favoritos",
			"LINK_OPTION_adminRootAddContent"=>"Somente o administrador pode adicionar itens no diretório raiz",
			"LINK_addLink"=>"Adicionar um link",
			"LINK_noLink"=>"Sem links no momento",
			"LINK_adress"=>"Endereço Web",

			////	MOD : MAIL
			////
			"MAIL_MODULE_NAME"=>"E-mails",
			"MAIL_MODULE_DESCRIPTION"=>"Enviar mensagens de e-mail com um único clique!",
			"MAIL_specifyMail"=>"Por favor, especificar ao menos um destinatário",
			"MAIL_title"=>"Assunto do e-mail",
			"MAIL_description"=>"Mensagem de e-mail",
			"MAIL_historyTitle"=>"Histórico dos e-mails enviados",
			"MAIL_delete"=>"Excluir este e-mail",
			"MAIL_resend"=>"Reenviar este e-mail",
			"MAIL_resendInfo"=>"Recuperar o conteúdo deste e-mail e integrá-lo diretamente ao editor para um novo envio",
			"MAIL_historyEmpty"=>"Sem e-mail",
		);
	}

	/*
	 * Jours Fériés de l'année
	 */
	public static function publicHolidays($year)
	{
		$dateList[$year."-01-01"]="Ano Novo";
		$dateList[$year."-04-25"]="Dia da Liberdade";
		$dateList[$year."-05-01"]="Dia do Trabalhador";
		$dateList[$year."-06-10"]="Dia de Portugal";
		$dateList[$year."-08-15"]="Assunção de Nossa Senhora";
		$dateList[$year."-10-05"]="Implantação da República";
		$dateList[$year."-11-01"]="Dia de Todos-os-Santos";
		$dateList[$year."-12-01"]="Restauração da Independência";
		$dateList[$year."-12-08"]="Imaculada Conceição";
		$dateList[$year."-12-25"]="Natal";
		if(function_exists("easter_date")){
			$easterTime=easter_date($year);
			$dateList[date('Y-m-d',$easterTime-(86400*2))]	="Sexta-feira Santa";
			$dateList[date('Y-m-d',$easterTime)]			="Domingo de Páscoa";
			$dateList[date('Y-m-d',$easterTime+(86400*60))]	="Corpo de Deus";
		}
		$tmpDates=Txt::timeChangeDates($year);
		$dateList[$tmpDates["summer"]]="Horário de verão";
		$dateList[$tmpDates["winter"]]="Horário de inverno";
		return $dateList;
	}
}